### PR TITLE
Bump to 0.8.5

### PR DESCRIPTION
**Pull request by garyb**
Unless there's anything else that should go in? The 0.8.5 milestone is empty now at least!

### CODE REVIEW

**Comment by garyb** [comment]
I think this covers the changelog stuff:

---

## New features

- Fast recompilation for single files in `psc-ide-server` #1712 (@kRITZCREEK, @paf31)

  The [`pscid`](https://github.com/kRITZCREEK/pscid) project makes use of this to watch files as you work and raise errors and warnings when they occur with near instant feedback.
  
- Operator aliases can now be declared for types #416 (@garyb)

  ``` purescript
  infixr 6 type Natural as ~>
  ```

- Underscore wildcards can now be used in `case` and `if` expressions #1558 (@garyb)

  ``` purescript
  case _ of
    Something -> ...
  ```
  ``` purescript
  -- underscores can optionally be used in any "slot" in the expression
  cond = if _ then _ else _
  picker = if _ then "x" else "y"
  ```
- Typed holes #1283 (@garyb)

  ``` purescript
  example :: forall a. Maybe a -> Unit
  example ma = ?umm
  ```
  ```
  Hole 'umm' has the inferred type

    Unit

  in value declaration example
  ```
  You can use any literal name after the question mark and that will be used to label the hole in the raised error message.

## Enhancements

- Improved error messages for invalid FFI identifiers #2011 (@hdgarrood)
- `psc-publish` now allows publishing of packages with a valid SPDX license field in `bower.json` #1985 (@hdgarrood)
- Haddock markdown fix #2001 (@trofi)
- `psc-ide` now creates the `output` folder on startup if it is missing #2030 (@kRITZCREEK)

## Bug fixes

- Fixed an issue with incorrect suggestions when re-exporting modules #1862 (@garyb)
- Fixed an issue with invalid redundant import warnings #1823 (@garyb)
- Fixed an issue where `DuplicateSelectiveImport` would not fire when it should #2004 (@garyb)
- Fixed the error that occurs when an invalid newtype is created that belongs to a data binding group  #1895 (@garyb)
- Fixed a case where re-exports included unintended exports #1872 (@garyb)
- Operator aliases can now be declared for qualified data constructors #2015 (@LiamGoodacre)
- A single `hiding` import will no longer raise an "unspecified imports" error #2017  (@garyb)
- Fixed a case where cycles in modules were being detected when they do not occur #2018 (@garyb)
- Various cases where files were not being read as UTF-8 on Windows were fixed #2027, #2031 (@garyb, @kRITZCREEK)

**Comment by hdgarrood** [comment]
I might add that it no longer requires a LICENSE file to be present, since a few people were inconvenienced by that. Also just be aware that the CI binary bundle publishing mechanism is currently broken, at least on Travis. I now have access to all three supported OSes so I can help create binary bundles manually if you want.

:+1:

**Comment by jplatte** [comment]
`.travis.yml` still references `bundle/build.sh` which doesn't exist anymore. So deploying will pretty certainly fail. See #2034

**Comment by paf31** [comment]
Looks great! I haven't done a great deal of testing myself yet, but if others have, feel free to tag a release.

I think we should focus on 0.9.0 after this, and put other PRs on hold until we can get everything in there deprecated/updated/whatever.

**Comment by paf31** [comment]
@hdgarrood How is the binary bundling broken on Travis?

**Comment by garyb** [comment]
@paf31 yep, my thoughts exactly, these things I've fixed or added were the few remaining annoyances I had that cropped up daily, or were just easy to fix. I'm all about getting 0.9 out next, so we can finally fix up the library warning situation.

**Comment by paf31** [comment]
Oh, no complaints here, I think this is going to be an amazing release. I just think 0.9 and the new core libraries will be great to have too 😄

**Comment by hdgarrood** [comment]
@paf31 what @jplatte said, it's the same as what I wrote in #2034.

**Comment by paf31** [comment]
Released!

**Pull request merged**
