### PR TITLE
Format parse errors uniformly (#1098)

### PR DESCRIPTION
**Pull request by epost**
Before:

    /opt/purescript-0.7.1/psc ParseError.purs
    Error found:
    Unable to parse module:
      "/Users/erik/dev/ex/examples-purescript/purescript-0.7-project/error-msg-formats/ParseError.purs" (line 3, column 1):
    unexpected end of input
    expecting binder or indentation
    See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information, or to contribute content related to this error.

After:

    /Users/erik/dev/3rdparty/purescript-stack/.stack-work/install/x86_64-osx/lts-3.1/7.10.2/bin/psc ParseError.purs
    Error found:
    Error at /Users/erik/dev/ex/examples-purescript/purescript-0.7-project/error-msg-formats/ParseError.purs line 3, column 1 - line 3, column 1:
      Unable to parse module:
        unexpected end of input
        expecting binder or indentation
    See https://github.com/purescript/purescript/wiki/Error-Code-ErrorParsingModule for more information, or to contribute content related to this error.

### CODE REVIEW

**Comment by paf31** [comment]
Looks a million times better :) Is this code ripped out of Parsec by any chance? Probably worth noting that around the code, with a link to the original, if so. The existing LICENSE file should cover the usage I think.

**Comment by epost** [comment]
Yes; there is a comment to that effect, but it doesn't have a link yet. Would you like me to add one?

**Comment by paf31** [comment]
If you don't mind, I think it'd be useful.

**Comment by epost** [comment]
Voila!

**Comment by paf31** [comment]
Cool, hopefully I'll merge this into 0.7.4 this afternoon. :+1:

**Comment by epost** [comment]
That'd be awesome! :)

**Pull request merged**
