### PR TITLE
Hints

### PR DESCRIPTION
**Pull request by paf31**
@garyb Does this look ok? I think it simplifies things nicely and gives a nicer set of error messages.

Basically the new simplification rules is: take at most one hint from each hint category.

Thanks.

### CODE REVIEW

**Comment by paf31** [comment]
I'd say this resolves #1357.

**Comment by paf31** [comment]
This also simplifies the approach to position info slightly. Position errors always get consed to the front of the hint list, which means the most specific position data is usually at the end of the list. By reversing before picking unique hints by category, we automatically get the most specific position info.

**Comment by paf31** [comment]
I don't know if this was fixed by this change or something else, but #908 is definitely working on this branch.

Resolves #908

**Comment by paf31** [comment]
Resolves #909

**Comment by garyb** [comment]
Sounds awesome, but think this will take me a while to digest, so it'll probably be tomorrow before I get time to read it properly.

**Comment by paf31** [comment]
@garyb Unless you see anything major, I'll tidy a couple of things up and merge into `box-errors`, then everything can be reviewed together. Sound good?

**Comment by garyb** [comment]
Sure thing. Code looks good to me too, I haven't tried it out yet but the idea behind it sounds solid.

**Pull request merged**
