### PR TITLE
#1712, fast recompilation in psc-ide-server

### PR DESCRIPTION
**Pull request by paf31**
@kRITZCREEK  and I are still working on this, but I'll put the code here for early review anyway.

Still to do:

- [x] Get all transitive dependencies and topologically sort them in the "load all" command
- [ ] Pass warnings back to the editor
- [ ] Handle foreign modules
- [x] Move code into its own module
- [x] Make output file into a command parameter

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
I'll look into the last two points now :)

**Comment by kRITZCREEK** [comment]
The CI failure seems to be about dependency conflicts.

**Comment by hdgarrood** [comment]
I think that CI failure can safely be ignored:

> transformers-compat-0.5.1.4 failed while downloading the package. The exception was: user error (Failed to download http://hackage.haskell.org/packages/archive/transformers-compat/0.5.1.4/transformers-compat-0.5.1.4.tar.gz: ErrorMisc "Error HTTP code: 503")

**Comment by paf31** [comment]
I'll restart Travis now.

**Comment by kRITZCREEK** [comment]
I think it makes sense to work on this after #1967 is finished. Then we can write tests that instruct the server and not have to drop into the editor/fiddle with ghci too much.

**Comment by kRITZCREEK** [comment]
Did some more work on this in #1998

**Pull request closed without merging**
