### PR TITLE
Remove meet judgment, #1719

### PR DESCRIPTION
**Pull request by paf31**
For 0.9.

Tested with Halogen.

### CODE REVIEW

**Comment by paf31** [comment]
@garyb Would you mind reviewing this one? I'd like to put it into 0.8.3 if possible, since we'll have other type checker changes and we can test them all at once.

**Comment by garyb** [comment]
Looks good, and the branch name almost suits my vegetarian preferences too. :wink:

Do you remember why this was done with `meet` rather than unification in the first place?

**Comment by paf31** [comment]
It was a fix for a weird corner case related to subsumption vs. unification, but I think the actual issue was caused elsewhere. In any case, I think we should be using unification here. We can always use a type annotation to force checking mode in any particularly weird cases where this is an issue.

**Comment by garyb** [comment]
Sounds good to me.

**Pull request merged**
