### PR TITLE
Stackage

### PR DESCRIPTION
**Pull request by phadej**
Update travis scripts. Update to use [container infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/). Builds seems to start faster, but also to take longer (maybe it's the time of the day though).

This is motivated by https://github.com/purescript/purescript/issues/684 issue. I don't see any problems of adding purescript to stackage.

### CODE REVIEW

**Comment by mjgpy3** [comment]
:+1:

**Comment by hdgarrood** [comment]
I'm just trying to understand what's going on here - I thought all that was necessary for getting on Stackage was putting your package name into their build-constraints.yaml file, and then they contact you if there are any problems? What is accomplished by checking that it builds with Stackage in the CI build here?

**Comment by phadej** [comment]
@hdgarrood This refactors travis builds a bit, e.g. verify that `purescript` can be built against newest `lts` and `nightly` stackage snapshots. Maybe those aren't truly necessary, but with them we can be more sure when accepting other pull requests. For example nightly has upper version constraints (so not using the latest version on some package, even when for `purescript` alone build plan could use them).

**Comment by hdgarrood** [comment]
Ah, right, yeah that makes sense. Thanks for explaining.

**Comment by paf31** [comment]
Is there anything left to do on this, now that #1270 is merged?

**Comment by hdgarrood** [comment]
We could still add a couple more entries into our `env` matrix in order to verify `purescript` can be built with Stackage's `lts` and `nightly` snapshots; we don't do that currently.

Also, as Stackage is built with 7.8.4, perhaps it makes sense to switch 7.8.3 -> 7.8.4 for at least the Stackage builds, maybe also the other 7.8 builds as well? I can't see any particular reason to stick with 7.8.3.

**Comment by phadej** [comment]
I'll make a new PR

**Pull request closed without merging**
