### PR TITLE
Add SVG logo that matches system color theme

### PR DESCRIPTION
**Pull request by ptrfrncsmrph**
**Description of the change**

This replaces `logo.png` with `logo.svg`, and uses the latter in the main `README.md`. The SVG was sourced from this file: https://github.com/purescript/logo/blob/master/PS_Logo_Final.svg. Using an SVG logo allows targeting the [`prefers-color-scheme` CSS media query](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), and shows a white logo if the user has a system-wide dark color theme enabled. If the user is not using a dark theme, or if the user's browser does not support the `prefers-color-scheme` media query, the logo defaults to a fill color of `#14161a` as specified in the [PureScript logo repository](https://github.com/purescript/logo). The logo width (`392px`) is set to match the `logo.png` that it replaces.

Note that the `@media (prefers-color-scheme: dark)` will _not_ respect changes in the GitHub **Appearance** settings that don't align with system-wide settings. E.g., if a user has selected **Dark** mode in their GH settings, but their system-wide color theme is light, the logo will still be displayed as dark.

Fixes: #4001

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [X] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

<details><summary><strong>GIF</strong></summary>

</details>

### CODE REVIEW

**Comment by rhendric** [comment]
Ooh, :-1: from me for reacting to the system color and not the GitHub color. (Granted, there doesn't seem to be a way to react to the GitHub color at all, but I'd rather have things look bad for people who've enabled the experimental still-in-beta GitHub feature than for people who haven't, if I have to choose between them.)

**Comment by ptrfrncsmrph** [comment]
Oof, yeah, I'm just now realizing this is actually worse for probably a good amount of users that don't have any GitHub **Appearance** settings but have system-wide dark theme. If I can find a way to target just the GH settings I'll revisit this.

**Comment by garyb** [comment]
Great idea though! Thanks for taking a stab at it.

**Comment by i-am-the-slime** [comment]
How about something like this in the meantime?
PS_Logo_Final

**Comment by ptrfrncsmrph** [comment]
Tried a different approach here: https://github.com/purescript/purescript/pull/4003

**Pull request closed without merging**
