### PR TITLE
Parse modules in parallel

### PR DESCRIPTION
**Pull request by paf31**
This reduces the Halogen rebuild time to 0.7s on my machine, with `-N7` as the sweet spot.

### CODE REVIEW

**Comment by phadej** [comment]
is `LICENSE` edit intentional?

**Comment by paf31** [comment]
Yes, I added the license file for `parallel`.

**Comment by paf31** [comment]
But I don't know what happened with the newlines. `Glob` is a bit of a pain because its license is missing on Hackage, so I have to fix it up manually, and this happens.

**Comment by phadej** [comment]
I'd inspect what happened and try to fix history to look proper. At least in vim it's quite easy to change line-ending back and forth i.e. `:set fileformat=unix`

**Comment by paf31** [comment]
The line endings were mixed to begin with due to the way the script works.

**Comment by paf31** [comment]
Any other thoughts on this? Shall I merge?

**Comment by garyb** [comment]
Oh sorry, I missed this one. Cool! :+1:

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
