### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or another core contributor signed this repository up for Open Collective. This pull request adds financial contributors from your Open Collective https://opencollective.com/purescript ❤️

  What it does:
  - adds a badge to show the latest number of financial contributors
  - adds a banner displaying contributors to the project on GitHub
  - adds a banner displaying all individuals contributing financially on Open Collective
  - adds a section displaying all organizations contributing financially on Open Collective, with their logo and a link to their website

P.S: As with any pull request, feel free to comment or suggest changes.

  Thank you for your great contribution to the Open Source community. You are awesome! 🙌
  And welcome to the Open Collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other Open Source sustainers!

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks for the PR. I would like to wait until the financial backing actually has something to show for it before merging this - the purpose of setting up the open collective account was to pay for running costs of web services like Pursuit, Try PureScript, and the PureScript Discourse instance, but we haven't managed to get them all set up properly just yet.

**Comment by JordanMartinez** [comment]
Have all of these (Pursuit, Try PureScript, Discourse) been set up now?

**Comment by thomashoneyman** [comment]
Yes, they have.

**Review by thomashoneyman — APPROVED** [review]

**Comment by thomashoneyman** [comment]
I’m happy to add this, and I think we should if no one has an objection!

**Comment by JordanMartinez** [comment]
I'm up for adding it, but how should the readme be adjusted? I think we want to be careful to communicate that this only serves to fund those particular things and isn't currently supposed to fund more than that.

**Comment by thomashoneyman** [comment]
It’s just a badge, so I feel like that’s the responsibility of the open collective hotel

**Comment by hdgarrood** [comment]
Yeah, I’m not certain this should go here at all personally. This repository is specifically for the compiler, not the wider PureScript project in general, so putting this notice here risks people thinking that the backers listed here contribute financially to the development of the compiler, which could become a problem because we don’t want new people signing up thinking that their contributions will go towards the development of the compiler and then being disappointed to find that they aren’t.

I think we should take a step back, state what the goal here is first, and then decide what the best way of achieving it is. I guess it’s something like ‘make sure that people who contribute financially to help keep our services running are appropriately acknowledged and thanked’. If we agree with that, maybe it would be better to add a notice on purescript.org with this information, and/or to link to that notice (or maybe even directly to OpenCollective) in a footer on each of the services which are funded by the OpenCollective?

**Comment by JordanMartinez** [comment]
> If we agree with that, maybe it would be better to add a notice on purescript.org with this information, and/or to link to that notice (or maybe even directly to OpenCollective) in a footer on each of the services which are funded by the OpenCollective?

Since the funds are spent on PureScript _infrastructure_ and not the compiler development, I think adding a link on each of those infrastructure pages to the collective makes sense. I don't think those sites need it, but I agree that that would be a better location than here.

That being said, the description for the [PureScript Open Collective page](https://opencollective.com/purescript) is misleading. It says
> A strongly-typed functional programming language that compiles to JavaScript

So, it sounds like the collective supports PureScript the language, not PureScript infrastructure. Could the OC page itself should be updated to clarify that it's for supporting the infrastructure, not the compiler itself?

**Comment by thomashoneyman** [comment]
> So, it sounds like the collective supports PureScript the language, not PureScript infrastructure. Could the OC page itself should be updated to clarify that it's for supporting the infrastructure, not the compiler itself?

I've updated the short description to specifically state "infrastructure."

**Comment by thomashoneyman** [comment]
I am going to close this PR, since we don't want to add this notice to the main compiler repository, but I'm happy to add notices and thanks to the various infrastructure repositories, which include:

* https://github.com/purescript/registry
* https://github.com/purescript/trypurescript
* https://github.com/purescript/pursuit

**Pull request closed without merging**
