### PR TITLE
Prelude documentation

### PR DESCRIPTION
**Pull request by paf31**
Work on #852.

/cc @garyb

### CODE REVIEW

**Comment by paf31** [comment]
I'm not sure how coverage increased :)

**Comment by garyb** [comment]
Magic!

Looks great to me. Only comment is we sort of have a mixture of using `forall` and not in the laws - I'd been omitting it so far, as I think it's a little more pleasant to read without.

**Comment by paf31** [comment]
Yep, makes sense.

**Comment by paf31** [comment]
@garyb How's this?

**Comment by garyb** [comment]
:+1:

**Comment by michaelficarra** [comment]
We use "its arguments flipped" and "its arguments reversed" interchangeably. We should pick one and stick with it.

**Pull request merged**
