### PR TITLE
Marking code with backticks in error messages

### PR DESCRIPTION
**Pull request by soupi**
Implementing the request at #2056, is this what we might want?

### CODE REVIEW

**Comment by paf31** [comment]
👍

**Comment by hdgarrood** [comment]
👍 from me too.

**Comment by hdgarrood** [comment]
Actually I wonder if we could make it a little more type-safe by having `markIdent :: Ident -> String` and `markProperName :: ProperName a -> String`, so that you can't accidentally apply either of the `mark` functions to something that isn't code?

**Comment by hdgarrood** [comment]
That way, you only need to call one function, too; `markIdent ident` as opposed to `markCode (runIdent ident)`.

**Comment by hdgarrood** [comment]
Sort of related, should the following two constructors have `Ident` arguments instead of `String`? https://github.com/purescript/purescript/blob/5aaf615decfe20a84be051e118260ded4743f2b0/src/Language/PureScript/Errors.hs#L128-L129

**Comment by AppShipIt** [comment]
What @hdgarrood said (I just didn't have as clear an idea how to fix it) 👍

**Comment by hdgarrood** [comment]
Also, I don't know what the right answer is here, but it might be worth considering putting the backticks directly into `typeAsBox` instead of applying this new `withBoxBackTicks` function everywhere, so that we don't have to worry about accidentally forgetting them whenever we modify functions in this module.

**Comment by garyb** [comment]
Re: the above suggestion - I'm not sure every name shown in errors comes through with an `Ident` or `ProperName` type. I think `Sugar.Names` does some stuff with strings to avoid having to specify many different error messages that differ by one word.

**Comment by hdgarrood** [comment]
Ok, then this LGTM.

**Comment by paf31** [comment]
Could you please reopen this as a PR on the 0.9 branch?

**Comment by paf31** [comment]
Thanks!

**Pull request closed without merging**
