### PR TITLE
Added semigroupOrdering instance

### PR DESCRIPTION
**Pull request by pseudonom**
It's pretty useful for sorting by multiple criteria.

### CODE REVIEW

**Comment by joneshf** [comment]
Is the failure showing that type classes must be defined before instances can use them?

Has this always been the case and we've just never run into it until now?

**Comment by garyb** [comment]
Wow, yes, that certainly seems to be the case!

**Comment by paf31** [comment]
:+1:

**Comment by garyb** [comment]
This is now merge-able, as of #903.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
