### PR TITLE
Add InvalidDerivedInstance error

### LINKED ISSUE #2595: Provide an additional reason with the 'cannot derive instance' error
Currently the following attempts to derive instances all produce a compiler error "cannot derive a type class instance for X" and nothing else:

```purescript
-- Eq has just one type argument
derive instance eqIntInt :: Eq Int Int

-- missing the wildcard type argument
derive instance genericFoo :: Data.Generic.Rep.Generic Foo

-- cannot derive this class
class Foo
derive instance foo :: Foo
```

I think it would be nice to provide a little more detail in this error message. Possible reasons the compiler might have failed to derive an instance that I can think of:

* It's not aware of the class
* The instance was given the wrong number of type arguments (in particular, I think `derive instance genericFoo :: Generic Foo` missing the second wildcard might be a common mistake)

It's also possible that we might later add more reasons to this list as the compiler is able to derive more instances.

### PR DESCRIPTION
**Pull request by paf31**
Fixes #2595

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks good, although ideally I think this would go a little further and introduce another new type of error, to be used when the class is not known to the compiler, of the form "Don't know how to derive the type class Foo". Also I think it should be feasible to hardcode the expected number of arguments for each type class that has special compiler support for instance deriving, so that we can give better error messages (i.e. "Eq expects 1 type argument but has been given 2" rather than "the form of the derived instance is incorrect, make sure it has the correct number of type arguments").

:+1: to merge now if doing that is a lot of extra effort, but I think I would rather keep #2595 open until these things have also been addressed.

**Comment by paf31** [comment]
> ideally I think this would go a little further and introduce another new type of error, to be used when the class is not known to the compiler

That is `CannotDeriveInstance`, right?

👍 for adding the argument count to the error.

**Comment by hdgarrood** [comment]
There's `CannotDerive`, but it doesn't say why.

**Comment by paf31** [comment]
Right, but the only reason we use that error message is because the class is not one for which we support deriving. So I think "Cannot derive `Foo ...`" is a fine error in that case, no?

**Comment by hdgarrood** [comment]
It's fine, but I think it would be better to say why (especially if this change means that the only reason you'd get a `CannotDerive` is indeed that the type class is not one for which deriving is supported; that's not the case right now AFAIK).

**Comment by hdgarrood** [comment]
Agh, sorry I'm talking past you a bit; I've been travelling most of today and I'm quite tired.

**Comment by paf31** [comment]
No, that sounds good. I'll improve the message on my next pass at this.

**Comment by paf31** [comment]
@hdgarrood How's this?

**Comment by garyb** [comment]
Well I like it :smile:

"Type argument" or "Type parameter" though? I guess they're much the same.

**Comment by paf31** [comment]
I tend to say "type argument", but if we use "parameter" elsewhere then we should be consistent.

**Comment by paf31** [comment]
Ok, I'll merge this then, and we can fix up any remaining issues in a separate PR if need be.

**Comment by hdgarrood** [comment]
Looks good to me too :)

**Pull request merged**
