### PR TITLE
Extended object literals

### LINKED ISSUE #384: Extended Object Literals / Object Sections
I don't like the idea of implementing Scala-like argument placeholders (e.g. `map (_.foo)`) in full generality, but it seems there is a very useful (and much less syntactically ambiguous) specialization of the idea, which can be used to construct objects.

This change would cause the following

```
{ foo: _, bar: _, baz: "baz" }
```

to desugar to

```
\foo bar -> { foo: foo, bar: bar, baz: "baz" }
```

This would be very useful for things like applicative notation:

```
{ foo: _, bar: _, baz: "baz" } <$> readFoo <*> readBar
```

### PR DESCRIPTION
**Pull request by garyb**
This will resolve #384 when done... but it's not a real PR right now. I seem to have broken the linker?

### CODE REVIEW

**Comment by garyb** [comment]
It seems to be traversal related. It starts failing when reduced to this:

```
desugarObjectConstructors :: Module -> Module
desugarObjectConstructors (Module mn ds exts) = Module mn (map desugarDecl ds) exts

desugarDecl :: Declaration -> Declaration
desugarDecl d =
  let (f, _, _) = everywhereOnValues id id id
  in f d
```

**Comment by paf31** [comment]
I think you need to add your new module to the Cabal file.

This looks good though, I'm excited to try it out.

**Comment by garyb** [comment]
Duh, of course! It's obviously been too long since I worked on this. :)

**Comment by paf31** [comment]
I just looked at the code. It looks great, but I have a couple of comments:

- I wonder if the syntax could be simplified to something like `{ specified: 1, unspecified }`, meaning `\unspecified -> { specified: 1, unspecified: unspecified }`
- Could you please add an example?

Thanks.

**Comment by garyb** [comment]
Yep, no problem. I've not even tried it yet with the whole linker thing.

**Comment by garyb** [comment]
With the syntax thing, we could definitely do it without the `_`, but I figure that aligns quite nicely with if we do the `_.x` as syntactic sugar for `(\obj -> obj.x)` thing too? Or did you not want to do that anyway?

Also, do we want `obj { x = _ }` too? That might be handy.

**Comment by paf31** [comment]
I like the `_.x` idea, but I think I'd like to find a use case for updates before we implement it.

**Comment by garyb** [comment]
I was thinking for applicative style again, for instance the stuff I was looking at in names:

```
addValue env mn name = updateExportedModule env mn $ \m -> do
  values <- addExport (exportedValues m) name
  return $ m { exportedValues = values }
```
Could be:
```
addValue :: ExportEnvironment -> ModuleName -> Ident -> Either ErrorStack ExportEnvironment
addValue env mn name = updateExportedModule env mn $ \m ->
  m { exportedValues = _ } <$> addExport (exportedValues m) name
```

**Comment by paf31** [comment]
Interesting - we could definitely add it and see how we like it.

**Comment by garyb** [comment]
Updated with stuff working now. This is going to be super nice :)

Can either merge now if you're happy, or hold off until the property/update stuff is done too?

**Comment by paf31** [comment]
Looks great :)

Does `test-everything` work? I'm always wary of parser changes.

Otherwise, :ship:

**Comment by paf31** [comment]
Maybe we can do something about the coverage first though :P

**Comment by paf31** [comment]
Oh, it's a test failure. Never mind...

**Comment by garyb** [comment]
Huh, that's odd! Will figure it out in a sec.

Yep, `test-everything` still works. The only slight change now is `_` is never a valid identifier on its own, previously it would have been treated as a variable so the error would have been `_ is undefined` whereas now it's treated as a parse failure.

**Comment by garyb** [comment]
Whoops, I broke type wildcards and somehow managed not to run the tests... fixing now.

**Comment by garyb** [comment]
Finally...

**Comment by paf31** [comment]
:+1:

**Pull request merged**
