### PR TITLE
Document the remaining Prelude modules, fix #852

### LINKED ISSUE #852: Document all Prelude functions
The generated markdown docs now contain code comments, so we should start documenting all public functions in the core libraries. The Prelude would be a good place to start.

This involves a bit of work, but would be a fantastic contribution for any beginners.

### PR DESCRIPTION
**Pull request by paf31**
@garyb @hdgarrood Could you please review?

### CODE REVIEW

**Comment by garyb** [comment]
Looks good!

Could perhaps include the ```compare `on` bar``` style example for `on` as well? Or do you think people will get that usage from the example you gave?

**Comment by hdgarrood** [comment]
Looks good to me too. I feel like we only need one example of usage of `on`. I like this one - using `(>)` rather than `compare` means that people coming from languages that use `int` for comparisons instead of an actual `Ordering` type have fewer new concepts to get their heads around. I don't feel particularly strongly either way though.

**Comment by garyb** [comment]
That makes sense.

**Comment by paf31** [comment]
I agree that we only need one, but I'm going to change it to use `compare`, since I think it's more idiomatic.

**Comment by paf31** [comment]
How does this look? I picked a slightly more interesting function for the RHS too.

**Comment by hdgarrood** [comment]
:+1:

**Pull request merged**
