### PR TITLE
Add --require-path options to psc-bundle

### LINKED ISSUE #1605: psc-bundle doesn't work when code has been built with `--require-path`
I like to build with `--require-path=../` to avoid `node_modules` hackery, and `psc-bundle` [expects all require statements to be unprefixed](https://github.com/purescript/purescript/blob/dc54faf480c3e5dd64da69ef6b7e21d31bf17016/src/Language/PureScript/Bundle.hs#L145-L146). Should `psc-bundle` support `--require-path` as well?

### PR DESCRIPTION
**Pull request by natefaubion**
Fixes #1605

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks good. I can't test right now, but I can merge this evening if you think it works how one would expect.

**Comment by natefaubion** [comment]
I've tested it on a small hello world app with and without the require-path, it works identically as before in the latter case, and using require-path yields identical results in the former case.

**Comment by paf31** [comment]
Ack, sorry, could you please rebase this?

**Comment by natefaubion** [comment]
Done.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
