### PR TITLE
v0.13.7

### LINKED ISSUE #3886: 0.13.7
@justinwoo [recently wrote about some changes he backported](https://github.com/justinwoo/my-blog-posts/blob/master/posts/2020-05-22-some-backported-purescript-changes-for-my-own-uses.md) in order to make use of some commits which are in master now, and I think the post suggests that an official 0.13.7 release is worth considering. The CBOR externs change in particular is very exciting; I hadn’t fully appreciated how big a deal that is.

As for 0.14.0: it is not that far away, but there are a few bugs in roles that we will want to fix first. I think an 0.13.7 release would take the pressure off a bit, so to speak, so that we wouldn’t feel the need to rush those fixes to get it out sooner, too.

I’m happy to do the remaining legwork to put together a release (especially since Justin has done a lot of it already anyway). Of the commits in master since 0.13.6, I think the following are candidates for backporting (because they are non-breaking changes which will be useful downstream):

- #3777 fix some bounds
- #3781 add `purs graph` for graphing module dependencies
- #3789 update cache-db.json on ide rebuilds - fixes a bug which could lead to things not being rebuilt when they should be
- #3799 tracks the cache-db.json timestamp in purs ide in order to reload ide state when necessary, and get rid of polling and file watching (the flags are still present but are ignored). @kritzcreek this can be considered non breaking, right?
- #3841 binary encoding for externs
- #3850 hide compiler internals in Prim modules from ide completions
- #3843 use a single Text for module names
- #3856 extract documentation for type classes in purs ide
- #3877 Fix CoreFn JSON version parsing 

My plan is to create a branch off 0.13.6, try to pull these commits in one by one, and see how far I get.

### PR DESCRIPTION
**Pull request by hdgarrood**
Resolves #3886. I've successfully backported all of the commits I listed in #3886 and pushed them to the 0.13.x branch in this repository already, which is why there's not much to see in this PR. This turned out to be relatively straightforward, thankfully!

### CODE REVIEW

**Comment by hdgarrood** [comment]
I'm in the process of writing release notes.

**Comment by kritzcreek** [comment]
Most of these changes are my PRs, please let me know if you need any input.

**Comment by hdgarrood** [comment]
@kritzcreek would you be able to write release notes for the change #3799? I'm not sure I fully understand its implications.

**Comment by kritzcreek** [comment]
Sure, I'll try to explain it without talking about IDE internals:
## purs ide is better at reloading changes

The IDE would previously sometimes miss changes that were made outside of the editor, like building with new dependencies or recompiling larger parts of the project on the console.

The IDE will now notice when this happened on the next command issued to it and refresh its state before processing that command. This might cause the first command after an external change to take a long time to execute, but should increase reliability in general.

**Comment by hdgarrood** [comment]
Thanks!

**Comment by hdgarrood** [comment]
Draft release notes: https://gist.github.com/hdgarrood/f0c167600036630bfe1c5fdb2729f3ca

**Comment by hdgarrood** [comment]
I say "draft" but as far as I'm concerned they're good to go, I'm just posting the link so that others can review. I think everything is now in place to go ahead with v0.13.7, so once this is approved I'll merge and do the release.

**Pull request merged**
