### PR TITLE
Fix #1246

### LINKED ISSUE #1246: psci: ability to reload FFI definitions without losing bindings from the session
This would be useful when testing things inside psci.

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb @hdgarrood

### CODE REVIEW

**Comment by paf31** [comment]
The issue seems to be that the content of the foreign module is captured inside the `MakeActions` structure.

**Comment by garyb** [comment]
Oops! It's much simpler now too, not sure why I didn't do it this way in the first place. :+1:

**Comment by garyb** [comment]
Huh, looks like the core library stuff is working now, it's one of the stackage builds that is failing.

**Comment by paf31** [comment]
@phadej Do you have any idea why this might happen? Maybe a build cache issue?

**Comment by paf31** [comment]
Looks like the sandbox is being cached between different builds, perhaps? Maybe we have to revert to no caching.

**Comment by hdgarrood** [comment]
Yeah, I think this is because of the sandbox being cached between builds (which was intended). However, oddly, it's the Stackage LTS 2.22 build that's failing; surely, if the Stackage snapshot version is fixed, none of the dependencies' versions should change? I think we should start by clearing the Travis cache and rerunning the build. I think this can be done inside Travis' web UI.

Perhaps it also makes sense to add `--force-reinstalls` to the `cabal install` command?

**Comment by paf31** [comment]
My guess is that it's using the same cache between all of the different builds?

**Pull request merged**
