### PR TITLE
Make explicit import suggestions more consistent

### PR DESCRIPTION
**Pull request by nwolverson**
It's been annoying me that while either psc-ide or the suggestions for `ImplicitImport`/`HidingImport` will suggest `Blah(..)` for the import of a type and its data constructors, but other import suggestions always suggest the explicitly listed form `Blah(Blah1, Blah2,...)`, so that the suggested imports change even when they are not relevant to the warning.

e.g. when I have used `Just`
```
Module Foo has unspecified imports, consider using the explicit form:

    import Foo (Maybe(..))
```
vs
```
The import of module Foo contains the following unused references:

    zzz

  It could be replaced with:

    import Foo (Maybe(Just))
```

This change instead uses the `(..)` form if that was used previously, but still maintains the form with explicitly listed data constructors if present. So where I have an import ```import Foo (Either(..), Maybe(Just, Nothing), zzz)```

```
The import of module Foo contains the following unused references:

    zzz

  It could be replaced with:

    import Foo (Either(..), Maybe(Just))
```

(I'd like to test this, but as far as I know existing warnings tests are just testing the error code?)

### CODE REVIEW

**Comment by nwolverson** [comment]
Uh. I guess I thought this got merged, not sure how it shows as having 32 commits. I guess this needs rebased?

**Comment by hdgarrood** [comment]
I wonder if this commit history has something to do with the 0.12 branch... I'll try to work out what's going on with that and get back to you.

**Comment by nwolverson** [comment]
Wasn't sure what happened with the 0.12 branch, seemed like some funny business - I can easily enough cherry pick the commits back on top of master. I guess it was ac18e53 80b04b0

**Comment by nwolverson** [comment]
Actually seems there was only 1 commit for this PR, I think this should be back in a sensible state.

**Comment by hdgarrood** [comment]
I tested this manually with the following input source files, comparing the behaviour on `master` with this PR: https://gist.github.com/hdgarrood/a0d2b03f6af2b73ba6c376e4be1aa4ab

This seems to work great; there's just one thing I noticed:
```purescript
module ImplicitQualifiedImport where

import Prelude
import Data.Array as M
import Data.Maybe as M

foo :: M.Maybe Unit
foo = M.Just unit
```
suggests using `import Data.Maybe (Maybe(Just)) as M`, whereas the `ImplicitImport` warning suggests using the `(..)` form; presumably these should both do the same thing too? I guess they should both suggest `(..)`?

**Comment by garyb** [comment]
> I guess they should both suggest `(..)`?

👍

**Comment by nwolverson** [comment]
Good spot, the ImplicitQualifiedImport suggestion should now be consistent with the others.

Something I did test before and I think was missing from that gist, is checking the "maintains the form with explicitly listed data constructors if present" - ie. the case of 
```
import Data.Maybe (Maybe(Just), fromMaybe)
```
when `Just` is used but not `fromMaybe`, the suggestion to remove `fromMaybe` should not alter `Maybe(Just)`, i.e. is
```
import Data.Maybe (Maybe(Just))
```
 Updated gist here https://gist.github.com/nwolverson/f94772a141c68178acb09b68f4d41cbd

**Comment by LiamGoodacre** [comment]
(I'm also not familiar with this part of the code, but this looks good :+1:)

**Comment by hdgarrood** [comment]
@garyb would you like to look over this? No rush, of course.

**Comment by garyb** [comment]
Sure thing. I'm taking a mostly-complete break from code stuff just now, but will definitely take a look in the new year :)

**Comment by kRITZCREEK** [comment]
I've built and tested this and it works nicely, thanks!

**Pull request merged**
