### PR TITLE
Make 0.15.1 release

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Update project to 0.15.1

---

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
CI failure:
```
  
  Failures:
  
    tests/TestCompiler.hs:166:7: 
    1) compiler, Warning examples, 'ImplicitQualifiedImportReExport.purs' should compile with expected warning(s)
         Test output differed from 'tests/purs/warning/ImplicitQualifiedImportReExport.out'; got:
         Warning 1 of 2:
         
           in module Main
           at tests/purs/warning/ImplicitQualifiedImportReExport.purs:9:1 - 9:23 (line 9, column 1 - line 9, column 23)
         
             Module Data.Maybe was imported as X with unspecified imports.
             As this module is being re-exported, consider using the explicit form:
         
               import Data.Maybe (Maybe(..), fromJust, fromMaybe, fromMaybe', isJust, isNothing, maybe, maybe', optional) as X
         
         
         
           See https://github.com/purescript/documentation/blob/master/errors/ImplicitQualifiedImportReExport.md for more information,
           or to contribute content related to this warning.
         
         Warning 2 of 2:
         
           in module Main
           at tests/purs/warning/ImplicitQualifiedImportReExport.purs:10:1 - 10:24 (line 10, column 1 - line 10, column 24)
         
             Module Data.Either was imported as Y with unspecified imports.
             As this module is being re-exported, consider using the explicit form:
         
               import Data.Either (Either(..), blush, choose, either, fromLeft, fromLeft', fromRight, fromRight', hush, isLeft, isRight, note, note') as Y
         
         
         
           See https://github.com/purescript/documentation/blob/master/errors/ImplicitQualifiedImportReExport.md for more information,
           or to contribute content related to this warning.
         
  
    To rerun use: --match "/compiler/Warning examples/'ImplicitQualifiedImportReExport.purs' should compile with expected warning(s)/"
```

**Comment by garyb** [comment]
I imagine the addition of `blush` means the expected error isn't exactly the same now? CI probably passed locally because you have the prior version of `either` still.

**Comment by JordanMartinez** [comment]
That would make sense. I'll submit a PR updating the tests. I think I'll also update `tailrec` to depend on its newer version as well.

**Comment by JordanMartinez** [comment]
Guilty!

**Comment by JordanMartinez** [comment]
@rhendric When this does finally get merged and released, would you make the Discourse announcement?

**Comment by rhendric** [comment]
Sure!

**Comment by JordanMartinez** [comment]
CI builds. Can I get an approval?

**Review by rhendric — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Hmm....
```console
$ npm i -g purescript
$ purs --version
0.15.2-0
$ npm i -g purescript@v0.15.1
$ purs --version
0.15.2-0
```

**Comment by rhendric** [comment]
Ah, dang it. I see the problem.

**Pull request merged**
