### PR TITLE
small fix for the copyright dates

### PR DESCRIPTION
**Pull request by seanwestfall**
Just fixing the dates on the copyright prop in package.yaml.

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
You also need to run hpack to generate the new .cabal file.

**Comment by seanwestfall** [comment]
@kRITZCREEK I ran `stack build` but it didn't affect the cabal file at all. How do you run hpack?

**Comment by hdgarrood** [comment]
What version of stack are you using? Probably just update stack and run `stack build` again.

**Comment by seanwestfall** [comment]
okay, purescript.cabal fixed. Hopefully the checks will all pass than, then this is good.

**Comment by seanwestfall** [comment]
Checks passed. :+1:

**Comment by hdgarrood** [comment]
Thank you!

**Pull request merged**
