### PR TITLE
Refer to binary using local-doc-root workaround

### LINKED ISSUE #4138: CI doesn't currently build binaries
See [the ubuntu build](https://github.com/purescript/purescript/runs/3003232309?check_suite_focus=true), which fails because the binary file that should exist at `sdist-test/.stack-work/install/x86_64-linux/0c876ca1dfc6728d04f0d922e905e8ecaa12cec66470d064293c7f7c2a261f0b/8.10.4/bin/purs` does not exist.

It seems #4072 caused an issue by introducing the `--hadock` flag.

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes #4138.

Since v0.14.3 was already tagged, how do you want to handle this situation?

---

**Checklist:**

- [ ] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by thomashoneyman** [comment]
It was tagged so recently (and without binaries) that I think we can delete the tag and tag a new release.

**Comment by JordanMartinez** [comment]
The release and tag have both been deleted

**Comment by JordanMartinez** [comment]
CI builds. Can I get an approval, so I can get this merged?

**Comment by hdgarrood** [comment]
I think this is fine for now, especially since the old release has now been deleted, but just for future reference - we don’t know what kind of automation people might have with tags and releases and repo mirrors and so on, so in the future I would prefer to err on the side of not modifying existing tags. In this case I would have created a new v0.14.4 tag instead, and a small note in the changelog that v0.14.3 isn’t a real release.

**Comment by hdgarrood** [comment]
Does using `--haddock` affect the size of the resulting binary? I’m now wondering if the binary we get will include docs somehow where it didn’t previously, causing the binary to be larger. I can’t see why else it would end up in a separate directory. If so I think the correct fix may be to avoid `--haddock` entirely, at least for release builds.

**Comment by JordanMartinez** [comment]
> we don’t know what kind of automation people might have with tags and releases and repo mirrors and so on, so in the future I would prefer to err on the side of not modifying existing tags. In this case I would have created a new v0.14.4 tag instead, and a small note in the changelog that v0.14.3 isn’t a real release.

Makes sense. Mind if I add that to the RELEASE_GUIDE.md in case this should occur again?

> Does using --haddock affect the size of the resulting binary?

I'm looking into that right now.

**Comment by hdgarrood** [comment]
Adding this to RELEASE_GUIDE.md sounds like a great idea 👍

**Comment by JordanMartinez** [comment]
```bash
# v0.14.2
ls -ls purs.bin 
48408 -rwxr-xr-x 1 jordan jordan 49561488 Jun  5 12:18 purs.bin

# binary built from this PR
$ ls -ls purs 
48500 -rwxr-xr-x 1 jordan jordan 49650640 Jul  6 17:55 purs
```
| Comparision |
| -: |
| 49,561,488 |
| 49,650,640 |

The difference is 89,152

**Comment by hdgarrood** [comment]
I think we need to be comparing the old CI script with the new one when run against the same code. What do you get if you revert only the changes in ci/build.sh but leave everything else alone?

**Comment by hdgarrood** [comment]
If the difference turns out to less than 100KB though then I think that’s safe to ignore.

**Comment by JordanMartinez** [comment]
```
$ ls -ls purs 
48496 -rwxr-xr-x 1 jordan jordan 49650640 Jul  6 18:39 purs
```
Seems to be the same binary.

**Review by thomashoneyman — APPROVED** [review]

**Review by hdgarrood — APPROVED** [review]

**Comment by hdgarrood** [comment]
Thanks for checking!

**Pull request merged**
