### PR TITLE
Allow import hiding with qualified imports

### LINKED ISSUE #1507: Allow qualified import with hiding
``` purescript
import Foo hiding (baz) as X
```

I think putting the `hiding` before the `as` is clearer than having `hiding` follow it, considering the effect this should have. Forming it this way also makes it clear why you can't combine selective imports with `hiding`, as it makes `hiding` a modifer of the selection.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1507

### CODE REVIEW

**Comment by paf31** [comment]
Looks good but don't we need to handle `hiding` in the `qualImport` branch too? Or are we just going to deprecate the `qualified` keyword?

**Comment by garyb** [comment]
Yeah I thought we were going to do that. I was trying to think of a good way to raise the warning - tagging the `ImportDefinition` with some flag and then warning during desugaring was the first thing that sprang to mind, but is there some better way we can capture warnings in the parser without resorting to that or switching parsing to use a transformer stack?

**Comment by paf31** [comment]
I'm not above using `unsafePerformIO` if we're going to remove it in 0.8 anyway :smile:

**Comment by garyb** [comment]
:scream: :laughing: 

Ok, I'll append that change to this!

**Comment by paf31** [comment]
Although having the parser run in `IO` probably isn't too difficult either. I don't mind either way.

**Comment by garyb** [comment]
Actually, I'll probably do the warn-in-desugar thing, as at least then the warnings will appear consistently with the rest.

**Comment by garyb** [comment]
Updated with the warning now, how's this?

**Comment by paf31** [comment]
:+1:

**Pull request merged**
