### PR TITLE
Fix #1276

### LINKED ISSUE #1276: PSCi has started printing "Writing..." and "Compiling..." messages again

### PR DESCRIPTION
**Pull request by paf31**
@garyb Could you please review this? I also removed the used `RebuildPolicy` stuff from `make`.

### CODE REVIEW

**Comment by paf31** [comment]
This also simplifies the progress messages a little bit. The only ones which show up now are "Compiling X..." and "Writing Y" where Y is a `.js` file.

**Comment by paf31** [comment]
I'm not even sure the Writing... messages are needed.

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
@garyb Do you think the "Reading..." messages for externs are useful at all?

While we're at it, as a professional user, are there other progress messages you'd like to see?

**Comment by garyb** [comment]
I guess the "Reading" errors are useful for bugs in reading the externs files, but since we print filenames in the error messages anyway it's not important at all.

None of the status messages are that useful to me really when building projects, I only really pay attention to any error/warning messages we might throw out. The status messages are more of a debugging thing to me, when working on the language, but even at that I've not used them for a really long time.

**Comment by garyb** [comment]
Oh, did you see this too? https://github.com/bodil/pulp/issues/52 (re: printing warnings to stderr)

**Comment by paf31** [comment]
yeah, let's fix that before 0.7.2

**Comment by paf31** [comment]
I've added it to this PR to just get it done.

**Comment by garyb** [comment]
:+1:

**Pull request merged**
