### PR TITLE
Update the support modules list in the tests

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by paf31** [comment]
👍 Thanks!

**Comment by paf31** [comment]
Is there something I need to do to get tests running? They all seem to be failing for me.

**Comment by garyb** [comment]
Hmm, no. That kinda was the point of switching back to bower, that it should "just work"... Travis is managing okay too. Perhaps clear out the stuff you have in `support` and try again?

**Comment by hdgarrood** [comment]
Should we be sharing this list across both of these modules?

**Comment by garyb** [comment]
That would make sense... I'll revise it.

**Comment by garyb** [comment]
The list is shared now.

**Comment by hdgarrood** [comment]
:+1:

**Pull request merged**
