### PR TITLE
Underscore syntax for object getters

### PR DESCRIPTION
**Pull request by garyb**

### CODE REVIEW

**Comment by paf31** [comment]
Looks good, I'll just wait for the tests to run.

**Comment by paf31** [comment]
I'll release this as 0.6.6 with the extended infix stuff.

**Comment by garyb** [comment]
Sure. They should pass, and `test-everything` was happy also.

**Comment by garyb** [comment]
Actually, I may as well add that  `_ { foo = x }` syntax too for 0.6.6 while we're at it.

**Comment by paf31** [comment]
Should I merge then?

**Comment by garyb** [comment]
I'll update this with the extra syntax first, mostly done.

**Comment by garyb** [comment]
There we go. `_ { x = _ }` also works, the underscores can appear anywhere in the updater now. `test-everything` is happy again, so once Travis completes, merge away if you're happy - I'm off to bed!

**Comment by jdegoes** [comment]
Wow, nice work!

**Comment by paf31** [comment]
Thanks again!

**Pull request merged**
