### PR TITLE
Update `build` command to run test

### PR DESCRIPTION
**Pull request by sectore**
of example test files.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Have you tested this? As far as I am aware it will still require the `--` so that `stack` knows those extra arguments are for `purs` and not for `stack`.

**Comment by sectore** [comment]
You are right, but it seems that in this case `stack` runs `purs compile` without `--`, too. I've run this command for manually tests of #2874.

For example with `--`

```
stack exec purs -- compile 'tests/support/bower_components/purescript-*/src/**/*.purs' examples/failing/2874-forall.purs
Error found:
at examples/failing/2874-forall.purs line 5, column 36 - line 5, column 36

  Unable to parse module:
  unexpected forall
```

Without `--`
```
stack exec purs compile 'tests/support/bower_components/purescript-*/src/**/*.purs' examples/failing/2874-forall.purs
Error found:
at examples/failing/2874-forall.purs line 5, column 36 - line 5, column 36

  Unable to parse module:
  unexpected forall
```

Anyway, I'll update this PR to use `--` as usual. Thanks for your feedback @hdgarrood !

**Comment by hdgarrood** [comment]
That's good to know too - maybe `stack` has changed to be a bit more smart about command arguments since I last checked.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
