### PR TITLE
Prevent codegen when `--dump-corefn` is supplied

### LINKED ISSUE #3196: Add flag to disable Javascript backend
I'm writing an alternative VimL backend for PureScript based on the CoreFn dump produced by `--dump-corefn`. That is, I haven't forked the compiler codebase. There are two things with the regular `purs compile` command that would be nice to disable:

* CommonJS module output
* Checking/inclusion of `<Module>.js` files (foreign definitions)

Specifically the latter is of interest, as I don't want to write foreign definitions for Vim-specific things for the JS backend.

At a high level, this might be considered "disabling the entire JS backend", I'd say, so I'm not sure what would be a good name for a flag to disable it. Perhaps `--no-codegen` or `--no-js-codegen`. Anyway, I could have a stab at this and provide a PR if this seems reasonable.

Thanks!

### PR DESCRIPTION
**Pull request by gabejohnson**
Fixes #3196 

I opted to implement the suggestion from https://github.com/purescript/purescript/pull/3049#issuecomment-338507346; no JS is generated when `--dump-corefn` is passed to `compile`.

### CODE REVIEW

**Comment by paulyoung** [comment]
I tried this locally but I still see JS files being created. Perhaps I'm doing something wrong.

**Comment by gabejohnson** [comment]
Can I get some 👀 on this?

**Comment by garyb** [comment]
@gabejohnson this is conflicting now #3270 has been merged - sorry, I was kinda waiting for that to go in before taking a look at this again, I probably should have mentioned!

**Comment by gabejohnson** [comment]
No worries. I'll rebranch from master and have another go at it. Curious though if you think we should go in this direction or the one mentioned in https://github.com/purescript/purescript/issues/3196#issuecomment-369389152

**Comment by garyb** [comment]
Oops, I just pushed to your branch @gabejohnson! Thought I'd branched it myself. Anyway, I updated this for latest master, but was going to tweak it a bit further to work like https://github.com/purescript/purescript/issues/3196#issuecomment-379266687 - I'll be sure to actually use my own branch for that.

**Comment by gabejohnson** [comment]
@garyb no problem. I planned to take it up again after the 0.12 release. But if you want to knock it out now, be my guest 😄

**Pull request closed without merging**
