### PR TITLE
Fix #1297, reduce memory usage from WriterT

### LINKED ISSUE #1297: psc consumes enormous amount of RAM
During update of slamdata I've noticed that builds take lot more memory. 0.6.9.7 version used to consume about 250Mb in `psc` mode and 150Mb in `psc-make` mode. Now `psc` consumes more then 4Gb :disappointed:

### PR DESCRIPTION
**Pull request by paf31**
This reduces memory usage to <100M on my machine when compiling Halogen from scratch.

The test suite hovers around ~1M usage :smile:

### CODE REVIEW

**Comment by jdegoes** [comment]
:+1: :+1: :+1: :tada: :tada: :tada: :fireworks: :fireworks: :fireworks:

**Comment by garyb** [comment]
Wonderful news! :100:

**Comment by paf31** [comment]
Note this changes the ordering of the transformers, so another subtle change is that we now get warnings _and_ errors together.

**Comment by paf31** [comment]
If someone could please review the code, I'll merge this and release 0.7.5.1.

Thanks!

**Comment by jdegoes** [comment]
:+1: Seems straightforward.

**Comment by paf31** [comment]
Thanks John. Merging..

**Comment by paf31** [comment]
Hmm, weird, CI passed but shouldn't have.

**Comment by paf31** [comment]
Ugh, warnings are all showing up twice now, which I didn't notice before. Will fix...

**Comment by paf31** [comment]
Fixed, was a small issue with `MonadBaseControl`.

**Comment by paf31** [comment]
@garyb I'll cut the 0.7.5.1 branch now, ok? It seems solid to me at least.

**Comment by garyb** [comment]
Sure thing!

**Comment by paf31** [comment]
Maybe let's give it one more day of testing, then put it on `npm`?

**Comment by paf31** [comment]
So the binary build is up and fine, but the GHC 7.6 build doesn't work because of the import of `Data.Monoid`. So, I'll push a 0.7.5.2 up to Hackage, but do we need to tag a release on GitHub for that? Does NPM build from source at all?

**Comment by paf31** [comment]
Ah, whatever, I'll just tag a 0.7.5.2 release when Travis finishes.

**Comment by garyb** [comment]
It doesn't... and unfortuantely I just got done with updating a `v0.7.5-rc.3` release on npm (using 0.7.5.1) :smile:

**Comment by garyb** [comment]
I just added a 0.7.5.1 Windows build too, will do the same for 0.7.5.2.

**Comment by paf31** [comment]
Ah well if it works, that's good. 0.7.5.1 and 0.7.5.2 are functionally the same.

**Pull request merged**
