### PR TITLE
Link to documentation repo as docs for non-Prim built-in types/kinds

### LINKED ISSUE #3459: Add `kind Row` to Prim's Docs
The best reference we have to a definition of `Row` is `Record` which is inaccurate because Rows are used in so many other places besides Records (e.g. Variant, type-level programming). I'd like to submit a PR that adds docs for it, but before I do, I want to discuss the best rendering for it. Here's my current rendering for `Row`:

> `Row` is a kind for 0 or more label-type associations where the total number of these associations is known at compile time. A label can be used to refer to an instance of the associated type.
>
> First, a row can be empty (there are no associations) or non-empty (there is at least one association). Second, it can be closed (the row contains only the label-type associations defined here) or open (the row contains at least, though it may contain more than, the label-type associations defined here). Third, it can contain duplicate 'labels'.
>
> Examples:
> Empty closed Row: `()`
> Empty open Row: `( | otherLabelTypeAssociations)`
> Non-empty closed Row: `(label1 :: TypeName1, ... , labelN :: TypeNameN)`
> Non-empty open Row: `(label1 :: TypeName1, ... , labelN :: TypeNameN | otherLabelTypeAssociations)`
> Duplicate Labels: `(someLabel :: String, someLabel :: Int)`

One open question I have. While rows can contain duplicate labels, can those labels associate different types? I'm assuming yes, but I'd like it clarified.

### PR DESCRIPTION
**Pull request by JordanMartinez**
Fixes #3459

### CODE REVIEW

**Comment by hdgarrood** [comment]
This is pretty close to being mergeable now imo, but one last nitpick: I think we should have

> For example, row kinds (e.g. `# Type`, which is the kind of types such as `(name :: String, age :: Int)`)

instead of

> For example, the row kind (i.e. `# Type`, which is the kind of types such as `(name :: String, age :: Int)`)

since I think the latter, by using the article *the* together with *i.e.* (= *that is*), implies that `# Type` is the unique row kind, when `# Type` is just one of many kinds involving `#`.

**Comment by JordanMartinez** [comment]
Nitpicks are fine, especially on docs. I'll fix it.

**Comment by JordanMartinez** [comment]
I believe you asked someone in another PR to add their names to the list of contributors. Will that be required of me as well before this gets merged?

**Comment by hdgarrood** [comment]
Yes please :)

**Comment by JordanMartinez** [comment]
Pushed. Just need to wait on CI then.

**Comment by hdgarrood** [comment]
Sorry, I should have been a little clearer: I think it would be best to replace the *i.e.* with an *e.g.* in addition to pluralising 'row kinds', since I would argue that (even though you've already pluralised 'row kinds') the *i.e.* still implies that `# Type` could be the only row kind.

**Comment by JordanMartinez** [comment]
Oh. No, that's my bad for misreading your feedback. I'll push another commit with that change.

**Comment by hdgarrood** [comment]
Yeah, that is correct. For any kind `k`, there is also a kind `# k`, which is the kind of rows with labels of kind `k`. So for example, you could have

```
( greeting :: "Hello, World", favouriteColor :: "Blue" )
```

which has kind `# Symbol`, or even

```
( foo :: ( bar :: "Baz" ) )
```

which has kind `# (# Symbol)`. You can verify the kinds of these types in the repl with `:k` (although there does seem to be a bug where the parentheses aren't being printed properly in kinds like `# (# Symbol)` at the moment).

**Comment by LiamGoodacre** [comment]
Thanks!

**Pull request merged**
