### PR TITLE
Fix #942

### LINKED ISSUE #942: Imports not added in PSCI
```text
> :i Data.Profunctor.Choice 
> ((+ 1) ||| (+ 2)) $ Data.Either.Left 10
```

gives an error at runtime for `Data.Either.Left` not found. It's probably something to do with the codegen for qualified imports.

### PR DESCRIPTION
**Pull request by paf31**
@garyb How's this? I think this is all the cases we need, since types get handled in `Names`.

### CODE REVIEW

**Comment by garyb** [comment]
Looks good, but I guess there's still something wrong given the tests are failing.

**Comment by paf31** [comment]
Hmm it works in `psc` but not in `psc-make`.

**Comment by paf31** [comment]
No wait, it works in `psc-make` too. Just not in the test suite. How odd.

**Comment by paf31** [comment]
Oh right, yes, only the Main module gets code gen'd during tests. I'll have to move this to `manual/`.

**Comment by garyb** [comment]
Ah yep, :+1: then.

**Pull request merged**
