### PR TITLE
[purs-ide] Fixed case-splitting on local non-exported datatypes

### LINKED ISSUE #2968: Case-split doesn't work for non-exported local declarations
Example:
```
module Lib (one) where

one :: Int
one = 1

data A = B | C

def3 :: A -> Int
def3 a = 1
```

Generates this `externs.json` (formatted for readability):
```
{
    "efVersion": "0.11.5",
    "efModuleName": ["Lib"],
    "efExports": [{
        "ValueRef": {
            "Ident": "one"
        }
    }],
    "efImports": [{
        "eiModule": ["Prim"],
        "eiImportType": {
            "Implicit": []
        },
        "eiImportedAs": null
    }],
    "efFixities": [],
    "efTypeFixities": [],
    "efDeclarations": [{
        "EDValue": {
            "edValueName": {
                "Ident": "one"
            },
            "edValueType": {
                "tag": "TypeConstructor",
                "contents": [
                    ["Prim"], "Int"
                ]
            }
        }
    }],
    "efSourceSpan": {
        "start": [1, 1],
        "name": "/tmp/flycheck23170MKr/Lib.purs",
        "end": [9, 10]
    }
}
```

Whereas adding `A(..)` to the exports list generates this `externs.json`:

```
{
    "efVersion": "0.11.5",
    "efModuleName": ["Lib"],
    "efExports": [{
        "TypeRef": ["A", ["B", "C"]]
    }, {
        "ValueRef": {
            "Ident": "one"
        }
    }],
    "efImports": [{
        "eiModule": ["Prim"],
        "eiImportType": {
            "Implicit": []
        },
        "eiImportedAs": null
    }],
    "efFixities": [],
    "efTypeFixities": [],
    "efDeclarations": [{
        "EDType": {
            "edTypeName": "A",
            "edTypeKind": {
                "tag": "NamedKind",
                "contents": [
                    ["Prim"], "Type"
                ]
            },
            "edTypeDeclarationKind": {
                "DataType": {
                    "args": [],
                    "ctors": [
                        ["B", []],
                        ["C", []]
                    ]
                }
            }
        }
    }, {
        "EDDataConstructor": {
            "edDataCtorName": "B",
            "edDataCtorOrigin": "data",
            "edDataCtorTypeCtor": "A",
            "edDataCtorType": {
                "tag": "TypeConstructor",
                "contents": [
                    ["Lib"], "A"
                ]
            },
            "edDataCtorFields": []
        }
    }, {
        "EDDataConstructor": {
            "edDataCtorName": "C",
            "edDataCtorOrigin": "data",
            "edDataCtorTypeCtor": "A",
            "edDataCtorType": {
                "tag": "TypeConstructor",
                "contents": [
                    ["Lib"], "A"
                ]
            },
            "edDataCtorFields": []
        }
    }, {
        "EDValue": {
            "edValueName": {
                "Ident": "one"
            },
            "edValueType": {
                "tag": "TypeConstructor",
                "contents": [
                    ["Prim"], "Int"
                ]
            }
        }
    }],
    "efSourceSpan": {
        "start": [1, 1],
        "name": "/tmp/flycheck23170zvx/Lib.purs",
        "end": [9, 10]
    }
}
```

This is an issue because it means you can only case split on a locally-defined datatype if you export it, which I think is an unreasonable restriction.

### PR DESCRIPTION
**Pull request by LightAndLight**
Fixes #2968

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Since this is your first commit, would you also add yourself to the `CONTRIBUTORS.md` file? After that this is good to be merged :) Thanks!

**Comment by kRITZCREEK** [comment]
ping @LightAndLight

**Comment by LightAndLight** [comment]
Hey @kRITZCREEK, sorry for the delay. I did this as part of my employment so I'm just trying to figure out licensing. It's a bit slow.

**Comment by kRITZCREEK** [comment]
Oh, I see. Sure take your time.

**Comment by LightAndLight** [comment]
We're good to go.

**Comment by kRITZCREEK** [comment]
License stuff looking good @paf31?

**Comment by paf31** [comment]
👍 Looks good, thanks!

**Pull request merged**
