### PR TITLE
Stop emitting null source spans

### LINKED ISSUE #4034: Sourcemap generated with negative lines/columns
## Description

I think there is some problem with sourcemaps generation, in that it produces lines/columns with negative indexes. I'm not 100% sure because I'm not an expert in the sourcemaps format, but I've got errors from webpack+purs-loader and using the source-map npm package, which makes me believe they are indeed incorrect.

## To Reproduce

I'll give the steps I've used under Windows 10, but there shouldn't be any difference in other environments

- install purescript and spago globally
- create a new directory
- run "spago init"
- run "spago build"
- run "npm init -y"
- install source-map package: "npm install source-map --save"
- save a script in the project root with this content:
```javascript
const s = require("source-map");
const fs = require("fs");
const path = require("path");
const content = fs.readFileSync(path.join(__dirname, "output", "Effect.Console", "index.js.map"), {encoding: "utf-8"});
s.SourceMapConsumer.with(
  JSON.parse(content),
  null,
  (consumer) => {
    console.log("sources:");
    console.log(consumer.sources);

    console.log("mappings:");
    consumer.eachMapping(function (m) {
      console.log(JSON.stringify(m));
    });
  }
)
  .then(() => console.log("all done"))
  .catch(console.error);
```
- run the script

## Expected behavior

It should print a list of mappings between Effect.Console's purescript sources and generated javascript sources. Instead, it fails with an error:

```
sources:
[ '..\\..\\.spago\\console\\v5.0.0\\src\\Effect\\Console.purs' ]
mappings:
Error: Error parsing mappings (code 1): the mappings contained a negative line, column, source index, or name index
    at BasicSourceMapConsumer._parseMappings (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:360:13)
    at BasicSourceMapConsumer._getMappingsPtr (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:315:12)
    at E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:387:57
    at Object.withMappingCallback (E:\Documents\projects\smbug\node_modules\source-map\lib\wasm.js:95:11)
    at BasicSourceMapConsumer.eachMapping (E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:371:16)
    at E:\Documents\projects\smbug\test.js:13:14
    at E:\Documents\projects\smbug\node_modules\source-map\lib\source-map-consumer.js:78:16
```

## Additional context

Spago version: 0.19.1
source-map package version: 0.7.3
psc: psc-0.14.0-20210318

## PureScript version

0.14.0

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes #4034 by building off of #4273 (so credit still goes to @j-nava) but extracting only the 'remove null source span' fix.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by rhendric** [comment]
Can this get a test?

**Comment by JordanMartinez** [comment]
The issue listed `Effect.Console` as an example tat produces invalid source spans. However, I'm not sure what causes it to generate invalid spans. I tried to reduce the file used for `Bug4034.purs` by removing a few functions (e.g. all the `console` ones, but keeping the `time` ones, or vice versa). Unfortunately, I wasn't able to reproduce the failure. Not sure if this is just bad `.test_modules` code affecting things.

**Comment by rhendric** [comment]
No, I think the path was correct and you just need to add it to the `extra-source-files` globs.

**Comment by JordanMartinez** [comment]
Yup, that fixed it. Thanks.

Pushing the commit that fixes this now.

**Comment by JordanMartinez** [comment]
Ah, got regenerate the output file.

**Comment by rhendric** [comment]
https://github.com/purescript/purescript/pull/4273/commits/95baf0747d3a76d75b9b47fe3e255fe4e80a8a2d

**Comment by JordanMartinez** [comment]
Ah, thanks.

CI builds now.

**Review by rhendric — APPROVED** [review]

**Pull request merged**
