### PR TITLE
[psc-ide] removes the deprecated --debug option

### PR DESCRIPTION
**Pull request by kRITZCREEK**
It's subsumed by --log-level=debug

While we're breaking things ;)

### CODE REVIEW

**Comment by paf31** [comment]
👍

**Comment by kRITZCREEK** [comment]
Sorry for leaving broken PRs around I'll get to fixing these asap.

**Comment by kRITZCREEK** [comment]
```
Cannot import type class Eq1 from module Data.Eq
  It either does not exist or the module does not export it.
```

**Comment by garyb** [comment]
Yeah, pretty recent... I added `Eq1` / `Ord1` last night :wink:

**Pull request merged**
