### PR TITLE
Fix #2252, instantiate types in array literals before unification

### LINKED ISSUE #2252: Impredicative type inferred when using polymorphic values but not with constructors
``` purescript
data T a = T

-- inferred as `Array t0`
xs :: _
xs = [T, T, T]

t :: forall a. T a
t = T

-- inferred as `Array (forall a. T a)`
xs' :: _
xs' = [t, t, t]
```

### PR DESCRIPTION
**Pull request by paf31**
cc @garyb 

We just need to make sure we instantiate types before unifying. There are some more places like this, and I'm going to try to fix them in another PR.

### CODE REVIEW

**Comment by paf31** [comment]
@garyb Mind having a look at this one, and then I'll release 0.9.3 today? Thanks.

**Comment by garyb** [comment]
Oh right, yes - I was going to propose a different test, one that matches how I discovered the bug in the first place. I'm about to eat, but will do so when I get back.

**Comment by paf31** [comment]
Cool, thanks.

**Comment by garyb** [comment]
This is what I had in mind:

``` purescript
module Main where

import Control.Monad.Eff.Console (log)

data T a = T

ti :: T Int
ti = T

t :: forall a. T a
t = T

xs = [ti, t, t]

main = log "Done"
```

Now you get a 

```
  Could not match type

    a0

  with type

    Int
```

But `[ti, T, T]` would work, and so should the fix I assume :smile:

**Comment by paf31** [comment]
Much better, thanks. Updated.

**Comment by garyb** [comment]
:+1: :shipit:

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
