### PR TITLE
Expand type synonyms before role checking

### PR DESCRIPTION
**Pull request by kl0tl**
Fix https://github.com/purescript/purescript/issues/3871.

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]

**Comment by hdgarrood** [comment]
It looks like this wasn't completely up to date with master when I merged it, and CI is now failing because a different change in the meantime means that the test output is slightly different. Would you mind regenerating the test output files?

**Comment by kl0tl** [comment]
Sorry about that, I this should be fixed by https://github.com/purescript/purescript/pull/3931.

**Comment by hdgarrood** [comment]
No worries, it was me who merged it! I would have done it myself but I was halfway through something else.

**Comment by kl0tl** [comment]
I also forgot to regenerate the golden tests added in https://github.com/purescript/purescript/pull/3906 but I rebased the pull request on top of master and fixed that too. The other pull requests are unaffected.

**Pull request merged**
