### PR TITLE
Delay errors about scope conflicts until they are unavoidable

### LINKED ISSUE #1497: Conflicting imports
I can run this code in Haskell
```
module Foo where
test = 1

module Bar where
test = 2

module Main where
import Foo
import Bar
main = print "test"
```

But PureScript compiler return an error

```Conflicting imports for test from modules Bar and Foo```

Is this a bug?

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1497

### CODE REVIEW

**Comment by garyb** [comment]
Also rebased now #1684 has been merged, but will probably have to do so again after #1685 :smile:

**Comment by zudov** [comment]
It still gives a warning, right?

**Comment by garyb** [comment]
No, it errors when things are brought into conflict by making an ambiguous reference rather than when two potentially conflicting references just happen to be in scope but are not used. Re-exporting also forces errors about conflicts.

**Comment by zudov** [comment]
Yeah, but probably it would make sense to produce a warning in the cases when conflicting names are imported, and of course error only when there is an actual conflict?

**Comment by garyb** [comment]
Ah. I didn't really think it warranted a warning, as it's unambiguously wrong or not. Warnings are mostly for cases where it looks like there may be a mistake being made. Also, with #1685 we'll be warning about indiscriminate importing anyway, which is the case that this most commonly arises in.

**Comment by paf31** [comment]
:+1: Looks nice, and I agree this is the better way for the errors to work.

**Pull request merged**
