### PR TITLE
Rebindable do notation

### LINKED ISSUE #742: Do notation for semigroups
This is a bit of an odd idea, but I'll put it here for discussion purposes.

We could add an analogue of do notation for semigroups, which gave the nice notational advantages of do notation (with no support for `<-`).

For example, we could build a DOM library which looked like Blaze HTML but without the need to make Markup into a monad:

(Not sure what is the best syntax here...)

```haskell
render $
  html do
    head do
      title $ text "PureScript"
      link' [rel := "stylesheet", href := "style.css"]
    body do
      h1 $ text "PureScript"
      div' [id_ := "intro"] $ text "PureScript is a strongly-typed language which compiles to JavaScript"
```

Originally, I was thinking that we would use a separate keyword, but maybe we can just overload `do`.

Maybe we could even use the fact that every `Monad` is a `Semigroup`, and only require a `Monad` constraint in the case of a `<-`, but that seems to put a strange restriction on the `Monad` type class.

### PR DESCRIPTION
**Pull request by paf31**
@garyb @joneshf @jdegoes Could you please review? I thought this would be pretty neat.

Resolves #742.

### CODE REVIEW

**Comment by paf31** [comment]
This currently breaks `StrMap` (see [here](https://travis-ci.org/purescript/purescript/builds/54497740) - also the CI build doesn't break when core-tests does :-1:), since the `Prelude` is imported qualified, but it can be easily fixed by importing `(>>=)` separately, or by shadowing it.

**Comment by jdegoes** [comment]
Sweet. Would make smoulder, affjax, etc., DSLs faster & more type safe. Looks good to me.

**Comment by paf31** [comment]
This is working as of the last `maps` release. Shall I merge?

**Comment by garyb** [comment]
How did it break `maps`?

**Comment by paf31** [comment]
`maps` used to import `Prelude` qualified, which meant `>>=` wasn't in scope, but now it is since I removed the qualified import in my docs commit.

**Comment by garyb** [comment]
So this will break `do` syntax in any module that currently imports `Prelude` qualified or hides `(>>=)`?

I don't think that's unreasonable, I'd just like to know in advance what it may kick up.

**Comment by paf31** [comment]
Yes, `(>>=)` needs to be in scope, unqualified. You can always fix it by either adding an unqualified import for it, or using `hiding` or just rebinding it in a `where` block.

**Comment by garyb** [comment]
:+1:

**Comment by garyb** [comment]
By :+1: I mean :shipit:

**Comment by paf31** [comment]
:)

**Pull request merged**
