### PR TITLE
Bump stack lts version

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Changing this let me build on macOS Sierra - which I have been unable to do since I upgraded.

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
The two failing travis builds were due to: `The job exceeded the maximum time limit for jobs, and has been terminated.`

**Comment by LiamGoodacre** [comment]
Reapplying the change and trigger a rebuild.

**Comment by LiamGoodacre** [comment]
@paf31 / @garyb: anything we can do to extend the build time limit?

**Comment by garyb** [comment]
Only way of doing that is using `travis_wait` in the script I think?

**Comment by LiamGoodacre** [comment]
No idea if I've added that in the right place lol.  We'll see what happens...

**Comment by andyarvanitis** [comment]
FYI, I've been successfully building with lts-7.8 on both Sierra and El Capitan

**Comment by garyb** [comment]
Maybe try `travis_wait 60`? Looks like it cut off after 20.

**Comment by LiamGoodacre** [comment]
Interestingly: I can `stack build` with lts-7.8, however I can't run `stack test` - it fails on `psc-ide-server` with `malformed mach-o`.  Not only that, if I run `stack test` then try `stack build`, the build then fails...

**Comment by andyarvanitis** [comment]
FYI again, I just saw it misbehave again, for no apparent reason (same malformed mach-o problem)

**Comment by LiamGoodacre** [comment]
Just tried using `lts-7.9`, looks like it would require the same changes as #2432.

**Comment by paf31** [comment]
Note that we're already using 7.9 in the GHC-8.0 Stack YAML file. Is this still relevant?

**Comment by LiamGoodacre** [comment]
The changes here aren't relevant any more, so I'll close.
However I still can't build with either of the stack files currently in master.
I'm now using my own file based on the comments in https://github.com/commercialhaskell/stack/issues/2577
This works for me:
```yaml
resolver: lts-7.14
compiler-check: match-exact
compiler: ghc-8.0.1.20161117
setup-info:
  ghc:
    linux64:
      8.0.1.20161117:
        url: http://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-deb8-linux.tar.xz
        content-length: 112047972
        sha1: 6a6e4c9c53c71cc84b6966a9f61948542fd2f15a
    macosx:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-apple-darwin.tar.xz
        content-length: 113379688
        sha1: 53ed03d986a49ea680c291540ce44ce469514d7c
    windows64:
      8.0.1.20161117:
        url: https://downloads.haskell.org/~ghc/8.0.2-rc1/ghc-8.0.1.20161117-x86_64-unknown-mingw32.tar.xz
        content-length: 155652048
        sha1: 74118dd8fd8b5e4c69b25df1644273fbe13177c7
packages:
- '.'
extra-deps:
- pipes-http-1.0.2
- wai-websockets-3.0.0.9
- websockets-0.9.6.2
```

**Comment by andyarvanitis** [comment]
@LiamGoodacre , yeah, I'm also using the brew + --system-ghc approach, since it's the only one that works consistently for me.

**Pull request closed without merging**
