### PR TITLE
Unicode operators

### LINKED ISSUE #1728: Unicode operators
I don't think we should encourage the use of unicode too much, but I do think it's a neat feature, and useful in some circumstances. I think we should be careful not to use it too much (if at all?) in the core libraries, and instead provide unicode aliases in a separate package.

### PR DESCRIPTION
**Pull request by paf31**
Use at your own risk.

Resolves #1728.

### CODE REVIEW

**Comment by garyb** [comment]
Isn't this too broad a test? Won't things like greek letters be treated as operators now?

**Comment by paf31** [comment]
I don't think so, only things in the symbol unicode category.

**Comment by garyb** [comment]
Oh sorry, I see the predicate for that now :sunglasses:

**Comment by paf31** [comment]
Maybe we want to handle combining characters at some point as well, I'm not sure.

**Comment by garyb** [comment]
:+1:

**Comment by jdegoes** [comment]
> Use at your own risk.

This is scary. :scream: Why?

**Comment by garyb** [comment]
I asked the same question :wink:

He meant it as "don't go crazy making everything unicode"

**Comment by paf31** [comment]
I guess it should have been "use at everyone's risk" :smile:

**Comment by jdegoes** [comment]
> He meant it as "don't go crazy making everything unicode"

Too late. UNICODE ALL THE THINGS. :tada:

**Comment by garyb** [comment]
⍉' *'[⍎'1+0<|z',(∊150⍴⊂'←c+m×m'),'←c←(¯2.1J¯1.3+(((2.6÷b-1)×(¯1+⍳b))∘.+(0J1×(2.6÷b-1)×(¯1+⍳b←51))))']

**Comment by michaelficarra** [comment]
:+1:

**Pull request merged**
