### PR TITLE
Vars should always synthesize monotypes

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb

### CODE REVIEW

**Comment by paf31** [comment]
Hmm, this breaks `liftCoyonedaT`.

**Comment by garyb** [comment]
It'll probably break Halogen and some other stuff too then :(

**Comment by paf31** [comment]
Yeah, I think this means there's something wrong somewhere else, but `Var` should definitely not be synthesizing polymorphic types.

**Comment by garyb** [comment]
What's the `liftCoyonedaT` error?

**Comment by paf31** [comment]
They're all `EscapedSkolem` errors. Maybe this means I should just to implement the new type checker. I'll probably put this on hold until I get a couple of other things finished then.

**Comment by jdegoes** [comment]
> Maybe this means I should just to implement the new type checker.

:+1: :heart_eyes:

**Pull request closed without merging**
