### PR TITLE
Expand synonyms during desugaring

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb 

Probably still a few kinks to work out here.

### CODE REVIEW

**Comment by garyb** [comment]
Yeah, looks like it - various tests are failing. It's nice though, tidies up quite a bit (as expected!).

**Comment by paf31** [comment]
@garyb I made some changes to the tests to get things working. Some tests were just incorrect, but the `Superclasses3.purs` test was interesting. It started passing, because after desugaring, the `b` type argument became unimportant, so it didn't matter that it wasn't bound on the right hand side. I think this is probably ok.

I'll do a bit of performance testing/tuning, but does everything look ok otherwise?

**Comment by paf31** [comment]
Irritatingly, it's slower compiling `coroutines` by about 50%, but I'm not sure why.

**Comment by paf31** [comment]
Ok, those tests are passing on my machine. Something odd is going on..

**Pull request closed without merging**
