### PR TITLE
[psc-ide] use unicode forall and arrows in completions

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Using the unicode syntax for the reported types looks nice and has the added benefit of reducing the popup/message size.

Doing a simple string replacement is not the most robust solution, but I'm fairly certain it's good enough for our purposes. If a typevariable ending in `forall` gets altered it's easy enough to figure out what has happened for the user.

### CODE REVIEW

**Comment by paf31** [comment]
Replacing strings seems a bit sketchy. Why not pass options to `prettyPrintType` instead?

**Comment by kRITZCREEK** [comment]
You're right, done.

**Comment by kRITZCREEK** [comment]
Hmm the windows failure needs a bit of encoding massaging...

**Comment by paf31** [comment]
Thanks! Looks good once the encoding issue is sorted.

**Comment by kRITZCREEK** [comment]
The tests pass again... I had to take explicit control over the psc-ide process for the integration tests. If this looks fine I'll squash and merge.

**Pull request merged**
