### PR TITLE
Enhancements to import linting

### LINKED ISSUE #1740: Import suggestions don't take into account imports-via-re-export
e.g. if you `import X`, and `import Y (foo)`, and `foo` is actually a re-export from `X`, the import suggestion list for `X` will contain `foo` again.

### LINKED ISSUE #1743: Warn when importing-qualified into a virtual module without an explicit list
For similar reasons to #1742 - this will ensure name collisions can't be introduced by changes in upstream modules.

### LINKED ISSUE #1804: Warn on unused qualified import
Right now if you don't use a qualified import, no warnings are generated. It should give a redundant import warning.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1804, resolves #1743, resolves #1740

### CODE REVIEW

**Comment by garyb** [comment]
Oh, also, I realised we should warn on use of `import hiding`, as this is another form of implicit importing, so it does that too now.

**Comment by nwolverson** [comment]
I was just writing a comment on #1804, I don't see immediately if it's still valid as the code has changed drastically so here it is as-was:

Just noticed that the `ImplicitImport` warning and by extension my enhanced warning in #1777 (which I should have made as a separate change) handles qualification wrongly too - if I import the same module qualified and unqualified the error lists even things that are used only qualified. `getClassName`/`getIdentName`/`getTypeName` should insist on no qualification (or rather the qualifier being `qualifierName` if it's pulled up as I did.)

**Comment by garyb** [comment]
I think that's fixed now, if I understand the problem. Could you perhaps whip up an example snippet for something that would cause this problem to be apparent and I'll double check?

**Comment by garyb** [comment]
Oh, I think I see, right, I'll look at that :wink:

This?

``` purescript
module Main where

import Prelude (Unit)
import Control.Monad.Eff (Eff())
import Control.Monad.Eff.Console as X
import Control.Monad.Eff.Console

main :: forall e. Eff (console :: X.CONSOLE | e) Unit
main = do
  log "Hello sailor!"

```

```
  Module Control.Monad.Eff.Console has unspecified imports, consider using the explicit form:

    import Control.Monad.Eff.Console (CONSOLE, log)
```

(only need to include `log` there)

**Comment by paf31** [comment]
LGTM :+1: 

On a related note, does it make sense to warn on qualified uses of a name in a module without that module being explicitly imported (since we might deprecate that to support parsing module headers for incremental compilation)?

**Comment by nwolverson** [comment]
Exactly. (Where the intention is to make explicit the unqualified one later)

**Comment by garyb** [comment]
@nwolverson Fixed :ok_hand: - just needed to thread through the `qualifierName` into `getClassName` etc.

I'll merge once Travis okays it again.

**Comment by nwolverson** [comment]
Yep that's basically what I meant, had a quick play and don't see any issues.

**Pull request merged**
