### PR TITLE
Bump aeson upper bound

### PR DESCRIPTION
**Pull request by phadej**
https://github.com/fpco/stackage/issues/572

### CODE REVIEW

**Comment by garyb** [comment]
#1366? :)

**Comment by phadej** [comment]
Ah, I just get notice from stackage, didn't bothered to check. Feel free to choose :)

**Comment by garyb** [comment]
I'll merge the other one as the test have already passed. Thanks anyway! :wink:

**Comment by phadej** [comment]
Go ahead.

**Pull request closed without merging**
