### PR TITLE
fixed #807

### LINKED ISSUE #807: negate (-42) compiles to invalid JavaScript
Input:

```purescript
x = negate (-42)
```

Actual output:

```javascript
var x = --42;
```

Desired output:

```javascript
var x = -(-42);
// or...
var x = - -42;
```

### PR DESCRIPTION
**Pull request by philopon**
Hi!

I fixed #807.

### CODE REVIEW

**Comment by michaelficarra** [comment]
Well this should fix it, but now all negations will have a space in them.

**Comment by philopon** [comment]
Sorry, I underestimated it.

I'll fix it soon!

**Comment by paf31** [comment]
This might even be an issue in my `pattern-arrows` library. I'll have a look as well.

**Comment by michaelficarra** [comment]
I think the way to solve this is much like the way you've done now, except also disallow negative numbers in `JSNumericLiteral` and require those to be unary negation operations (which is how JavaScript actually works anyway). This will have the added benefit of handling `negate (negate -1)` properly, which this current patch does not do.

**Comment by philopon** [comment]
I agree. so I rewrote. but I think It can fix easily even if JSNumericLiteral has sign.
Moreover, I think that independent negate can optimize easily. `negate (negate a)` to `a`.

Maybe, `removeSignedLiterals` should be renamed.

**Comment by paf31** [comment]
Looks good to me. @michaelficarra ?

**Comment by michaelficarra** [comment]
Very nice. :+1:

**Pull request merged**
