### PR TITLE
Tidy up MakeActions API, close #1264

### LINKED ISSUE #1264: Review MakeActions API
It's not clear to me how it works. Maybe we can revisit it when we implement parallel builds?

### PR DESCRIPTION
**Pull request by paf31**
@garyb Does this look ok?

I want to look at parallel builds in 0.8 for performance reasons and tidying this up a bit first seemed useful.

### CODE REVIEW

**Comment by garyb** [comment]
I guess the problem is now the other backends can't use `MakeActions`, that's a big part of why I did things the way they were previously - to keep `make` generally useful, not just for `psc`.

**Comment by paf31** [comment]
Oh, I thought we were just trying to abstract away `IO`. That makes sense.

**Comment by paf31** [comment]
I'll keep the branch around while I experiment with parallel builds though.

**Comment by garyb** [comment]
I'm sure it can probably still be improved, but yeah, sorry I should have mentioned that was the motivation behind the previous version.

**Pull request closed without merging**
