### PR TITLE
Fix "purs ide server" crash on macOS by providing connection hints

### LINKED ISSUE #3594: Running `purs ide server` on macOS crashes
```bash
purs ide server
purs: Network.Socket.listen: unsupported operation (Operation not supported on socket)
```

This happens since `0.12.4`.

### PR DESCRIPTION
**Pull request by f-f**
This should fix #3594 

The fix solves the issue on my macOS, @i-am-the-slime could you also try it out?

### CODE REVIEW

**Comment by i-am-the-slime** [comment]
I can try. I'm doing `make build` right now. It'll probably take a few hours, right?

**Comment by f-f** [comment]
@i-am-the-slime you might want to do `make install` instead (that will install `purs` system-wide). And yeah, it will take at least ~30mins on a recent processor to compile everything if you didn't use stack before

**Comment by i-am-the-slime** [comment]
It would be so nice for this beautiful compiler to be self-hosted.

**Comment by i-am-the-slime** [comment]
Appveyor says this: Timed out while installing dependencies. :)

**Comment by i-am-the-slime** [comment]
As Apache would say: 
# It works!
Thank you very much @f-f .

**Comment by kRITZCREEK** [comment]
Lovely, this looks good to me. If we're allright with bumping network to 3.x over our current snapshot I'm happy to merge this.

**Comment by f-f** [comment]
@i-am-the-slime you're welcome 🙂 

@kRITZCREEK could we cut a small release with this?

**Comment by hdgarrood** [comment]
We need to verify that this still works on Windows before merging (unless I'm missing something and someone has already done this). If not I can get appveyor running again soon (perhaps this weekend).

I agree that making a small bugfix release for this would be good. I think we should also include a fix for #3591.

**Comment by hdgarrood** [comment]
I've made a milestone: https://github.com/purescript/purescript/milestone/27

**Comment by garyb** [comment]
I'll give it a try when I get a minute later today.

**Comment by garyb** [comment]
Hmm, well it seems like it won't build on Windows with this change, so I don't really know whether it works. It blows up at the end with this:

```
    ghc.EXE: unable to load package `network-3.0.0.1'
    ghc.EXE:  | D:\Home\GitHub\purescript\.stack-work\install\f33caf5a\lib\x86_64-windows-ghc-8.6.4\network-3.0.0.1-4CoErOi6AngG4EwBDdM0JI\HSnetwork-3.0.0.1-4CoErOi6AngG4EwBDdM0JI.o: unknown symbol `if_nametoindex'
```

Maybe I'm doing it wrong somehow?

**Comment by f-f** [comment]
@garyb it looks like that was fixed in `network..3.0.1.1` (see [here](https://github.com/haskell/network/pull/391)), pushed a commit upgrading to that.

Unfortunately `network-bsd` has tight bounds, so I enabled "allow-newer" in the stack file (it should be fine to keep it until the bounds are fixed)

**Comment by garyb** [comment]
Ah cool, trying again then 🙂

**Comment by garyb** [comment]
All seems good 👍

**Comment by hdgarrood** [comment]
Come to think of it is the network-bsd dependency necessary? It looks like network-bsd is only being used to get a protocol number, but the example in the network library’s docs doesn’t bother setting the protocol number on the hints: http://hackage.haskell.org/package/network-3.0.1.1/docs/Network-Socket.html

**Comment by f-f** [comment]
@hdgarrood good catch!
I included it because the old implementation did (i.e. before the upgrade that introduced the bug), but things seem to work also without it.

**Comment by f-f** [comment]
Thanks 🙂

**Comment by purcell** [comment]
Awesome fix, thanks! Can https://github.com/purescript-contrib/node-purescript be bumped too?

**Pull request merged**
