### PR TITLE
Fix 1166, Use bind instead of >>= in do desugaring

### LINKED ISSUE #1166: Use bind instead of >>= in do desugaring
No reason to use `>>=` any more, and this should give slightly nicer errors.

### PR DESCRIPTION
**Pull request by paf31**
Fix #1166
@garyb Could you please review this? I think it should lead to slightly nicer errors and generated code.

### CODE REVIEW

**Comment by paf31** [comment]
Hmm, I'm not sure. Do you think so?

**Comment by garyb** [comment]
Just as I figure the optimization is more "magic `Eff` monad" than "magic `do`", but I don't feel strongly about it.

**Comment by mjgpy3** [comment]
How does using `bind` improve errors and generated code?

**Comment by paf31** [comment]
Well, `bind` is a bit nicer to look at than `>>=`, and "bind was not implemented" reads better than ">>= was not implemented" IMO.

**Comment by mjgpy3** [comment]
Gotcha! Thanks for the answer :) I was unsure if it was more complicated than that

**Comment by paf31** [comment]
@garyb I'd rather change `>>=` to `bind` separately later on. Does this look ok otherwise?

**Comment by garyb** [comment]
That makes sense.

Are there any failing tests that need updating too? We should probably do a check to see if they're all failing in the way they're supposed to actually, after all the recent changes.

Looks good to me though. :+1:

**Comment by paf31** [comment]
Yeah, it would be good to verify that things fail in the right way, which should be easier now that we have an actual error type to match on. I'll write something up for that.

**Pull request merged**
