### PR TITLE
Revert "Require single-method instance declarations to be indented"

### PR DESCRIPTION
**Pull request by paf31**
Reverts purescript/purescript#2965

### CODE REVIEW

**Comment by paf31** [comment]
Tested locally

**Comment by hdgarrood** [comment]
Did you mean to revert all of these?

**Comment by paf31** [comment]
It's just how GitHub's UI does the revert unfortunately. If you see, they're all empty commits actually, and after squashing, it's just one with the commit I need removed.

**Comment by hdgarrood** [comment]
Ahh, I see. Thanks for clarifying!

**Pull request merged**
