### PR TITLE
Remove deprecated class import/export syntax

### PR DESCRIPTION
**Pull request by LiamGoodacre**
For https://github.com/purescript/purescript/issues/2012

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
The failing tests appear to be using a version of the prelude which doesn't use the updated class import/export syntax.

**Comment by garyb** [comment]
#1963 should address that. Hopefully we're going to release an 0.8.5 before 0.9 though, so there's a whole bunch of PRs that are waiting for that first.

**Comment by paf31** [comment]
@LiamGoodacre Could you please reopen this as a PR on the 0.9 branch?

**Comment by LiamGoodacre** [comment]
Will do!

**Pull request closed without merging**
