### PR TITLE
Move -Werror to travis config

### PR DESCRIPTION
**Pull request by erdeszt**
As suggested in #1411 moving the -Werror to the travis config from the cabal file.
Not sure though that this is the right way of doing it, I've never used travis before.

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Thanks. Let's see what Travis does this time.

**Comment by garyb** [comment]
This'll conflict with my changes I think, as I removed `-Werror` also. I guess what we really want is to only run `-Werror` on the newer GHCs though, right? As otherwise this will suffer from the same problem I had.

**Comment by erdeszt** [comment]
@garyb I've fixed the only non 7.10 related warning in #1411 so there should be no warnings on earlier versions either(and the travis build for that branch was green for the old versions too, let's see how this one turns out).

**Comment by hdgarrood** [comment]
Why only run `-Werror` on the newer GHCs? I think I'd rather have it so that there are no warnings on any of the GHCs that we test with.

Also, sorry I didn't think to mention this earlier, but perhaps [base-compat](http://hackage.haskell.org/package/base-compat) might be a bit nicer than CPP all over the place? I think it would also make it easier to deal with any changes in future `base` releases, if any situations similar to the Foldable/Traversable Proposal arise in the future.

**Comment by paf31** [comment]
Both of those sound like good ideas to me.

**Comment by garyb** [comment]
> Why only run `-Werror` on the newer GHCs? I think I'd rather have it so that there are no warnings on any of the GHCs that we test with.

I've already discovered how painful it is to try and track down warnings by waiting 5-10 minutes for Travis to fail so an import can be tweaked... several times :) It wouldn't be so bad if you got all the errors at once.

**Comment by paf31** [comment]
Wouldn't `base-compat` help with that though?

**Comment by garyb** [comment]
Looks like it, yep!

**Comment by paf31** [comment]
This needs to be merged with `master` now, sorry.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
