### PR TITLE
Tune GHC parameters

### PR DESCRIPTION
**Pull request by phadej**
`-j2` actually decreases parallellism, which on shared travis containers cause bad performance. See https://ghc.haskell.org/trac/ghc/ticket/9221

### CODE REVIEW

**Comment by paf31** [comment]
I'm not sure I follow about `-j2`. Are you saying you are decreasing parallelism on purpose, to increase the speed of Travis builds? 

Could you please explain the `-A32m` option too?

Maybe these could benefit from a code comment as well, to explain both of these things.

**Comment by paf31** [comment]
Also, thanks for working on this :smile:

**Comment by phadej** [comment]
Added comments. Build times seems to be largely improved (down to ~7 min, from over 20 for >=GHC7.8 builds).

**Comment by paf31** [comment]
This does look much better, thanks. :+1:

**Comment by hdgarrood** [comment]
:100: amazing!

**Pull request merged**
