### PR TITLE
Fixes #2064

### LINKED ISSUE #2064: Performance problem with psc-ide
MacMini 2012 i7 16GB 1.2TB Fusion drive, OS X 10.11.4 El Capitan.

MacVim takes 10-20 seconds when closing/quitting the purescript source file with psc-ide integration installed, even if no changes were introduced. 
When this happens one can notice ReportCrash process hanging for a few minutes with the following in the system.log:

```
Apr 29 03:39:30 kika-mini com.apple.xpc.launchd[1] (com.apple.ReportCrash.Root[8423]): Endpoint has been activated through legacy launch(3) APIs. Please switch to XPC or bootstrap_check_in(): com.apple.ReportCrash.DirectoryService
Apr 29 03:39:31 kika-mini ReportCrash[8423]: Invoking spindump for pid=8385 wakeups_rate=185 duration=244 because of excessive wakeups
```
 
PID 8385 is the pid of the psc-ide-server process.
Diagnostic report from ReportCrash: https://gist.github.com/kika/b358b53a0411e79d45ead38870052c34

### PR DESCRIPTION
**Pull request by kika**
The unnecessary forward (client) and reverse (server) name resolution
was impaired on OS X when IPv6 entries for `localhost` were missing in
`/etc/hosts`
The proposed patch removes this name resolution and makes psc-ide
operation independent from name resolution proper configuration.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks for this. Could you please update `CONTRIBUTORS.md`?

**Comment by kika** [comment]
@paf31 Done

**Comment by hdgarrood** [comment]
:+1: I have a feeling that this might fix the failures on travis on osx we're seeing.

**Comment by garyb** [comment]
Maybe it will, I'll give it a try. Thanks for figuring this out yourself @kika!

**Comment by kRITZCREEK** [comment]
Thanks! :tada:

**Pull request merged**
