### PR TITLE
Create Gitpod configuration

### LINKED ISSUE #4211: Proposal: Gitpod Configuration
## Summary

[Gitpod](https://www.gitpod.io/) offers cloud development environments, and they also provide a template for developing Haskell projects, which can be seen [here](https://github.com/gitpod-io/template-haskell). Introducing a `.gitpod.yml` file for configuring Haskell tooling e.g. `ghcup` + `cabal/stack` + `hls` would allow for faster bootstrapping for Gitpod users.

## Motivation

Gitpod is a pretty neat platform for developing heftier applications on underpowered machines; Haskell, especially, tends to be one of the worse offenders. I don't think this necessarily adds a maintenance burden as it'd really be just an installation script for Haskell tooling; `stack` already installs the appropriate compiler version too, and likewise, I don't think the GHC version would be updated all that much.

### PR DESCRIPTION
**Pull request by sjpgarcia**
Closes #4211. This introduces two files to allow for faster bootstrapping of Gitpod environments: `.gitpod.yml` and `.gitpod.Dockerfile`. These install the Haskell tools needed for development under Gitpod's VS Code environment. You can try it out here through this link: https://gitpod.io/#https://github.com/vtrl/purescript/tree/gitpod.

Gitpod's environments are designed to be ephemeral, but I did my best to make sure that the `.stack` and `.cabal` directories are persisted as much as possible across workspace shutdowns.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
* Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
* Updated or added relevant documentation
* Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by rhendric** [comment]
This looks similar to #3977, where I think we established the precedent that if there isn't a maintainer who uses a dev tool/environment, we shouldn't include configuration for that thing in the PureScript repo.

Do we have anyone willing to speak for Gitpod?

**Comment by garyb** [comment]
> if there isn't a maintainer who uses a dev tool/environment, we shouldn't include configuration for that thing in the PureScript repo.

Yeah, I'd agree with that again since it won't be kept up to date by us.

**Comment by sjpgarcia** [comment]
Ah, that's understandable. This pull request and the associated issue can be closed then.

**Comment by rhendric** [comment]
Closing then, though Gitpod sounds neat, and this PR might be useful in the future if a maintainer decides to take it on.

**Pull request closed without merging**
