### PR TITLE
Unify matching constraints

### LINKED ISSUE #950: Eta expansion is required for higher rank types with constraints
This might already be known:

``` purescript
data Sequence t
  = Sequence (forall m a. (Monad m) => t (m a) -> m (t a))

-- This is fine
mkSequence :: forall t. (forall m a. (Monad m) => t (m a) -> m (t a)) -> Sequence t
mkSequence f = Sequence f

-- This is not:
mkSequence' :: forall t. (forall m a. (Monad m) => t (m a) -> m (t a)) -> Sequence t
mkSequence' = Sequence
```

```
Error in module Main:
Error in value declaration mkSequence':
Error checking that type
  forall t. (forall m a. (Prelude.Monad m) => t (m a) -> m (t a)) -> Main.Sequence t
subsumes type
  (forall m a. (Prelude.Monad m) => t1498 (m a) -> m (t1498 a)) -> Main.Sequence t1498
Error checking that type
  (forall m a. (Prelude.Monad m) => u1502 (m a) -> m (u1502 a)) -> Main.Sequence u1502
subsumes type
  (forall m a. (Prelude.Monad m) => t1498 (m a) -> m (t1498 a)) -> Main.Sequence t1498
Error checking that type
  forall m a. (Prelude.Monad m) => t1498 (m a) -> m (t1498 a)
subsumes type
  forall m a. (Prelude.Monad m) => u1502 (m a) -> m (u1502 a)
Error checking that type
  forall m. (Prelude.Monad m) => t1498 (m u1503) -> m (t1498 u1503)
subsumes type
  forall m a. (Prelude.Monad m) => u1502 (m a) -> m (u1502 a)
Error checking that type
  (Prelude.Monad u1504) => t1498 (u1504 u1503) -> u1504 (t1498 u1503)
subsumes type
  forall m a. (Prelude.Monad m) => u1502 (m a) -> m (u1502 a)
Error checking that type
  (Prelude.Monad u1504) => t1498 (u1504 u1503) -> u1504 (t1498 u1503)
subsumes type
  forall m. (Prelude.Monad m) => u1502 (m a1505) -> m (u1502 a1505)
Error checking that type
  (Prelude.Monad u1504) => t1498 (u1504 u1503) -> u1504 (t1498 u1503)
subsumes type
  (Prelude.Monad m1506) => u1502 (m1506 a1505) -> m1506 (u1502 a1505)
Error at examples\passing\SequenceDesugared.purs line 12, column 1 - line 12, column 15:
  Cannot unify constrained type
    (Prelude.Monad u1504) => t1498 (u1504 u1503) -> u1504 (t1498 u1503)
  with type
    (Prelude.Monad m1506) => u1502 (m1506 a1505) -> m1506 (u1502 a1505)
```

### LINKED ISSUE #3588: Confusing interaction with rank-n types and constraints
Originally reported by @munizart in Slack. I think this is a bug.
```purescript
module Main where

data Tuple a b = Tuple a b

class C a

type SomeC = forall x. C x => x

-- This is fine
id1 :: SomeC -> SomeC
id1 x = x

-- This is not
id2 :: forall a. Tuple a SomeC -> Tuple a SomeC
id2 x = x

-- Neither is this
id3 :: Array SomeC -> Array SomeC
id3 x = x
```

The function `id2` produces an error
```
[1/1 ConstrainedTypeUnified] src/Main.purs:15:9

  15  id2 x = x
              
  
  Could not match constrained type
  
    C x1 => x1
  
  with type
  
    C x1 => x1
  
  while trying to match type C x1 => x1
    with type C x1 => x1
  while checking that expression x
    has type Tuple a0 (forall x. C x => x)
  in value declaration id2
  
  where a0 is a rigid type variable
          bound at (line 0, column 0 - line 0, column 0)
        x1 is a rigid type variable
          bound at (line 7, column 21 - line 7, column 22)
```

and `id3` also produces a very similar error.

### PR DESCRIPTION
**Pull request by garyb**
This might well be a terrible idea, I feel like if it was this easy then it would already have been done. In https://github.com/purescript/purescript/issues/950#issuecomment-139434920 Phil said:
> We could add a case to the unify function for when two instance heads are equal, but I'm not confident it would be a good idea.

but he doesn't mention why it might not be good. I assume what he meant there is what I've done here too.

It seems to work great in fixing cases where we get the error currently; it resolves #950, it resolves #3588, and it also resolves the case I mentioned in #3558 where the obvious implementation of `unLBox` fails. 

I don't know how to check if it starts letting things in it shouldn't - I can't think of a case that would occur in.

### CODE REVIEW

**Comment by natefaubion** [comment]
> This might well be a terrible idea, I feel like if it was this easy then it would already have been done.

Maybe at the time it was more of an issue because of context tupling (`(Foo a, Bar b) => ...`)? I'm not sure when we removed that. But to me, with an enforced ordering, I don't see how it's any different than unifying an explicit argument.

**Comment by hdgarrood** [comment]
It seems reasonable to me but I don't think my input counts for very much here. I would quite like to get Phil's input on this at least. @paf31 what are your thoughts? Do you remember what you had in mind when you wrote https://github.com/purescript/purescript/issues/950#issuecomment-139434920 ?

**Comment by paf31** [comment]
I don't remember, but I think my objection to this was more that it was an incomplete solution to a bigger problem. As a simple example, if there are two constraints in a different order, this approach won't work, we'd need to elaborate to swap the dictionaries. So it seems like it's a trade-off between the better usability vs. a small risk of adding more confusion in certain cases (why does this case work, but this very similar case doesn't?) - but the current situation is already confusing, so it's probably no worse.

**Comment by garyb** [comment]
Cool! Sounds like this is ok then.

Anecdotally I think I've only ever seen this in situations where the constraints match.

**Pull request merged**
