### PR TITLE
Don't lint modules if they won't be rebuilt

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb @hdgarrood Slightly simpler solution than in my other PR.

### CODE REVIEW

**Comment by paf31** [comment]
Looks like builds are failing because of a `core-tests` version mixup. @garyb Do we need to bump some core library dependencies or is this an issue with the `bower.json` file?

**Comment by garyb** [comment]
We need to bump some core libraries for `strings` I think... _maybe_ something else too. I'll see what I can do.

**Comment by garyb** [comment]
Fix looks nice though.

**Comment by garyb** [comment]
Actually QC was the culprit, I was holding off on a release until we fixed the stack safety issues but I think that's still being looked at. Restarted Travis checks now so hopefully will be green once they're done.

**Pull request closed without merging**
