### PR TITLE
Allow aeson 1.1

### PR DESCRIPTION
**Pull request by felixonmars**
It seems to work fine here.

### CODE REVIEW

**Comment by hdgarrood** [comment]
We've been bitten in the past by making changes like this which seemed to work without really testing properly. We really need to check the aeson release notes before doing this, e.g. to make sure that no instances we are using have been changed.

**Comment by paf31** [comment]
Now might be a good time to add those JSON unit tests we discussed recently.

**Comment by hdgarrood** [comment]
If we were using derived instances and checking a hash based on the data type definition, and Aeson's TH instance derivation changed, a bug could still slip through that way though surely?

**Comment by kRITZCREEK** [comment]
After reading through the aeson's changelog I didn't see anything breaking for us. Every new addition defaults to backwards compatible behaviour.

**Comment by paf31** [comment]
Thanks @kRITZCREEK

**Pull request merged**
