### PR TITLE
Allow rows in instance contexts

### LINKED ISSUE #642: Allow rows in instance contexts
Currently we disallow rows in constraints, but really all we need to do is restrict instance heads, not instance contexts. We are currently disallowing seemingly valid things like 

```
foo :: (MonadState { field :: Type } m) => m Type
```

As long as every instance doesn't mention any non-empty rows, we should be fine.

### PR DESCRIPTION
**Pull request by paf31**
@apsk @garyb Could you please review?

@apsk I worked from your pull request, but I needed to make some changes to support some additional use cases, and also added a couple of comments to explain what's going on and what needs to be improved.

Resolves #642.

### CODE REVIEW

**Comment by garyb** [comment]
Awesome! :+1: :+1: :+1: 

It all looks great to me too, but I probably don't have a deep enough understanding of exactly what's going on to see any potential problems here anyway.

**Comment by paf31** [comment]
This will probably need more testing, but `test-everything` works for me. I'll make a release soon, and we can see if there are any issues.

**Comment by pseudonom** [comment]
This is separate from allowing anonymous records? Like

```purescript
instance showFoo :: Show ({foo :: String}) where
  show f = "f"
```
?

**Comment by garyb** [comment]
Yeah, that's what @paf31 meant in #863 when he mentioned disallowing rows in instance heads.

Closed rows like you have in that example would perhaps be workable, but maybe even that is problematic. @paf31?

**Pull request merged**
