### PR TITLE
Fix `UnusedTypeVar` missing position info

### PR DESCRIPTION
**Pull request by garyb**
For #3208

### CODE REVIEW

**Comment by hdgarrood** [comment]
Ah, we've hit that stack bug on AppVeyor; we need to tell it to use Stack 1.6.x.

**Comment by hdgarrood** [comment]
Oh sorry, I forgot that that version has already been bumped in master via #3209. I suppose this build must have started before that PR was merged. Rebasing should sort this out, and it might be worth removing that extra commit as well, in case it causes a conflict.

**Comment by garyb** [comment]
Ah ok!

**Comment by kRITZCREEK** [comment]
OSX queue is stuck forever, but I built and ran the tests locally and they passed, so I'll just get this in.

**Pull request merged**
