### PR TITLE
Use utf8 when writing to stdout and stderr

### LINKED ISSUE #1992: hPutChar error when printing warnings
```
Warning 2057 of 2076:

  in module SlamData.Notebook.Cell.Common.EvalQuery
  at D:\Home\GitHub\slamdata\src\SlamData\Notebook\Cell\Common\EvalQuery.purs line 159, column 1 - line 162, column 1

    An operator section uses legacy syntax. Operator sections are now written using anonymous function syntax:

      (_ psc: <stderr>: hPutChar: invalid argument (invalid character)
```

The offending code:

``` purescript
instance bindCellEvalT ∷ (Monad m) ⇒ Bind (CellEvalT m) where
  bind (CellEvalT m) = (⋙ getCellEvalT) ⋙ bind m ⋙ CellEvalT
```

We're not writing unicode output I guess?

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1992

### CODE REVIEW

**Comment by garyb** [comment]
Actually, "resolves" might be a bit strong, as now this happens:

```
    An operator section uses legacy syntax. Operator sections are now written using anonymous function syntax:

      (_ ÔïÖ f)

    Support for legacy operator sections will be removed in PureScript 0.9.
```

(on Windows at least)

Significantly better than the alternative crash out though:

```
    An operator section uses legacy syntax. Operator sections are now written using anonymous function syntax:

      (_ psc: <stderr>: hPutChar: invalid argument (invalid character)
```

**Comment by kRITZCREEK** [comment]
I guess this would go away if we used `Text` through the compiler?

**Comment by garyb** [comment]
I don't know, hopefully. We'd still need to set the encoding though, as writing unicode chars as `latin1` will always result in the `hPutChar: invalid argument (invalid character)` crash.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
