### PR TITLE
Pass the length of arguments in as a function argument.

### PR DESCRIPTION
**Pull request by nicodelpiano**
This solves the issue #1380.

Now the error (`head empty list`) doesn't appear:

```purescript
module Main where

import Prelude
import Data.Generic

data Void
derive instance genericVoid :: Generic Void
```

and this example works fine.

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Thanks!

**Comment by nicodelpiano** [comment]
:smile:

**Comment by paf31** [comment]
Might as well put the new policy into effect now :smile: 

Could you please add your licensing terms here? https://github.com/purescript/purescript/issues/1394

**Comment by nicodelpiano** [comment]
Done :smile: :+1:

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
