### PR TITLE
Upgrade to GHC 9.2.7

### PR DESCRIPTION
**Pull request by Unisay**
**Description of the change**

Updates GHC to 9.2.7 and the Stackage snapshot to LTS-20.13.

The changes are very similar to the https://github.com/purescript/purescript/pull/4433.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [ ] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by rhendric** [comment]
This PR contains several unrelated zero-impact formatting changes; please remove them.

More generally, why are we following point releases of GHC like this? I can understand doing major version bumps to keep up with the times, and the occasional minor bump to get an important feature or compatibility with an LTS snapshot or something, but I don't want to do this every month if we don't have a reason to.

**Comment by Unisay** [comment]
> This PR contains several unrelated zero-impact formatting changes; please remove them.

Sure. I have removed all unintentional formatting changes already (`vscode` did them automatically without asking me, bad boy). 

> More generally, why are we following point releases of GHC like this? 

Idk about any existing conventions. The [previous bump](https://github.com/purescript/purescript/pull/4433) wasn't a major one and it let me to believe that this is the way.

> I can understand doing major version bumps to keep up with the times, and the occasional minor bump to get an important feature or compatibility with an LTS snapshot or something, but I don't want to do this every month if we don't have a reason to.

I'll respect your time and work, and will follow any guideline you decide to come up with. I'd also appreciate if a decision criteria are not subjective (e.g. an "importance of a certain feature or compatibility" is could be relative).

Please close this PR if you feel like its not worth your time reviewing and answering it.

Thank you!

**Comment by wclr** [comment]
Btw, GHC 9.2.7 is not on the [list of supported versions by HLS](https://haskell-language-server.readthedocs.io/en/latest/support/ghc-version-support.html).

**Comment by JordanMartinez** [comment]
Closing as this doesn't seem like we'll be merging.

**Pull request closed without merging**
