### PR TITLE
Update ErrorsWarnings.hs

### PR DESCRIPTION
**Pull request by flip111**
This error is not informative because it talks about a "format". And then you go google and don't find the right things quickly. So better to link to an actual list of license then it becomes very clear what to fill in.

### CODE REVIEW

**Comment by flip111** [comment]
This is for https://github.com/purescript/purescript/issues/3833

**Comment by hdgarrood** [comment]
Thanks for this! Linking to spdx.org/licenses is definitely a good idea. The one issue I have with this is that the current message is trying to get across the fact that you can use a license _expression_, not just a license identifier, so that if you want to express that your package is dual-licensed you can do that, and I think the proposed new error text loses that. Perhaps there's another resource we can link to which explains what license expressions are?

**Comment by hdgarrood** [comment]
I would prefer to keep the existing list of examples, as that way some of the most common cases are covered without the user having to follow any links. Also I think it would be best to use the same explainer text for both license-related errors (no license, and invalid license). How about this?

No license:
> No license is specified in package manifest. Please add a "license" property with a SPDX license expression. For example, any of the following would be acceptable:
>
> * "MIT"                                                                     
> * "Apache-2.0"                                                              
> * "BSD-2-Clause"                                                            
> * "GPL-2.0-or-later"                                                                
> * "(GPL-3.0-only OR MIT)"                                                        
>
> See https://spdx.org/licenses/ for a full list of licenses. For more information on SPDX license expressions, see https://spdx.org/ids-how
>                                                                                
> Note that distributing code without a license means that nobody will (legally) be able to use it. 
>
> It is also recommended to add a LICENSE file to the repository, including your name and the current year, although this is not necessary.  

Invalid license:
> The license specified in package manifest is not a valid SPDX license expression. Please update the "license" property so that it is a valid SPDX license expression. For example, any of the following would be acceptable:
>
> * "MIT"                                                                     
> * "Apache-2.0"                                                              
> * "BSD-2-Clause"                                                            
> * "GPL-2.0-or-later"                                                                
> * "(GPL-3.0-only OR MIT)"                                                        
>
> See https://spdx.org/licenses/ for a full list of licenses. For more information on SPDX license expressions, see https://spdx.org/ids-how

I noticed the existing example lists are wrong because apparently FSF licenses now use `-or-later` or `-only` suffixes rather than the `+` to indicate whether later versions of the license also apply, so I've updated those too.

**Comment by hdgarrood** [comment]
Could you update CONTRIBUTORS.md too please?

**Comment by flip111** [comment]
> How about this?

Sorry this is not in line with the short message i had in mind.

**Pull request closed without merging**
