### PR TITLE
Numeric literals with leading zeros #1125

### PR DESCRIPTION
**Pull request by kRITZCREEK**
This feels a little hacky. If you have suggestions for a nicer way I'd love to improve my Parsec-Fu. 
I'll add a failing test aswell.

### CODE REVIEW

**Comment by garyb** [comment]
Seems reasonable to me, might want a better message than "intended" though? :wink:

**Comment by kRITZCREEK** [comment]
That error message never gets shown. I only need the parser to fail without consuming input so that choice tries the next one.

**Comment by garyb** [comment]
Ah, interesting. I assumed that at first, but wanted to check - it had no description in the documentation and reading the implementation suggests it is used, I guess not for the resulting error message. Would `parserZero/mzero/empty` work instead?

**Comment by kRITZCREEK** [comment]
Of course you're right! That's what I'm looking for.

**Comment by kRITZCREEK** [comment]
A parse failure does now error as follows:

``` 
> 02
(line 1, column 3):
unexpected '2'
expecting no leading zero in number literal
```

I think that should do it.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
