### PR TITLE
[psc-ide] create the output folder if it's missing

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Adresses #2030

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by kRITZCREEK** [comment]
hmm I think I'm seeing a tiny bug.. I'll report when it's fixed

**Comment by kRITZCREEK** [comment]
Allright that should be it :)

**Comment by paf31** [comment]
👍

**Comment by kRITZCREEK** [comment]
Rebased

**Pull request merged**
