### PR TITLE
Add HasCallStack to internalError

### PR DESCRIPTION
**Pull request by alexbiehl**
This might be useful in case of a crash.

### CODE REVIEW

**Comment by hdgarrood** [comment]
The line endings on the diff look a bit funny - could you check to see if this has a mixture of Linux and windows style line endings?

**Comment by hdgarrood** [comment]
This fixes #2538. I generally like to avoid CPP but this seems like a good reason to use it. :+1: once line endings are sorted.

**Comment by alexbiehl** [comment]
Updated the patch. This even works for GHC-7.x. They won't print a callstack though.

**Comment by paf31** [comment]
Looks good, thanks! Please can you update `contributors.md` here as well.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
