### PR TITLE
Solve RowToList

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Will add a test once https://github.com/purescript/purescript-typelevel-prelude/pull/11 is merged.

### CODE REVIEW

**Comment by paf31** [comment]
Looks good! What do you think about including the types along with the labels?

**Comment by LiamGoodacre** [comment]
Yeah, I'm not opposed.  The two are equivalent in that we can use rowcons to look up the types.  It'd probably be more convenient to have both though.  In that case, what do you think about the names `RowEntries`/`EntryList`?

**Comment by paf31** [comment]
I was thinking `RowToList` originally. I'm hoping that we can build up a library of these sorts of classes: folds, maps, etc. once we have constraint kinds so that we can take a MPTC as an argument:

```purescript
class RowMap f xs ys | f xs -> ys

instance auto1 :: RowMap f () ()
instance auto2 :: (f a b, RowMap f r1 r2) => RowMap f (l :: a | r1) (l :: b | r2)
```

**Comment by LiamGoodacre** [comment]
Oh instead of two classes we can make have the fundeps in both directions `RowToList r l | r -> l, l -> r`.

**Comment by paf31** [comment]
With the new bidirectional fundep, what would the instances look like if you wrote them out? Does the coverage condition hold in both directions?

**Comment by paf31** [comment]
What I'm getting at is that a fundep doesn't just depend on the relation you're defining, but also how you define it, right? Like, numeric addition as a 3-way relation has the property that if you know two, you know the third, but in practice we define it by recursion on one or the other argument, so the coverage condition doesn't actually hold for one of the fundeps, I think.

**Comment by LiamGoodacre** [comment]
Ah yeah, because RowList doesn't have the ordering invariant it means multiple RowLists can compute the same rows.  So the bidirectional fundep doesn't make sense.  Thanks!
I'll switch back to two classes when I get some time.

**Comment by paf31** [comment]
I wasn't thinking about ordering so much, but that's true too, unless you require sorted lists. I was thinking more that you have to define the mapping by inspecting one argument or or other.

**Comment by LiamGoodacre** [comment]
Rebased on master.  If I add a test now, it will either depend on my typelevel-prelude clone, or it will fail until we decide where to put the class.

**Comment by paf31** [comment]
Thanks, looks great!

**Comment by paf31** [comment]
A little test I did in the REPL, for reference:

```
> data LProxy (list :: RowList) = LProxy
> :p
… f :: forall proxy row list. RowToList row list => proxy row -> LProxy list
… f _ = LProxy

> :t f { x: 1, y : 2}
LProxy (Cons "x" Int (Cons "y" Int Nil))

> -- testing open rows
> :t \o -> o.x (f o)
forall t4 t5 t8.            
  RowToList                 
    ( x :: LProxy t5 -> t8  
    | t4                    
    )                       
    t5                      
   => { x :: LProxy t5 -> t8
      | t4                  
      }                     
      -> t8
```

👍 Looks really great!

**Pull request merged**
