### PR TITLE
Add a stricter source span check for warnings

### PR DESCRIPTION
**Pull request by natefaubion**
Obviously now I have to fix the failing tests.

### CODE REVIEW

**Comment by natefaubion** [comment]
@garyb Any idea how

https://github.com/purescript/purescript/blob/c89e2f6d96879a91618d2c783c8f677d6bec5661/src/Language/PureScript/Sugar/Names/Imports.hs#L53

propagates all the way to

https://github.com/purescript/purescript/blob/c89e2f6d96879a91618d2c783c8f677d6bec5661/src/Language/PureScript/Sugar/Names/Env.hs#L474

**Comment by natefaubion** [comment]
Also, for my own curiosity, why are we creating such a nonsense span in the first place?

**Comment by natefaubion** [comment]
It seems like it was using the wrong source span. I now get something like this:

```
[1/1 ScopeShadowing] /Users/nathan/Sites/git/purescript/BadShadow.purs:3:1

  3  import Prelude
     ^^^^^^^^^^^^^^

  Shadowed definitions are in scope for value append from the following open imports:

    import Prelude

  These will be ignored and the local declaration will be used.
```

**Comment by natefaubion** [comment]
If that isn't correct, and the error should point to the local definition rather than the import, then that means we would need to lookup the source span of the appropriate declaration, rather than use the current module source span (which is bogus).

**Comment by natefaubion** [comment]
This should fix #3417

**Comment by natefaubion** [comment]
I can confirm that's what happens, which I don't really care for. Do you have a suggestion for how to get a hold of the source span for the particular declaration in question?

**Comment by garyb** [comment]
Not that I can think of, no. I think the newly positioned error is still pretty good though actually - you're warned that the version coming from the open import is unused, so the span being there rather than on the member that is actually resolved is perhaps better even?

Either way, I'll merge this, and we can open an issue to improve the error further if we think that's worth doing.

**Pull request merged**
