### PR TITLE
fixes purescript/#1673

### PR DESCRIPTION
**Pull request by mgmeier**
Among other solutions

* using a different data type (e.g ```Data.Text```)
* using strict I/O (package strict-io)

this fix is the least invasive.

It's tested on my system and works. It forces ```readFile``` to advance till reaching EOF (or an exception) and change the corresponding file handle's state, so that it can be GC'd.

### CODE REVIEW

**Comment by paf31** [comment]
Neat, thanks! :+1: 

Perhaps it makes sense to put this in its own function, but could you please document it with a line comment in either case?

**Comment by hdgarrood** [comment]
As an aside, I think switching to `Text` is probably a good idea, and I think there's an issue open for it somewhere anyway? #547? Not sure if that's related.

**Comment by mgmeier** [comment]
comment added.
IMHO it's preferable to leave ```length js``` in the same closure as ```js <- readFile ...```, so we prevent leaking of lazily read content in any case. This also guarantees the file handle being marked as "semi-closed" by the Haskell runtime before the next iteration, so it doesn't interfere with Mac OS 's crappy resource management.

**Comment by mgmeier** [comment]
and yeah, +1 for switching to ```Text``` ;)

**Comment by paf31** [comment]
Could you please include yourself in https://github.com/purescript/purescript/blob/master/CONTRIBUTORS.md?

**Comment by mgmeier** [comment]
(y)

**Comment by garyb** [comment]
Thanks! Sorry about the delay in merging, Phil is busy at the moment and I hadn't been keeping track of this.

**Comment by mgmeier** [comment]
no problem. looking forward to the next release :+1:

**Pull request merged**
