### PR TITLE
Add test cases for #3114

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR adds a minimal test case for #3114.

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
Should we maybe remove the annotations and make this a `pending` test? In its current state this PR introduces technical debt, because we need to remember to remove annotations and comment when the underlying issue was fixed.

**Comment by hdgarrood** [comment]
My understanding is that the underlying issue has already been fixed, and this test does fail between the two commits that @parsonsmatt identified as being the commits that introduced and fixed #3114, so it shouldn't need further modification.

**Comment by parsonsmatt** [comment]
Right, this is a regression test for a bug that was introduced and then accidentally fixed.

**Comment by hdgarrood** [comment]
Shall we go ahead and merge this then?

**Comment by kRITZCREEK** [comment]
I guess with the issue number attached we have enough context to understand the comment. 👍 from me

**Pull request merged**
