### PR TITLE
Efficient object updates for closed records 

### PR DESCRIPTION
**Pull request by fehrenbach**
See #1493.

This uses @matthewleon 's newly introduced CoreFn optimization infrastructure (#3218).

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
We're making a trade-off here, right? This will increase the size of the generated JS depending on how large of a record we are copying.

Should we pick a number of record properties at which we switch back to the loop?

**Comment by garyb** [comment]
I think we can set that threshold pretty high if we're going to have it, like 100 or something.

**Comment by fehrenbach** [comment]
It certainly is a trade-off. The appropriate measure to optimize for generated code size would be something like sum of length of field names that are not updated compared to size of the update loop.

In my dreams, we would just generate `Object.assign({}, inputRecord, {up: "-dated", "field":'s'})` which is short and JS engines would be clever, recognizing this as a copy with updates, but alas they are not and it's ES2015 anyway.

I can add a threshold, in whatever form, but to be honest I'd rather wait for someone to actually have a problem with huge records.

**Comment by fehrenbach** [comment]
For the record:
https://jsperf.com/copyobj
https://jsperf.com/copyobjhuge

**Comment by garyb** [comment]
> I can add a threshold, in whatever form, but to be honest I'd rather wait for someone to actually have a problem with huge records.

I'd tend to agree with that 👍

**Comment by garyb** [comment]
Also, sorry we're only getting around to commenting on this now - but big thanks! This is something I've wanted to do for a long time.

**Pull request closed without merging**
