### PR TITLE
Typecheck main in PSCi

### PR DESCRIPTION
**Pull request by paf31**
I noticed `Partial` functions would run incorrectly in PSCi since we didn't typecheck `main`. Now that we generalize constraints, we need to add a signature.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Will this throw an error unless you add in an `unsafePartial`? I think it might be nice to just evaluate expressions with Partial constraints automatically, without needing an `unsafePartial`. Not sure how difficult that is from an implementation perspective.

**Comment by paf31** [comment]
It does, yes. I figured that was probably the best default behavior, since you can always use `unsafePartial` in the REPL.

**Comment by paf31** [comment]
@hdgarrood So what do you think then?

**Comment by hdgarrood** [comment]
My gut says we should just let people evaluate partial expressions without requiring unsafePartial, but I think this is fine for now; we can try it and see what happens. It's not a big deal.

**Comment by paf31** [comment]
Alright, sounds good. We can create an issue to track it, but I'll merge this for now, so that we can get a release out.

**Pull request merged**
