### PR TITLE
Fix #922

### LINKED ISSUE #922: Instance Resolution Problem
I'm not exactly sure what's happening, but there appears to be some general problem in Purescript's type class instance resolution. In addition to https://github.com/purescript/purescript-transformers/issues/28, I have the following test case:

```purescript
module Foo where

import Data.Either
import Control.Monad.Error.Class
import Debug.Trace

foo :: forall m. (MonadError Unit m, Monad m) => m Number
foo = return 1

foo' :: Either Unit Number
foo' = foo

main = do
  case foo of
    (Right a) -> print a
```

It generates the error:
```
Attempted to unify a constrained type (Control.Monad.Error.Class.MonadError Prelude.Unit u11, Pr
elude.Monad u11) => u11 Prim.Number with another type.
```

Swapping the `case foo of` to `case foo' of` resolves the error. Both versions work in Haskell.

### PR DESCRIPTION
**Pull request by paf31**
@garyb How does this look?

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by paf31** [comment]
I just want to spend a bit of time testing this with `test-everything`, then I'll merge.

**Comment by paf31** [comment]
Ok, this breaks `purescript-free` in a confusing way, so I'm going to leave this one for now.

**Comment by garyb** [comment]
This isn't a viable fix then?

**Comment by paf31** [comment]
Possibly, and I'll leave the code here for now, but I need more time to figure out what's really going on. The typechecker needs some real attention, and better documentation too.

**Pull request closed without merging**
