### PR TITLE
Switch to Doc for custom type errors & remove TypeConcat/TypeString

### PR DESCRIPTION
**Pull request by LiamGoodacre**
Fixes https://github.com/purescript/purescript/issues/3134

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
Reminder: merge https://github.com/purescript/purescript-lists/pull/146 and revert `tests/support/bower.json` back to `purescript/purescript-lists#compiler/0.12`.

**Comment by LiamGoodacre** [comment]
Gone with
```purescript
module Prim.TypeError where

foreign import kind Doc
foreign import data Text :: Symbol -> Doc
foreign import data Quote :: Type -> Doc
foreign import data Beside :: Doc -> Doc -> Doc
foreign import data Atop :: Doc -> Doc -> Doc

class Fail (message :: Doc)
class Warn (message :: Doc)
```

**Comment by garyb** [comment]
Looks great so far 👍

**Comment by LiamGoodacre** [comment]
Yeah `Above` is better - will swap it out.  Thanks!

**Comment by garyb** [comment]
🎉

**Comment by LiamGoodacre** [comment]
Just merged https://github.com/purescript/purescript-lists/pull/146
Will revert the `tests/support/bower.json` in a new PR now.

**Pull request merged**
