### PR TITLE
Remove spurious doc comment on CoreFn Module

### PR DESCRIPTION
**Pull request by jmackie**
There have clearly been several changes since this comment was written, and is now incorrect. Best to remove it.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I'm not very familiar with this part of the compiler; can you explain why it's incorrect?

**Comment by natefaubion** [comment]
I think everything about the names is wrong, and this comment is definitely in the wrong place. I think it's important to document that we are not serializing types, but that should probably go in ToJSON/FromJSON.

**Comment by rhendric** [comment]
There are no types in CoreFn to serialize. If that fact needs to be called out explicitly, here is as good a place as any, but then the comment would just be `-- The CoreFn representation does not contain type information.`. Personally, I think @jmackie is correct: this comment is obsolete and can be dropped with prejudice.

**Review by rhendric — APPROVED** [review]

**Review by hdgarrood — APPROVED** [review]
Ok, that's good enough for me.

**Pull request merged**
