### PR TITLE
Emit _ instead of false case for if-then-else

### PR DESCRIPTION
**Pull request by rightfold**
This makes for better code generation.

### CODE REVIEW

**Comment by paf31** [comment]
Thanks!

> This makes for better code generation.

I believe you, but can you give an example? 😄

**Comment by rightfold** [comment]
```purescript
x a = if a then 1 else 2
```

before:
```javascript
var x = function (a) {
    if (a) {
        return 1;
    };
    if (!a) {
        return 2;
    };
    throw new Error("Failed pattern match at Main line 5, column 7 - line 5, column 24: " + [ a.constructor.name ]);
};
```

after:
```javascript
var x = function (a) {
    if (a) {
        return 1;
    };
    return 2;
};
```

**Comment by paf31** [comment]
I thought we used `? ... : ...` for `if then else`. Did that change?

**Comment by paf31** [comment]
Looks good, thanks!

**Comment by rightfold** [comment]
`?:` operator might have been pre-CoreFn?

**Comment by paf31** [comment]
Ah right.

**Pull request merged**
