### PR TITLE
Refactors 2

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by paf31** [comment]
You seem to have added back `Control.Monad.Unify`.

**Comment by paf31** [comment]
Also, what changed in `Sugar/TypeClasses/Deriving.hs`?

**Comment by phadej** [comment]
- Removed `Control.Monad.Unify`.
- `Sugar/TypeClasses/Deriving.hs` changes are visible in second commit. First one reformats to it use unix line endings (if was the only file).

**Comment by paf31** [comment]
Great, thanks!

**Pull request merged**
