### PR TITLE
Remove dodgy check rule

### PR DESCRIPTION
**Pull request by paf31**
I don't think we need this any more. Waiting on tests...

### CODE REVIEW

**Comment by garyb** [comment]
Does this depend on #1490 being merged first?

**Comment by paf31** [comment]
I think there will be conflicts either way but they should hopefully be easily resolved.

**Comment by garyb** [comment]
Actually I was wondering if removing this rule comes as a consequence of changes made in #1490, or whether removing it is still valid even before then. If we can get rid of it now, can you explain why we don't need it?

**Comment by paf31** [comment]
It's independent. It used to be necessary for some obscure reason, but now that we change into inference mode whenever checking fails, we don't need it.

**Comment by garyb** [comment]
Right, that makes sense. Thanks for explaining! :+1:

**Pull request merged**
