### PR TITLE
Added basic warningsWriter

### PR DESCRIPTION
**Pull request by mjgpy3**
See #803. I have no clue if this is right, I thought I'd take a stab at it. Feedback is much appreciated.

### CODE REVIEW

**Comment by paf31** [comment]
So we definitely want to use `WriterT`, but we will need to integrate it into the existing typechecker monad transformer stack in `Language.PureScript.TypeChecker.Monad`.

Also, I think it makes sense to make the type of warnings different from the type of errors. I would probably like to see both of them become data types, with separate functions to render them for display to the user.

**Comment by mjgpy3** [comment]
Awesome, thanks so much for the feedback. I'll take another stab at it tonight.

**Comment by paf31** [comment]
It might be a good idea to tackle #745 first. That would probably help you to familiarize yourself with how errors work, and the structure of the type checker monad.

A good first step might be to make a list of all of the different types of errors in the application, and a list of possible warnings (e.g. a name got shadowed).

**Comment by mjgpy3** [comment]
Great! I'll have a look at it tonight, thanks!

**Comment by paf31** [comment]
Is this abandoned? It would need quite a lot more work, so I will close it unless there are plans to revive it.

**Comment by mjgpy3** [comment]
Yes, it's abandoned, I haven't had the time, unfortunately.

**Comment by mjgpy3** [comment]
Can you advise on a more entry-level issue? I am very interested in this project and would love to contribute, but feel unable to dive in the deep end.

**Comment by paf31** [comment]
Ok, no worries. Maybe error messages would be a good place to make some improvements? Maybe take a look at the error-messages label on the issue tracker?

**Pull request closed without merging**
