### PR TITLE
Default require path to ../, warn from psc

### PR DESCRIPTION
**Pull request by nwolverson**
#1698 

Does this need a warning from psc-bundle too?

Incidentally I noticed that if you specified a non-empty require path not ending in `/` (e.g. just `..`), `psc` and `psc-bundle` would behave differently.

### CODE REVIEW

**Comment by paf31** [comment]
> Does this need a warning from psc-bundle too?

Yes, I think so.

:+1: Looks good.

**Comment by paf31** [comment]
@garyb Good to merge?

**Comment by garyb** [comment]
Yep :+1:

**Comment by hdgarrood** [comment]
Is this missing from the release notes? I think it went into 0.8.4, right?

**Comment by nwolverson** [comment]
0.8.3 https://github.com/purescript/purescript/commit/546809cbc318ebbcff7e16764ec32710090d1eaf

**Comment by hdgarrood** [comment]
Ah, oops, thanks. Not sure how I missed that in the release notes. I guess I misunderstood the github UI; presumably this part of the UI just lists all the tags which contain the commit, then?

screen shot 2016-04-20 at 14 50 41

**Pull request merged**
