### PR TITLE
Require single-method instance declarations to be indented

### PR DESCRIPTION
**Pull request by quesebifurcan**
Resolves https://github.com/purescript/purescript/issues/2947

### CODE REVIEW

**Comment by quesebifurcan** [comment]
Thanks for the swift review. Looks like `purescript.cabal` was added to `.gitignore` recently: https://github.com/purescript/purescript/commit/947c950a58a9949015bdc63f41246578e9696118

**Comment by LiamGoodacre** [comment]
Oh interesting, thanks!

**Comment by hdgarrood** [comment]
I don't think this previously would have required a cabal file change anyway, it used to be only when you added a directory that you would need to change it, since the globbing in cabal files doesn't allow any kind of recursive includes like `**/*.purs`. Now that we generate the cabal file using hpack it should be even more rare that adding test files needs a corresponding change in package.yaml. Anyway yeah this looks good to me :+1:

**Comment by paf31** [comment]
Thanks! Please update CONTRIBUTORS.md as well and I'll get this merged in.

**Comment by paf31** [comment]
Thanks!

**Comment by paf31** [comment]
Unfortunately, this is a breaking change, since the compiler no longer allows code like this, which occurs quite frequently:

```purescript
instance foo :: Foo String where

instance bar :: Bar String where
  member = ...
```

Note how `foo` has no members but still uses `where`.

I'll revert this, but we can try to include it in the next breaking release or find a way to make it non-breaking.

**Comment by paf31** [comment]
@quesebifurcan Would you like to reopen this now that we're putting 0.12.0 together? Thanks!

**Comment by quesebifurcan** [comment]
@paf31 Sure, I'll see if I can come up with something (preferably non-breaking) over the weekend. If not, I'm happy to let someone else take over.

**Comment by paf31** [comment]
Oh it's fine to break now, we're at a major release. You could just reopen the PR if you like.

**Pull request merged**
