### PR TITLE
Travis tweaks

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by paf31** [comment]
Thanks!

Is there any reason not to use `--fast` for any non-deployment builds?

**Comment by kRITZCREEK** [comment]
I guess it turns off any optimizations? Might get in our way if we started doing benchmarks as a CI thing.

**Comment by phadej** [comment]
@paf31 you already do
```
STACK_EXTRA_FLAGS=""
if [ -z "$TRAVIS_TAG" ]
then
  # On non-release builds, disable optimizations.
  STACK_EXTRA_FLAGS="--fast"
fi
```

I guess, that check could check `$DEPLOY` variable as well

**Comment by paf31** [comment]
Ah, I didn't know that. Thanks.

LGTM.

**Comment by paf31** [comment]
`Invalid option `--fast'`, apparently.

**Comment by paf31** [comment]
Apparently pattern synonyms need signatures with GHC 8 and `-Werror`.

**Comment by phadej** [comment]
I'll check failures on Monday latest.

**Comment by phadej** [comment]
@paf31 please review, travis is green. I was bold and removed all redundant constraints, though some of them might have been there for a reason, OTOH there wasn't comments justifying that.

**Comment by paf31** [comment]
Thanks @phadej!

**Pull request merged**
