### PR TITLE
Ensure all integer ops are in the Int32 range

### PR DESCRIPTION
**Pull request by garyb**
Also inlines `mod` now I've checked that `(%)` does actually give us the right behaviour for ints.

### CODE REVIEW

**Comment by paf31** [comment]
Seems good to me. @michaelficarra, any comments?

**Comment by garyb** [comment]
Made the same change in `purescript-integers` here: purescript/purescript-integers@e0d71323854185bb48cb6827d079cbee8aea6851 but will hold off releasing it as 0.1.0 until we hear from @michaelficarra.

**Comment by michaelficarra** [comment]
Both LGTM.

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
