### PR TITLE
Resolves #1169. Throw constructor arity error when case omits params

### LINKED ISSUE #1169: Produce better error when a case does not match all of a data constructor's arguments
Currently this results in a type error, but an explicit error message for not matching all of the arguments would be much clearer.

### PR DESCRIPTION
**Pull request by mjgpy3**
First shot.

Let me know if it looks okay :)

### CODE REVIEW

**Comment by paf31** [comment]
Let me think about this one. I want to see if we can extract out a function so that we can avoid the duplication of `throwIncorrectArity`

**Comment by mjgpy3** [comment]
Alright, thanks for looking!

**Comment by mjgpy3** [comment]
@paf31, had any time to think about this?

**Comment by paf31** [comment]
Sorry I'll have a look today.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
