### PR TITLE
Fix #1465

### LINKED ISSUE #1465: Warning for shadowed type variables in a scoped type variables situation

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb

### CODE REVIEW

**Comment by paf31** [comment]
We might want to consider doing all shadowing checks like this?

**Comment by paf31** [comment]
Let's not put this into a patch. It also seems to suffer from the multiple warnings issue.

**Comment by paf31** [comment]
Actually, the multiple warnings are correct. `Data.Map` has _a lot_ of shadowed scoped type variables.

**Comment by garyb** [comment]
Yeah, let's not put this one in the patch - I think more than `Data.Map` will explode with warnings with this?

**Comment by paf31** [comment]
Shall I merge this one now?

**Comment by garyb** [comment]
Sure :+1:

**Pull request merged**
