### PR TITLE
Fix everythingWithScope traversal bug, fix #2718

### LINKED ISSUE #2718: A case where a shadowed variable name is not detected
``` purescript
setKey ∷ EJ.EJson → EJ.EJson → EJ.EJson → EJ.EJson
setKey k (EJ.EJson x) v = case EJ.head v of
  EJ.Map fields →
    EJ.EJson <<< roll <<< EJ.Map $ map
      (\(kv@(Tuple k v)) → if k == k then Tuple k x else kv) fields
  _ → v
```

`k` is shadowed as it's introduced in `setKey` as well as the lambda/`Tuple k v` pattern.

### PR DESCRIPTION
**Pull request by paf31**
Another small traversal bug.

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
We seem to have lots of problems with these traversals :(
I might have a think at some point about how we can do better.

**Comment by paf31** [comment]
@LiamGoodacre Thanks for the review! The problem is that this particular traversal is not structural. Perhaps if we used something like `bound` we could do better.

**Comment by garyb** [comment]
Thanks for looking at this! Sorry the example wasn't too minimal, I intended to take a look myself when I got some time again.

**Comment by paf31** [comment]
Sure - it took me a while to find the minimal example actually, because I wasn't thinking about the parens :)

**Pull request merged**
