### PR TITLE
Warnings for missing top-level type declarations, fix #1333

### LINKED ISSUE #1333: Warnings for missing top-level type declarations

### PR DESCRIPTION
**Pull request by paf31**
@garyb Could you please review this?

Thanks.

### CODE REVIEW

**Comment by garyb** [comment]
Nice :+1: :smile:

**Comment by paf31** [comment]
Oops, this actually checks all declarations, not just top-level ones. I'll fix this.

**Comment by paf31** [comment]
Ok this should be better. I'll verify using the `core-tests` output when Travis finishes.

**Comment by paf31** [comment]
CI looks good now. I'll merge.

**Pull request merged**
