### PR TITLE
Bump dependencies for semigroups-0.18

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by phadej** [comment]
Seems that travis script picks dependencies already installed. Can someone clear caches and rebuild this?

**Comment by paf31** [comment]
Looks like it's building correctly to me.

**Comment by phadej** [comment]
ping @paf31, @garyb Can you merge this, and make a revision on Hackage. Thanks in advancce.

**Comment by paf31** [comment]
I'll release this today as a branch off of v0.7.5.3 instead of `master`. Thanks.

**Comment by phadej** [comment]
@paf31 great, thanks.

**Comment by paf31** [comment]
Working on this now.

**Comment by paf31** [comment]
I put this in `master`, and also copied it to a `0.7.5.4` branch, off of the `v0.7.5.3` tag. I won't release that, but 0.7.5.4 is on Hackage now.

**Comment by phadej** [comment]
Thanks!

**Pull request closed without merging**
