### PR TITLE
Fix #1315

### LINKED ISSUE #1315: Suggestions for row unification errors
Two examples of modules which have type errors, and the error messages that they currently produce:
* Extra record field
```purescript
module ExtraRecordField where
import Prelude ((<>))

full :: { first :: String, last :: String } -> String
full p = p.first <> " " <> p.last
oops = full { first: "Jane", last: "Smith", age: 29 }
```
```
Row last :: Prim.String, first :: Prim.String lacks required property "age"
```
* Missing record field
```purescript
module MissingRecordField where
import Prelude ((>))

john = { first: "John", last: "Smith" }
isOver50 p = p.age > 50.0
result = isOver50 john
```
```
  Cannot unify type
    ()
  with type
    (age :: Prim.Number | _1)
```

I think these could be improved a little. In the first example, I think it makes more sense to say that the object `{ first: "Jane", last: "Smith", age: 29 }` has an *extra* field "age", rather than the row `{ first :: String, last :: String }` missing the required field "age". In the second, I think a `PropertyIsMissing` error would be more appropriate than the current "Cannot unify type" error.

### PR DESCRIPTION
**Pull request by paf31**
@garyb @hdgarrood Could you please review this?

Thanks.

### CODE REVIEW

**Comment by paf31** [comment]
Ok, this is ready for review.

**Comment by hdgarrood** [comment]
I don't understand the stuff inside the type checker, but everything else :+1:

**Comment by garyb** [comment]
Looks good to me - interesting place to catch the error too, I wasn't really sure how you were going to do this. I wonder about missing "row" out of the error message now, but I think it's probably fine, as labels only reside in rows, so :+1:

**Comment by paf31** [comment]
Thanks for the reviews.

**Pull request merged**
