### PR TITLE
psc-publish: Try "bower.cmd" if "bower" is not found

### LINKED ISSUE #1317: psc-publish cannot find bower on Windows
```
Details:
  While running `bower list --json --offline`:
    bower: readProcess: does not exist (No such file or directory)
```

I think this is because it needs to be called as `bower.cmd`, pulp had a similar issue at one point.

### PR DESCRIPTION
**Pull request by hdgarrood**
Fixes #1317. I haven't tested this, though, as I don't have a Windows machine to hand.

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks good. @garyb if I merge this, do you think you'd be able to test it, please?

**Comment by michaelficarra** [comment]
I'd rather look for `bower.cmd` only if I'm on windows platform. If I have an executable `bower.cmd` in my path, I'd be surprised if it was executed.

**Comment by garyb** [comment]
Sure, I can test it now actually.

**Comment by garyb** [comment]
Well it didn't fail because bower was missing, but I just uploaded this: http://pursuit.purescript.org/packages/purescript-maybe/0.3.3 (no modules listed).

I think @michaelficarra has a point too, adding a platform check should be easy enough I think?

**Comment by hdgarrood** [comment]
Yeah, the platform check is just `System.Info.os == "mingw32"` I think.

So you tried running `psc-publish` using this branch on Windows, with Bower installed, but when you uploaded it, there were no modules?

**Comment by hdgarrood** [comment]
Also, @garyb, would you mind running it again but posting the output as a gist or something?

**Comment by garyb** [comment]
Sure thing:

```
{"uploader":null,"packageMeta":{"homepage":"https://github.com/purescript/purescript-maybe","repository":{"url":"git://github.com/purescript/purescript-maybe.git","type":"git"},"ignore":["**/.*","bower_components","node_modules","output","test","bower.json","gulpfile.js","package.json"],"dependencies":{"purescript-monoid":"^0.3.0"},"name":"purescript-maybe","keywords":["purescript"],"description":"Optional values"},"modules":[],"resolvedDependencies":{"purescript-control":"0.3.0","purescript-invariant":"0.3.0","purescript-monoid":"0.3.0","purescript-prelude":"0.1.1"},"bookmarks":[],"version":"0.3.3","github":["purescript","purescript-maybe"],"versionTag":"v0.3.3","compilerVersion":"0.7.1.0"}
```

**Comment by paf31** [comment]
Is this good to merge now?

**Comment by hdgarrood** [comment]
No, I still need to check the platform before trying `bower.cmd`.

**Comment by paf31** [comment]
No worries, just checking. Thanks.

**Comment by hdgarrood** [comment]
Ok I think this is good to go now. @garyb, would you mind testing this on Windows please?

**Comment by garyb** [comment]
:+1:

**Pull request merged**
