### PR TITLE
Incorporate Add/Mul dictionaries in Int.Compare type class solver

### LINKED ISSUE #4333: Int.Compare unexpectedly doesn't solve type class
## Description

Not sure what's triggering this, but I would expect this to compile.

## To Reproduce

```purs
module Main where

import Prelude

import Data.Reflectable (class Reflectable, reflectType)
import Prim.Int as PI
import Prim.Ordering as PO
import Type.Proxy (Proxy)

-- | Valid bounds are between 1 and 5
newtype N = N Int

type MinN :: Int
type MinN = 1

type MaxN :: Int
type MaxN = 5

mkN
  :: forall i lower upper
   . Reflectable i Int
  => PI.Add MinN (-1) lower
  => PI.Compare i lower PO.GT
  => PI.Add MaxN 1 upper
  => PI.Compare i upper PO.LT
  => Proxy i
  -> N
mkN p = N $ reflectType p

data Something = Something N Int

mkSomething
  :: forall i lower upper
   . Reflectable i Int
  => PI.Add MinN (-1) lower
  => PI.Compare i lower PO.GT
  => PI.Add MaxN 1 upper
  => PI.Compare i upper PO.LT
  => Proxy i
  -> Int
  -> Something
mkSomething p i = Something (mkN p) i
```

## Expected behavior

This should compile.

## Additional context

See https://github.com/purescript/purescript-datetime/pull/97

## PureScript version

`0.15.0`, `0.15.1`

### PR DESCRIPTION
**Pull request by JordanMartinez**
**Description of the change**

Fixes #4333. Currently a WIP used to help facilitate discussion on this bug fix.

---

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Latest changes makes the original test pass. However, I added a few variants to ensure that an Add-Compare, Mul-Compare, and Add-Mul-Compare combo all work. The `Add-Mul-Compare` test currently fails and I believe a corresponding version where the `Add` constraint is dependent on the `Mul` constraint would likewise fail. Explanation below:

Adding a trace produces this context for the failing test:

<details>
<summary>Trace</summary>

```
Context: 
  LessThan
    Skolem () "i" (Just (TypeConstructor () (Qualified (Just (ModuleName "Prim")) (ProperName {runProperName = "Int"})))) 3 (SkolemScope {runSkolemScope = 10})
    Skolem () "two" (Just (TypeConstructor () (Qualified (Just (ModuleName "Prim")) (ProperName {runProperName = "Int"})))) 5 (SkolemScope {runSkolemScope = 12})
  LessThan
    TypeLevelInt () 0
    TypeLevelInt () 1
  Equal
    TypeLevelInt () 1
    TypeLevelInt () 1
  Equal
    TypeLevelInt () 0
    TypeLevelInt () 0
  Equal
    TypeLevelInt () 1
    TypeLevelInt () 1
  Equal
    Skolem () "one" (Just (TypeConstructor () (Qualified (Just (ModuleName "Prim")) (ProperName {runProperName = "Int"})))) 4 (SkolemScope {runSkolemScope = 11})
    TypeLevelInt () 1
```

</details>

which is visualized like this where `a -> b` means `a < b` and `a -- b` means `a == b`:
```mermaid
flowchart LR
  i --> two
  0 --> 1
  1 --- 1
  0 --- 0
  one --- 1
```

The issue is that the `Mul one 2 two` constraint (i.e. `two == 2` because `one == 1` and `1 * 2 == 2`) isn't included in the context. It's excluded because `mulInts` only works on literal type-level integers, not those inferred from the context (e.g. `one`). I would need to add a loop mechanism that can fully resolve `one` to `1` before `mulInts` would work. I don't think this is the best solution as it means solving all `Add` and `Mul` constraints `n + 1` times where `1` represents the original `Add`/`Mul` solution and `n` represents the number of `Compare` constraints there are.

**Comment by rhendric** [comment]
I'm skeptical that this should be fixed by tinkering with how `Compare` is solved by the compiler.

Check this version of the original issue for comparison:

```purs
class Add l r o | l r -> o
instance Add "1" "-1" "0"
instance Add "5" "1" "6"

class Compare l r o | l r -> o

-- | Valid bounds are between 1 and 5
newtype N = N String

type MinN :: Symbol
type MinN = "1"

type MaxN :: Symbol
type MaxN = "5"

mkN
  :: forall i lower upper
   . IsSymbol i
  => Add MinN "-1" lower
  => Compare i lower PO.GT
  => Add MaxN "1" upper
  => Compare i upper PO.LT
  => Proxy i
  -> N
mkN p = N $ reflectSymbol p

data Something = Something N Int

mkSomething
  :: forall i lower upper
   . IsSymbol i
  => Add MinN "-1" lower
  => Compare i lower PO.GT
  => Add MaxN "1" upper
  => Compare i upper PO.LT
  => Proxy i
  -> Int
  -> Something
mkSomething p i = Something (mkN p) i
```

There's no issue here, despite the fact that there are zero instances of `Compare` to be used. The compiler should be picking the correct dictionary from the context in `mkSomething`, as it does in this case. Because this example works and the original issue doesn't, that seems to me like evidence that something about the instance resolution loop isn't working correctly with compiler-solved classes in general, not that there's something wrong with how `Compare` is solved specifically.

**Comment by JordanMartinez** [comment]
> Because this example works and the original issue doesn't, that seems to me like evidence that something about the instance resolution loop isn't working correctly with compiler-solved classes in general, not that there's something wrong with how Compare is solved specifically.

That would explain a lot. I thought perhaps the compiler had some extra code for `Symbol` when doing multiple `Append`s and/or `Compare`s, but it doesn't. So, I believe you're right.

**Comment by JordanMartinez** [comment]
Rather than using `PI.Add`, if I define my own `Add`, it compiles:
```purs
module Main where

import Prelude

import Effect.Console (log)
import Data.Reflectable (class Reflectable, reflectType)
import Prim.Int as PI
import Prim.Ordering as PO
import Type.Proxy (Proxy(..))

class Add l r o | l r -> o
instance Add 1 (-1) 0
instance Add 5 1 6

-- | Valid bounds are between 1 and 5
newtype N = N Int

type MinN :: Int
type MinN = 1

type MaxN :: Int
type MaxN = 5

mkN
  :: forall i lower upper
   . Reflectable i Int
  => Add MinN (-1) lower
  => PI.Compare i lower PO.GT
  => Add MaxN 1 upper
  => PI.Compare i upper PO.LT
  => Proxy i
  -> N
mkN p = N $ reflectType p

data Something = Something N Int

mkSomething
  :: forall i lower upper
   . Reflectable i Int
  => Add MinN (-1) lower
  => PI.Compare i lower PO.GT
  => Add MaxN 1 upper
  => PI.Compare i upper PO.LT
  => Proxy i
  -> Int
  -> Something
mkSomething p i = Something (mkN p) i

main = log "Done"
```

**Comment by JordanMartinez** [comment]
Closing because this approach isn't correct and I still did not have a clue as to how to fix this after spending some time trying and failing to understand the code.

**Pull request closed without merging**
