### PR TITLE
Do not allow empty case statement

### LINKED ISSUE #1435: Case parse bug
```purescript
error err = case err of \_ -> 1
```

parses but probably shouldn't.

### PR DESCRIPTION
**Pull request by zudov**
Fixes #1435

### CODE REVIEW

**Comment by garyb** [comment]
:+1:

**Comment by phadej** [comment]
What about `Void`?

**Comment by garyb** [comment]
You could still write `case v of _ -> ...`. I don't think there's any good explanation of what a case with no patterns represents.

**Comment by zudov** [comment]
@phadej If I understand correctly, doing
```purescript
foo :: Void -> _
foo void = case void of _ -> ..
```
is useful only in a lazy setting, as a way to force the void and make the hack which was used to create it reveal itself (e.g. throw `error: undefined` if Void was created with `undefined :: Void`).

In strict setting `absurd` should be as good. Correct me if I'm wrong.

Although, this only applies to the actual `Void` for which we have absurd.

**Comment by zudov** [comment]
By the way, it now makes sense to use NonEmpty for case alternatives, I'll take a look a bit later how well-suited that is.

**Comment by phadej** [comment]
@zudov check `-XEmptyCase` https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/syntax-extns.html

```hs
case onlyVoid of _ -> ..
```
has *redundant* case expression

I cannot come with real world example where writing like that would be useful, but I can imagine some type level trickery (not only `Void` is non-inhabitant type)

**Comment by paf31** [comment]
:+1:

**Comment by zudov** [comment]
@phadej Yeah, I had `-XEmptyCase` in mind, AFAIK the canonical example are things like
```purescript
instance Show Void where
   show void = case void of {}
instance Eq Void where
   (==) void1 void2 = (case void1 of {}) `seq` (case void2 of {})
```
This would have advantage over `absurd` as it would evaluate `void`.

**Comment by zudov** [comment]
Given [that](https://github.com/purescript/purescript/issues/1435#issuecomment-136021828), it seems like it would be better to live `Case` AST definition as it is (do not change to `Case Expression (NonEmpty CaseAlternative)`.

I guess we can merge it now.

**Comment by phadej** [comment]
:+1:

**Pull request merged**
