### PR TITLE
Include stack files in the distribution

### PR DESCRIPTION
**Pull request by zudov**
https://twitter.com/ndm_haskell/status/654764513221185537

### CODE REVIEW

**Comment by paf31** [comment]
:+1: Looks good, thanks!

**Comment by zudov** [comment]
How about we also include README?

**Comment by paf31** [comment]
The markdown file? I don't see any reason not to include it.

Does the LICENSE file already get included? That and CONTRIBUTORS.md might be worth adding..

**Comment by zudov** [comment]
`LICENSE` is included since it's mentioned in `license:` field.

I'll add the rest.

**Comment by zudov** [comment]
Should be ready to merge now if no additions are wanted.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
