### PR TITLE
Use sndM instead of traverse, fix #1211

### LINKED ISSUE #1211: Installation error
When running `cabal install purescript`, I get the following error:

```
src/Language/PureScript/CodeGen/JS/AST.hs:297:59:
    Could not deduce (Data.Traversable.Traversable ((,) String))
      arising from a use of `traverse'
    from the context (Applicative m, Monad m)
      bound by the type signature for
                 everywhereOnJSTopDownM :: (Applicative m, Monad m) =>
                                           (JS -> m JS) -> JS -> m JS
      at src/Language/PureScript/CodeGen/JS/AST.hs:289:27-80
    Possible fix:
      add an instance declaration for
      (Data.Traversable.Traversable ((,) String))
    In the first argument of `traverse', namely `(traverse f')'
    In the second argument of `(<$>)', namely
      `traverse (traverse f') js'
    In the expression: JSObjectLiteral <$> traverse (traverse f') js
Failed to install purescript-0.7.0.0
cabal: Error: some packages failed to install:
purescript-0.7.0.0 failed during the building phase. The exception was:
ExitFailure 1
```

```
$ ghc -V
The Glorious Glasgow Haskell Compilation System, version 7.6.3
$ cabal -V
cabal-install version 1.22.6.0
using version 1.22.4.0 of the Cabal library 
```

### PR DESCRIPTION
**Pull request by paf31**
@garyb @hdgarrood Look ok?

### CODE REVIEW

**Comment by hdgarrood** [comment]
:+1: perhaps it might be worth trying to build with GHC 7.6 now?

**Comment by paf31** [comment]
Yeah, I don't have it installed on my Mac any more. Maybe my other machine has it, I'll check.

**Comment by hdgarrood** [comment]
I just realised: rather than fiddle about trying to instalI GHC 7.6 on our own machines, we should just ask Travis to check for us!

**Comment by garyb** [comment]
:+1:

**Comment by garyb** [comment]
No good?

**Comment by paf31** [comment]
No, it's good. I `cherry-pick`ed the commit into `master` without the Travis changes.

**Pull request closed without merging**
