### PR TITLE
Try to fix #1548

### LINKED ISSUE #1548: Thread block on recompile
```
psc: make: dependency should already have been built.
psc: thread blocked indefinitely in an MVar operation
```
Message after change in already compiled module. Removing `psc` output and recompile works. Error is raised non-determenistically.

### PR DESCRIPTION
**Pull request by paf31**
@cryogenian Could you please test this?

### CODE REVIEW

**Comment by paf31** [comment]
This is the only real blocker to 0.7.5.1 going out, so if someone could test this (who could reproduce the original issue), I'd really appreciate it.

**Comment by cryogenian** [comment]
Sure, will test

**Comment by paf31** [comment]
Thanks @cryogenian !

**Comment by cryogenian** [comment]
Fixed :+1:

**Comment by paf31** [comment]
Excellent, thanks very much!

**Pull request merged**
