### PR TITLE
Fix #1146, update psci for 0.7 module changes, and support :foreign

### LINKED ISSUE #1146: Ability to load foreign modules in psci
So that `pulp` and other tools can automate things properly with the `.psci` file when there are foreign modules involved.

### PR DESCRIPTION
**Pull request by paf31**
@garyb @hdgarrood Could you please review this? Thanks.

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me. :+1:

**Comment by paf31** [comment]
I have changes for `pulp` too, which I'm about to open a PR for, and this lets me test the `-rc.1` libraries in `psci` successfully.

**Comment by garyb** [comment]
Ah cool, I guess we'll need to update the gulp `psci` task also.

I'm about to go out for a little while, but will be back on IRC later.

**Comment by paf31** [comment]
Is there anything else which _needs_ to go in before I cut the 0.7 RC? If not, I'll do that this afternoon.

**Comment by garyb** [comment]
Just #1147 I think.

**Pull request merged**
