### PR TITLE
Switch to stack for CI, resolves #1974

### LINKED ISSUE #1974: Use Stack/LTS for CI builds
As long as we have reproducible builds and a simple way to get new contributors up and running, I don't see a need to build against multiple GHC versions any more, since Stack will download the correct version of GHC anyway.

Why not just standardize on a single LTS version (which can change over time)?

### PR DESCRIPTION
**Pull request by hdgarrood**
* Remove the stack-nightly.yaml, since it always needs updating.
  Instead, we pass --resolver=nightly in one of the build jobs to ensure
  we always have the latest nightly. As an added bonus we no longer have
  to set the STACK_YAML environment variable on Windows, because
  stack.yaml is no longer a symlink.
* Remove use of cabal-install, which drastically simplifies the CI
  scripts :)
* Use the 'compiler' key in the build matrix as a hack to ensure each
  build job gets a separate cache.
* Add OSX tests.
* Add haddock tests, on a separate build job (for speed).
* Use separate build jobs for sdist tests (for speed).
* Fix binary bundle uploading on Travis
* Add binary bundle uploading for OSX.

Coverage did not work when I was building on Travis with my fork, but I think that was because of an API key environment variable missing, or something like that. So hopefully it should work here.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Resolves #2034.

**Comment by hdgarrood** [comment]
In case you were wondering, I've canceled the Travis CI build for the second commit. I'm going to restart it when the first one finishes so that it can use the cache.

**Comment by paf31** [comment]
Great work, thanks very much! 

Just a note: this also seems to remove the `core-tests` run. I'm not sure if that was even working on `0.9` anyway due to the breaking changes, but it'll be worth trying to reinstate it at some point. We'll have to remember to run it manually before releasing 0.9.

**Comment by hdgarrood** [comment]
👍 , opened #2101

**Comment by paf31** [comment]
So this is ready to merge?

**Comment by hdgarrood** [comment]
I think so.

**Comment by paf31** [comment]
Thanks very much!

**Pull request merged**
