### PR TITLE
Make 0.15.2 release

### PR DESCRIPTION
**Pull request by rhendric**
**Description of the change**

Rename 0.15.1 release to 0.15.2. (See #4328.)

---

**Checklist:**

- [ ] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [ ] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by JordanMartinez — APPROVED** [review]

**Comment by JordanMartinez** [comment]
I think there might be some interplay between the CI that gets triggered once a release PR like this one is merged and the CI that gets triggered when I create a GH release-tag that actually builds the binaries. :man_shrugging:

**Comment by rhendric** [comment]
What makes you say that?

Possibly separately, I noticed that the second run of the 0.15.2 release Linux build failed because a file already existed in the release from the first run, but I doubt that's caused by the CI build; seems more likely a bug in the upload-release-assets action.

**Comment by JordanMartinez** [comment]
Ah... that could be it. But yeah, that was the interplay I was wondering about.

Alternatively, if we have a PR like this one get merged, perhaps we no longer need the manual GH release that creates a git tag that triggers CI that uploads the built binaries into the GH release? AFAIK, with CD basically set up, the only thing extra we would need to do is add a Hackage credential to automatically upload stuff via `stack upload .`.

**Comment by rhendric** [comment]
I'm generally in favor of automating all the things!

**Comment by JordanMartinez** [comment]
Let's discuss that further. This test run of automation has generally worked out really well, and removing me from the picture just streamlines it further.

Anyways, `0.15.2` has now been published to NPM and Hackage. Please make the announcement! See [0.14.4](https://discourse.purescript.org/t/purescript-v0-14-4-released/2552) as an example.

**Pull request merged**
