### PR TITLE
Small fixes

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Just some things I found while browsing the code.

### CODE REVIEW

**Comment by garyb** [comment]
> Coverage increased (+0.001%)

It's still an increase! :laughing: 

:+1:

**Comment by garyb** [comment]
OSX bug is back? :confused: 

I restarted the build as it only failed on one of the osx images.

**Comment by kRITZCREEK** [comment]
see #2112 . I'm hoping that will fix the OSX errors for good

**Comment by paf31** [comment]
Looks good, but if we're supporting base 4.7 now, let's remove `traverseEither` from `Language.PureScript.Make` too.

**Comment by kRITZCREEK** [comment]
removed `traverseEither` and fixed conflicts

**Pull request merged**
