### PR TITLE
Fix builtin links

### PR DESCRIPTION
**Pull request by hdgarrood**
Unfortunately, links to Prim declarations are still broken on Pursuit; I guess this bug sneaked in while I was transferring this code to this repo. I've fixed it again (and verified that it fixes the issue in Pursuit) and also added a test.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Argh, one of these days I'm going to remember to wait for CI to finish first.

**Comment by hdgarrood** [comment]
Thanks! I was planning to point directly to this commit in `master` from Pursuit's stack.yaml so that we don't need to release a 0.10.7, does that sound okay to you?

**Comment by garyb** [comment]
We probably need a .7 soon anyway: #2642

**Comment by hdgarrood** [comment]
Argh, that's my fault too, sorry!

**Pull request merged**
