### PR TITLE
Direct proposals to Discourse

### PR DESCRIPTION
**Pull request by hdgarrood**
Following on from #3832. We've had an implicit and only partially enforced policy for a while that would prefer to keep the issue tracker for things that a) involve dev work on the compiler and b) have already had at least a tentative approval from a maintainer, and so in a few occasions in the past we've closed issues and asked people to open threads on Discourse first. For example:

* #3723 
* #3755 
* #3757

This PR updates the issue templates to encourage people to open threads on Discourse for discussing proposals for changing either the language or the compiler first, so that this policy is a bit clearer and more explicit. Discourse allows setting the topic and post body via query strings so I've done that in order to retain the existing proposal template. I've made the PR from the master branch of my fork so you can see how it looks there: https://github.com/hdgarrood/purescript/issues/new/choose

### CODE REVIEW

**Comment by natefaubion** [comment]
I don't think this is necessarily a bad thing, but my experience is that Discourse garners _far_ less participation that GH issues.

**Comment by hdgarrood** [comment]
I'd say a proposal should become a compiler ticket once it has tentative approval from one core owner, and also provided that it actually represents work to be done on the compiler. I'm not sure where the best place to note this down would be, though. CONTRIBUTING.md?

**Comment by hdgarrood** [comment]
By the way if we want to stop using this policy (of not allowing feature requests to come directly to this issue tracker) then that's fine with me too. I think the issue tracker is relatively healthy now, but there was definitely a point where there were a lot of proposals which were poorly justified, severely lacking detail, or just not something that we would ever consider, and the issue tracker was starting to become a sink for maintainers' energy. But perhaps issue templates are enough to mitigate that? If we have provided a template and someone has chosen to discard it and still only provide a sentence or two, it makes it a lot easier to just close an issue outright.

**Comment by garyb** [comment]
I'd be happy with trying the template for now. The fact it has a section for "Detailed description of the proposal", examples, etc. means people will have to put a little more thought into it assuming they don't just discard the template. And yeah, if they discard the template we can prompt them to fill it in properly, or close the issue if they're not prepared to do so.

**Comment by hdgarrood** [comment]
Sure, that works for me. I'll close this then. :+1:

**Pull request closed without merging**
