### PR TITLE
Move code from executables into the library

### PR DESCRIPTION
**Pull request by wuzzeb**
This should implement #1229.  There is very little new code here, it is primarily moving code and updating a few of the comments.  To recap, it moves code from psc/Make.hs and psc-bundle/Main.hs into the main library.

### CODE REVIEW

**Comment by paf31** [comment]
Looks good to me. This will make it much easier to convert Try PureScript to 0.7 as well :)

Is it possible to extract some of the similar `Make` code from `psci` and `tests` now?

**Comment by wuzzeb** [comment]
For psci/Make.hs, it looks like it was originally copied but there are a few differences.

* src/Language/PureScript/Make.hs version of getInputTimestamp uses the maximum time between the code and the foreign file.  psci/Make.hs just uses the code.  I suspect this is a bug in psci, since it doesn't check the timestamp of foreign files.

* src/Language/PureScript/Make.hs version of writeFile displays a message to the screen for the
  file that it wrote, psci/Make.hs does not.  Not sure how critical this is, could probably be removed to make the two versions the same. 

*  psci/Make.hs omits some progress messages for modules starting with $PSCI.   We could still do this by changing out the progress function inside psci/Make.hs.  That is, use the MakeActions from src/Language/PureScript/Make.hs but replace just the progress function.

For the make stuff in tests, it looks like it is different make actions so no sharing needed.

**Comment by paf31** [comment]
If it's possible to extract out the common stuff, and use a record update inside `psci`, I think that would be a big win. If it's not possible, or just a pain, we can figure it out later.

**Comment by wuzzeb** [comment]
Ok, I added a commit which makes psci use the common make code.

**Comment by paf31** [comment]
That was quick :) Thanks!

**Comment by puffnfresh** [comment]
Will hopefully clean up truffled-purescript a little :+1:

**Comment by paf31** [comment]
Looks good to me. @garyb any thoughts on this?

**Comment by garyb** [comment]
All fine by me!

**Pull request merged**
