### PR TITLE
Fix for #2244

### PR DESCRIPTION
**Pull request by LiamGoodacre**
I wanted to add a test case but I didn't know how to go about it.

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
I found two usages of `identNeedsEscaping`:

```
-- src/Language/PureScript/CodeGen/JS.hs:179:
accessorString prop | identNeedsEscaping prop = JSIndexer Nothing (JSStringLiteral Nothing prop)

-- src/Language/PureScript/Pretty/JS.hs:57:
objectPropertyToString s | identNeedsEscaping s = emit $ show s
```

These are the cases of `foo` in `obj.foo` and `{foo: x}` respectively.

**Comment by garyb** [comment]
Looks good to me :+1:

Regarding tests, we don't have a setup that lets us check the JS output at the moment.

**Comment by paf31** [comment]
Looks good! Will accessors and record updates do the right thing too now?

**Comment by LiamGoodacre** [comment]
@paf31 Ah apparently not:

```purescript
-- purescript
foo0 = {"": ""}
foo1 = foo0.""
foo2 = _.""
foo3 = foo0 {"" = ""}
```

```javascript
// javascript
var foo2 = function (v) {
    return v[""];
};
var foo0 = {
    "": ""
};
var foo1 = foo0[""];
var foo3 = (function () {
    var $6 = {};
    for (var $7 in foo0) {
        if (foo0.hasOwnProperty($7)) {
            $6[$7] = foo0[$7];
        };
    };
    $6. = ""; // <<<---- oops
    return $6;
})();
```

I will look into this tonight. 😃

**Comment by LiamGoodacre** [comment]
The accessor in record extension is now fixed:

```javascript
var foo3 = (function () {
    var $128 = {};
    for (var $129 in foo0) {
        if (foo0.hasOwnProperty($129)) {
            $128[$129] = foo0[$129];
        };
    };
    $128[""] = "";
    return $128;
})();
```

However I found more serious bug when fixing this: extending a record will re-evaluate the expression that generated the record `1 + (2 * keys)` times!!!

```purescript
-- purescript
foo4 = {"ha": ""} {"ha" = ""}
```

```javascript
// crazy javascript - notice the {ha: ""} scattered around
var foo4 = (function () {
    var $126 = {};
    for (var $127 in {
        ha: ""
    }) {
        if ({
            ha: ""
        }.hasOwnProperty($127)) {
            $126[$127] = {
                ha: ""
            }[$127];
        };
    };
    $126.ha = "";
    return $126;
})();
```

After my fix it now generates as:

```javascript
-- The expression {ha: ""} is evaluated and result stored in a fresh var
var foo4 = (function () {
    var $128 = {
        ha: ""
    };
    var $126 = {};
    for (var $127 in $128) {
        if ($128.hasOwnProperty($127)) {
            $126[$127] = $128[$127];
        };
    };
    $126.ha = "";
    return $126;
})();
```

**Comment by paf31** [comment]
Thanks very much!

**Pull request merged**
