### PR TITLE
MakeActions changes

### LINKED ISSUE #1264: Review MakeActions API
It's not clear to me how it works. Maybe we can revisit it when we implement parallel builds?

### PR DESCRIPTION
**Pull request by paf31**
@garyb This is just some minor stuff, and adding a comment, now that I understand the role of `MakeActions` better.

Resolves #1264.

### CODE REVIEW

**Comment by garyb** [comment]
:+1: Using `SupplyT` is much more sensible.

You mentioned you were working on parallel builds and that `MakeActions` ties in with that, does the current design hamper parallel builds? If so I guess we can't keep it as is and will have to specialise for different backends. If that's the case then I'm all for it, just at the time I updated this it seemed like sharing it would be viable.

**Comment by paf31** [comment]
No, it should be fine. I was planning to make slight changes like this before parallel builds, but got carried away.

**Comment by paf31** [comment]
@garyb I just pushed another change to reduce some code duplication in the test suite. Hopefully it's ok too.

**Comment by garyb** [comment]
For sure! Much better :+1:

**Pull request merged**
