### PR TITLE
Add Ordering kind with LT, EQ, GT types in Prim

### PR DESCRIPTION
**Pull request by LiamGoodacre**

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
Originally I was thinking:
1. Add TypeOrdering kind
2. Add CompareSymbol class to purescript-symbols
3. Solve CompareSymbol

However perhaps we should just do 1 and 3 together?  Otherwise we'd need to have a release in the middle, which seems unnecessary.

**Comment by LiamGoodacre** [comment]
Maybe wait for https://github.com/purescript/purescript/issues/919 instead.

**Comment by paf31** [comment]
Another option here is to use kind `*` for now, and to implement symbol comparison anyway. We can always make a breaking change in the `symbols` library when custom kinds are ready.

**Comment by LiamGoodacre** [comment]
Closed in favour of https://github.com/purescript/purescript-typelevel-prelude/pull/1

**Pull request closed without merging**
