### PR TITLE
[WIP] removes superfluous constraints.

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Since GHC 7.10 Monad is a superclass of Applicative.

Should I also check if we need Prelude.Compat anymore?

### CODE REVIEW

**Comment by paf31** [comment]
Wonderful. Does this allow us to add GHC 8 back to the CI build?

**Comment by kRITZCREEK** [comment]
It'll probably still fail. I literally just grepped for lines with `Applicative/Functor m` in them :D I haven't tried to set up GHC 8 locally, which would probably be better for finding the rest of the superfluous constraints.

**Comment by paf31** [comment]
Well, if you're feeling enthusiastic, the last CI build report from GHC 8 has a complete list of redundant constraints :smile: 

But I'll get to this soon in any case, so no worries.

**Comment by paf31** [comment]
Let's deal with GHC8 separately. Merging, thanks!

**Pull request merged**
