### PR TITLE
Fix #1336 and #1334

### LINKED ISSUE #1336: tests failing
When running the testsuite in the Stackage nightly build:

```
Test suite tests: RUNNING...
tests: npm: callProcess: runInteractiveProcess: exec: does not exist (No such file or directory)
Test suite tests: FAIL
Test suite logged to: /home/stackage/work/logs/nightly/purescript-0.7.2.0/test-run.out
Test suite psci-tests: RUNNING...
^MCases: 37  Tried: 0  Errors: 0  Failures: 0^MCases: 37  Tried: 1  Errors: 0  Failures: 0^MCases: 37  Tried: 2  Errors: 0  Failures: 0^MCases: 37  Tried: 3  Errors: 0  Failures: 0^MCases: 37  Tried: 4  Errors: 0  Failures: 0^MCases: 37  Tried: 5  Errors: 0  Failures: 0^MCases: 37  Tried: 6  Errors: 0  Failures: 0^MCases: 37  Tried: 7  Errors: 0  Failures: 0^MCases: 37  Tried: 8  Errors: 0  Failures: 0^MCases: 37  Tried: 9  Errors: 0  Failures: 0^MCases: 37  Tried: 10  Errors: 0  Failures: 0^M                                            ^M### Failure in: completionTests:10
expected: [":l psci/tests/data/Sample.purs"]
 but got: []
^MCases: 37  Tried: 11  Errors: 0  Failures: 1^M                                            ^M### Failure in: completionTests:11
expected: [":module psci/tests/data/Sample.purs"]
 but got: []
^MCases: 37  Tried: 12  Errors: 0  Failures: 2^MCases: 37  Tried: 13  Errors: 0  Failures: 2^MCases: 37  Tried: 14  Errors: 0  Failures: 2^MCases: 37  Tried: 15  Errors: 0  Failures: 2^MCases: 37  Tried: 16  Errors: 0  Failures: 2^MCases: 37  Tried: 17  Errors: 0  Failures: 2^MCases: 37  Tried: 18  Errors: 0  Failures: 2^MCases: 37  Tried: 19  Errors: 0  Failures: 2^MCases: 37  Tried: 20  Errors: 0  Failures: 2^MCases: 37  Tried: 21  Errors: 0  Failures: 2^MCases: 37  Tried: 22  Errors: 0  Failures: 2^MCases: 37  Tried: 23  Errors: 0  Failures: 2^MCases: 37  Tried: 24  Errors: 0  Failures: 2^MCases: 37  Tried: 25  Errors: 0  Failures: 2^MCases: 37  Tried: 26  Errors: 0  Failures: 2^MCases: 37  Tried: 27  Errors: 0  Failures: 2^MCases: 37  Tried: 28  Errors: 0  Failures: 2^MCases: 37  Tried: 29  Errors: 0  Failures: 2^MCases: 37  Tried: 30  Errors: 0  Failures: 2^MCases: 37  Tried: 31  Errors: 0  Failures: 2^MCases: 37  Tried: 32  Errors: 0  Failures: 2^MCases: 37  Tried: 33  Errors: 0  Failures: 2^MCases: 37  Tried: 34  Errors: 0  Failures: 2^MCases: 37  Tried: 35  Errors: 0  Failures: 2^MCases: 37  Tried: 36  Errors: 0  Failures: 2^M                                            ^MCases: 37  Tried: 37  Errors: 0  Failures: 2
Test suite psci-tests: FAIL
```

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by paf31** [comment]
@hdgarrood Could you please review this?

**Comment by hdgarrood** [comment]
:+1:

**Comment by hdgarrood** [comment]
Oh wait - we should amend CONTRIBUTING because this means we no longer need bower on the PATH.

**Comment by paf31** [comment]
:+1: Thanks!

**Pull request merged**
