### PR TITLE
Row TypesDoNotUnify, don't assume unique labels, fix #2820

### LINKED ISSUE #2820: Duplicate label error partly wrong
The following code:
```
foreign import data Foo :: Effect

test :: forall e. Eff (foo :: Foo, foo :: Foo | e) Unit -> Eff (foo :: Foo | e) Unit
test f = f
```

Produces an error which appears to mention a wrong type in the initial part (same side twice):

```
  Could not match type
  
    ( foo :: Foo
    , foo :: Foo
    | e0
    )
  
  with type
  
    ( foo :: Foo
    , foo :: Foo
    | e0
    )
  
  while trying to match type Eff
                               ( foo :: Foo
                               , foo :: Foo
                               | e0
                               )
    with type Eff
                ( foo :: Foo
                | e0
                )
  while checking that expression f
    has type Eff
               ( foo :: Foo
               | e0
               )
               Unit
  in value declaration test
  
  where e0 is a rigid type variable
          bound at line 10, column 1 - line 10, column 11
```

### PR DESCRIPTION
**Pull request by thoradam**
I'm a novice so I might be overlooking something, but this fixes #2820 and other examples I can come up with seem to work?

### CODE REVIEW

**Comment by paf31** [comment]
This certainly looks better, could you please post some example output? Thanks!

**Comment by thoradam** [comment]
#### Example from #2820 
```
module Example1 where
import Prelude (Unit)
import Control.Monad.Eff (kind Effect, Eff)
foreign import data Foo :: Effect
test :: forall e. Eff (foo :: Foo, foo :: Foo | e) Unit -> Eff (foo :: Foo | e) Unit
test f = f
```
#### Before
```
  Could not match type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )

  with type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )
```
#### After
```
  Could not match type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )

  with type

    ( foo :: Foo
    | e0
    )
```
#### #2820 reversed
```
module Example1 where
import Prelude (Unit)
import Control.Monad.Eff (kind Effect, Eff)
foreign import data Foo :: Effect
test :: forall e. Eff (foo :: Foo | e) Unit -> Eff (foo :: Foo, foo :: Foo | e) Unit
test f = f
```
#### Before
```
  Could not match type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )

  with type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )
```
#### After
```
  Could not match type

    ( foo :: Foo
    | e0
    )

  with type

    ( foo :: Foo
    , foo :: Foo
    | e0
    )
```
#### Very example
```
module Main where
import Prelude (Unit)
import Control.Monad.Eff (kind Effect, Eff)
foreign import data A :: Effect
foreign import data B :: Effect
foreign import data C :: Effect
foreign import data D :: Effect
foreign import data Z :: Effect
test :: forall e. Eff (a :: Z, b :: A, a :: B | e) Unit -> Eff (d :: C, a :: Z, c :: D | e) Unit
test f = f
```
#### Before
```
  Could not match type

    ( b :: A
    , a :: Z
    , a :: B
    | e0
    
  with type

    ( c :: D
    , d :: C
    , a :: Z
    , a :: Z
    | e0
    )
```
#### After
```
  Could not match type

    ( a :: B
    , b :: A
    , a :: Z
    | e0
    )

  with type

    ( c :: D
    , d :: C
    , a :: Z
    | e0
    )
```
#### No change, same sort example
```
module Main where
import Prelude (Unit)
import Control.Monad.Eff (kind Effect, Eff)
foreign import data A :: Effect
foreign import data B :: Effect
foreign import data C :: Effect
foreign import data Y :: Effect
foreign import data Z :: Effect
test :: forall e. Eff (b :: Z, a :: Y | e) Unit -> Eff (b :: Z, a :: Y, c :: C | e) Unit
test f = f
```
#### Before
```
  Could not match type

    ( a :: Y
    , b :: Z
    | e0
    )

  with type

    ( c :: C
    , a :: Y
    , b :: Z
    | e0
    )
```
#### After
```
  Could not match type

    ( a :: Y
    , b :: Z
    | e0
    )

  with type

    ( c :: C
    , a :: Y
    , b :: Z
    | e0
    )
```

**Comment by paf31** [comment]
Looks good. Can you please resolve the conflicts and I'll merge this later.

**Comment by thoradam** [comment]
Resolved ^_^

**Pull request merged**
