### PR TITLE
[purs ide] extract namespace adt

### PR DESCRIPTION
**Pull request by kRITZCREEK**
This is just a minor refactoring in preparation for #2792.

### CODE REVIEW

**Comment by paf31** [comment]
👍 LGTM

**Comment by hdgarrood** [comment]
Would it make sense to unify this with the equivalent type in Language.PureScript.Docs?

**Comment by kRITZCREEK** [comment]
@hdgarrood but where would the type live? I guess in one of the `AST` modules?

**Comment by hdgarrood** [comment]
I think Names might be more appropriate? Is the Ide code not able to depend on Docs at the moment though?

**Comment by kRITZCREEK** [comment]
I think I'll leave this PR as is for now. I think it totally makes sense to have this Enum somewhere in the compiler, but it's probably not only Docs and Ide that would use it.

**Comment by kRITZCREEK** [comment]
```
[ 2 of 14] Compiling Version          ( app\Version.hs, .stack-work\dist\ca59d0ab\build\purs\purs-tmp\Version.o )
Segmentation fault/access violation in generated code
```

Doesn't sound good, but seems to be related to getting the git revision on the AppVeyor instance? Definitely isn't caused by this PR.

**Comment by hdgarrood** [comment]
Oh dear :/ Might be worth trying to repro with a local Windows VM, and perhaps seeing what happens with GHC HEAD too? I found this patch which was recently merged https://ghc.haskell.org/trac/ghc/ticket/13108#no1 which slightly improves this error message we're seeing.

**Comment by kRITZCREEK** [comment]
The tests works just fine on my local Windows machine. Must be something AppVeyor specific.

**Comment by hdgarrood** [comment]
I suppose there's a possibility it's due to us running `stack` slightly differently locally and on AppVeyor? Eg, does it make a difference if you run with `--jobs=1` like CI does?

**Comment by kRITZCREEK** [comment]
Still doesn't break anything on my machine. I'll just merge this PR since it doesn't cause the failures and I'll open a separate issue for the CI failures?

**Comment by hdgarrood** [comment]
Sounds good to me.

**Pull request merged**
