### PR TITLE
Fix source links for re-exports

### PR DESCRIPTION
**Pull request by felixSchl**
Fixes purescript/pursuit#304

Refer to purescript/pursuit#319

### CODE REVIEW

**Comment by hdgarrood** [comment]
Thanks for looking at this! I'm not quite sure about what approach is the best though, I need to have a think.

**Comment by hdgarrood** [comment]
Ok, this looks good - if you could just fix the warning which is causing CI to fail then I think this is good to merge. Thanks!

**Comment by hdgarrood** [comment]
Does anyone else want to look at this or should I just go ahead and merge?

**Comment by paf31** [comment]
@hdgarrood I haven't had a chance to review yet, but please merge if you're happy (in general).

**Comment by hdgarrood** [comment]
Ok :)

@felixschl thanks very much!

**Pull request merged**
