### PR TITLE
Pretty-print suggested types differently

### LINKED ISSUE #1793: Types generated by wildcards and typed holes should work when substituted
note sure how to name or describe this problem, but there is a concise way to reproduce it:

http://stackoverflow.com/questions/34593686/purescript-type-signature-fails-to-compile-code-works-fine-without-suggested-s

don't think these are related, but they are the closest (open) matches i found: #1110, #1579.

### PR DESCRIPTION
**Pull request by paf31**
Fixes #1793

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
` where a0 is a rigid type variable` still refers to the old name.

**Comment by paf31** [comment]
Thanks. Now only the suggestion is changed, the type shown to the user still uses the numbered skolems and named unification variables.

**Comment by paf31** [comment]
@kRITZCREEK Do you think this looks ok now?

**Comment by kRITZCREEK** [comment]
Yes :+1:

Am 11.10.2016 4:40 vorm. schrieb "Phil Freeman" <notifications@github.com>:

**Pull request merged**
