### PR TITLE
Fix #365

### LINKED ISSUE #365: Cannot fully eta reduce in instances
I noticed this while working on a collections library.

For example: https://github.com/joneshf/purescript-collections/blob/master/src/Data/Collection.purs#L92 has to have at least one argument. If not, it will generate something like

```javascript
var foldableArray = function (_) {
    return {
        "__superclasses": {}, 
        size: fold(foldableArray({}))(_ps.Prelude["const"](_ps.Prelude["+"](_ps.Prelude.numNumber({}))(1)))(0)
    };
};
```

which just recurses down itself when it attempts to construct the object, since `size` doesn't close over the instance it is defining.

### PR DESCRIPTION
**Pull request by paf31**
@garyb Could you please review?

### CODE REVIEW

**Comment by paf31** [comment]
`test-everything` passes (as much as before)

**Comment by garyb** [comment]
What does this do, disallow the eta-reduced implementations?

**Comment by paf31** [comment]
Yep exactly. The issue was in strongly connected components of size 1. At some point, they were treated differently, but now they're handled using the defined/undefined code in the typechecker.

**Comment by garyb** [comment]
It's unfortunate we can't eta convert these automatically, but seems like a reasonable fix to me. :+1:

**Comment by paf31** [comment]
I'm not sure. I generally think minimal munging of user code by the compiler is a good thing. You can make a case here because the user doesn't see how the code gets desugared, but I think predictability of the code gen is more important, honestly.

**Pull request merged**
