### PR TITLE
Revise Num class

### LINKED ISSUE #868: Revise Num class
This could become a huge discussion, but I'll say up front - I don't want to do anything drastic to `Num` all at once.

A very refined type class hierarchy _is_ possible, but I think would be better contained in libraries.

That said, I'm pretty sure `Number` is the only instance of `Num` right now (no `Int` yet, etc.) and I don't think any code uses `Num` in the abstract, so we can change a few things, if we're careful not to break the optimizer.

Here is the current proposal (by @jdegoes):

```purescript
-- addition and multiplication
class Semiring a where 
  (+)   :: a -> a -> a
  zero  :: a
  (*)   :: a -> a -> a
  one   :: a

-- addition, multiplication, and subtraction
class (Semiring a) <= Ring a where
  (-) :: a -> a -> a

negate :: forall a. (Ring a) => a -> a
negate a = zero - a

-- ring with division (possibly non-commutative field)
class (Ring a) <= DivisionRing a where
  (/) :: a -> a -> a

-- definitely commutative field
class (DivisionRing a) <= Num a
```

and in `purescript-monoids`:

```purescript
-- additive monoid
newtype Additive a = Additive a

-- multiplicative monoid
newtype Multiplicative a = Multiplicative a

instance additiveSemiRing :: (SemiRing a) => Semigroup (Additive a) where 
  (<>) (Additive a) (Additive b) = Additive (a + b)

instance additiveMonoid :: (SemiRing a) => Monoid (Additive a) where
  mempty = Additive zero

-- todo: Additive functor, applicative, etc.

instance multiplicativeSemiRing :: (SemiRing a) => Semigroup (Multiplicative a) where 
  (<>) (Multiplicative a) (Multiplicative b) = Multiplicative (a + b)

instance multiplicativeMonoid :: (SemiRing a) => Monoid (Multiplicative a) where
  mempty = Multiplicative one

-- todo: Multiplicative functor, applicative, etc. 
```

### PR DESCRIPTION
**Pull request by garyb**
Resolves #868 

`(%)` is missing at the moment, so this isn't ready to merge yet.

### CODE REVIEW

**Comment by jdegoes** [comment]
Ah, forgot about modulo.

I'd be interested in feedback on this slight tweak to the hierarchy:

```purescript
-- definition: a / b * b + (a % b) = a
class (Ring a) <= ModuloRing a where
  (%) :: a -> a -> a
  (/) :: a -> a -> a

-- definition: a % b = zero
class (ModuloRing a) <= DivisionRing a
```

The idea here is that some types support modulo ring but not division ring: for example, `Int`, and `Polynomial`. Whereas, because division rings are capable of producing true multiplicative inverses for every value, the quantity `a / b * b` is definitionally equal to `a`, so `a % b` is `zero` for all `b`.

**Comment by paf31** [comment]
Looks great. The tests don't really test the inlining stuff, so I assume that's all working. Also, can you please rerun `updateDocs.sh`.

Other than that, :ship: :+1:

**Comment by garyb** [comment]
How does this look?

Inlining seems to be ok, tested with:
``` purescript
module Test where

import Debug.Trace

main = do
  print (-(1 + 2 / 3 * 4))
  print (1 + 2 - 3)
  print (1 + 2 / 3)
  print (one + 2)
  print (2 * zero)
  print (negate (2 * zero))
  print (-1)
  print (negate 1)
  print (1 * 2)
  print (4 % 3)
  print (4 `mod` 3)
```

Compiles to:
``` js
var PS = PS || {};
PS.Test = (function () {
    "use strict";
    var Prelude = PS.Prelude;
    var Debug_Trace = PS.Debug_Trace;
    var Control_Monad_Eff = PS.Control_Monad_Eff;
    var main = function __do() {
        Debug_Trace.print(Prelude.showNumber)(-(1 + (2 / 3) * 4))();
        Debug_Trace.print(Prelude.showNumber)((1 + 2) - 3)();
        Debug_Trace.print(Prelude.showNumber)(1 + 2 / 3)();
        Debug_Trace.print(Prelude.showNumber)(1 + 2)();
        Debug_Trace.print(Prelude.showNumber)(2 * 0)();
        Debug_Trace.print(Prelude.showNumber)(-(2 * 0))();
        Debug_Trace.print(Prelude.showNumber)(-1)();
        Debug_Trace.print(Prelude.showNumber)(-1)();
        Debug_Trace.print(Prelude.showNumber)(1 * 2)();
        Debug_Trace.print(Prelude.showNumber)(4 % 3)();
        return Debug_Trace.print(Prelude.showNumber)(Prelude.mod(Prelude.moduloRingNumber)(4)(3))();

    };
    return {
        main: main
    };
})();
```

I could add a case to automatically inline ```4 `mod` 3``` as `0`, but is it worth it?

**Comment by garyb** [comment]
Ah yes the docs, will do!

**Comment by paf31** [comment]
Looks great. I don't think inlining `mod` is necessary really.

**Comment by jdegoes** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by garyb** [comment]
I'll let the tests run anyway and then will merge. :raised_hands:

**Comment by paf31** [comment]
Also, did you run `test-everything`? I don't see any potential for breakage, but probably worth running anyway.

**Comment by garyb** [comment]
Yep, it's still happy.

One thing I noticed while working on this, I used `pursuit` to check for definitions of `one` and `zero` - they show up in `Data.Monoid`, however that's not the "standard" monoid, it's from @joneshf's `purescript-algebra` - is it possible to add a URL for where things come from in `pursuit`?

**Pull request merged**
