### PR TITLE
Int literals #1061

### PR DESCRIPTION
**Pull request by paf31**
Work in progress, tests currently broken.

/cc @garyb

### CODE REVIEW

**Comment by garyb** [comment]
So far so :+1:

**Comment by paf31** [comment]
The choice `1 :: Int` and `1.0 :: Number` is nice from a type checker POV, but it's certainly not normal, and I wonder if it's going to lead to confusing errors. Things like `1 does not have type Number` crop up, which might confuse a beginner. We can always document this stuff, but I think a lot of people will expect `1 :: Number` to work. But then, I don't really want to go the overloaded literals route either.

**Comment by garyb** [comment]
That's why I was asking about the behaviour of it yesterday... I think I still do prefer this stricter option though. We can always spend some time ensuring the error is helpful though, adding something like `did you mean to use the Number 1.0 rather than the Int 1?`

**Comment by paf31** [comment]
Improving errors sounds like the way to go.

**Comment by garyb** [comment]
Or if we were going to allow coercion, at least make it a warning.

**Comment by paf31** [comment]
Coercion without overloaded literals is going to be a nightmare from a typechecking perspective.

**Comment by andyarvanitis** [comment]
Would allowing implicit integral literals to `Number` conversion (but not the other way around) be ok?

**Comment by garyb** [comment]
I guess this whole thing comes down to: What's more inconvenient? Using `fromNumber` a lot, or having to add `.0` to floats sometimes. Either one is going to be a slight hurdle for a beginner, and add `.0` is the less gross option to me at least. :smile:

**Comment by natefaubion** [comment]
Could we at least allow '1.'. I think this is fairly common in languages other than JS, eg Python:

```
>>> type(3)
<type 'int'>
>>> type(3.)
<type 'float'>
```

**Comment by paf31** [comment]
@natefaubion Sure, if we can get the lexer to recognize it unambiguously.

**Comment by paf31** [comment]
@andyarvanitis I'd rather avoid any sort of subtyping rules, since we risk losing principal types.

**Comment by joneshf** [comment]
I'm not sure if it's been discussed before, but what about something like what haskell does with the `IsString` class:
http://hackage.haskell.org/package/base-4.8.0.0/docs/Data-String.html#t:IsString except for numeric literals (akin to `fromInteger` from `Num` or `fromRational` from `Fractional` except not muddled with other functions)?

Though, I think it'd fall prey to the same lack of constraint inference that we have now, so maybe that's not an immediate thing.

**Comment by paf31** [comment]
> Though, I think it'd fall prey to the same lack of constraint inference that we have now

That's the only reason I want to avoid this for now, but we could move in that direction.

**Comment by paf31** [comment]
@garyb @andyarvanitis @michaelficarra Could you please review?

**Comment by paf31** [comment]
CI will probably fail due to core-tests.

**Comment by garyb** [comment]
Can we not use `Int` or `Char` as a type in the tests then?

**Comment by paf31** [comment]
We can, but I need to update the test prelude to include `Semiring` etc. for `Int` first. This was just a quick pass to get stuff working. I added a new `IntAndChar` test though.

**Comment by garyb** [comment]
Yeah, I figured that about the `Prelude`, I just wondered as I didn't see the `Int` or `Char` type used in the test, although the literals are.

:+1:

**Comment by andyarvanitis** [comment]
Looks good to me. It gives backends control over how to translate the `CharLiteral` itself (rather than, say, making it a `StringLiteral` upstream), so I'm happy!  :+1:

**Pull request merged**
