### PR TITLE
Fix #922

### LINKED ISSUE #922: Instance Resolution Problem
I'm not exactly sure what's happening, but there appears to be some general problem in Purescript's type class instance resolution. In addition to https://github.com/purescript/purescript-transformers/issues/28, I have the following test case:

```purescript
module Foo where

import Data.Either
import Control.Monad.Error.Class
import Debug.Trace

foo :: forall m. (MonadError Unit m, Monad m) => m Number
foo = return 1

foo' :: Either Unit Number
foo' = foo

main = do
  case foo of
    (Right a) -> print a
```

It generates the error:
```
Attempted to unify a constrained type (Control.Monad.Error.Class.MonadError Prelude.Unit u11, Pr
elude.Monad u11) => u11 Prim.Number with another type.
```

Swapping the `case foo of` to `case foo' of` resolves the error. Both versions work in Haskell.

### PR DESCRIPTION
**Pull request by paf31**
Another stab at #922. I'd like to be able to test with `core-tests` before merging this since it's in a pretty critical part of the type checker.

### CODE REVIEW

**Comment by paf31** [comment]
Ok, `core-tests` seems to pass. Not sure why I backed out the previous commit for this, maybe something else was failing to build. Could you try `slamdata` when you get chance please @garyb?

**Comment by garyb** [comment]
Cool! I'll have to back port it to 0.7.2 to test, but will definitely check it out tomorrow.

**Comment by paf31** [comment]
>  I'll have to back port it to 0.7.2 to test

Maybe a good use case for https://github.com/ThomasCrvsr/psvm-js ?

**Comment by garyb** [comment]
:shipit: :+1: - tested on slamdata now.

**Comment by paf31** [comment]
Thanks!

**Comment by garyb** [comment]
`purescript-freet` doesn't compile after this :cry:

**Comment by garyb** [comment]
The error:

```
Error found:
Error in module Control.Monad.Free.Trans:
Error in binding group bimapFreeT:
Error checking that type
  f0 _0 -> g0 _0
subsumes type
  _1 a0 -> _2 a0
Error checking that type
  _1 a0
subsumes type
  f0 _0
Error at D:\Home\GitHub\purescript-freet\src\Control\Monad\Free\Trans.purs line 98, column 88 - line 98, column 110:
  Cannot unify type
    a1
  with type
    a0
See https://github.com/purescript/purescript/wiki/Error-Code-TypesDoNotUnify for more information, or to contribute content related to this error.
```

**Pull request merged**
