### PR TITLE
fixes #2434 and #2438: PureScript chars must be UTF-16 code units

### LINKED ISSUE #2434: Treatment of surrogate pairs in string literals
After looking at #2418 I realised that we allow invalid surrogate pairs in string literals. For example:

```purescript
module Main where

import Prelude
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Console (CONSOLE, log)

main :: forall e. Eff (console :: CONSOLE | e) Unit
main = do
  log "\xDFFF\xD800"
```

Produces the following:

```
��
```

That is, two copies of U+FFFD, the unicode replacement character. At the moment, valid surrogate pairs come out how you would expect them to (although I expect backends other than JS will handle this less gracefully).

I think we should almost certainly throw an error in the parser if a string literal contains an invalid surrogate pair, and also consider throwing an error in the parser if a string literal contains any escape sequence for a character in the range reserved for surrogate pairs i.e. U+D800 to U+DFFF, i.e. we should also consider throwing errors for *valid* surrogate pairs.

Ideally I think string literals in PureScript source code would be represented in the compiler as the precise values they refer to, e.g. if you wrote `"\x1F4A1"` in a PureScript source file, the compiler would represent that internally as that actual code point (using some encoding which I don't think is relevant to this discussion). Then whichever backend is being used would be responsible for writing that value out as a string literal which would be interpreted correctly by whatever language implementation will end up reading it (i.e. usually JS but potentially many others).

The reason I would vote for erroring even on valid surrogate pairs is that allowing them suggests that strings are always going to be encoded as UTF-16 at runtime, which is true for JS, but probably not for other backends. It also makes the implementation of the lexer simpler. I also think it makes more sense to put any awkward code for handling surrogate pairs in the JS code generator (as opposed to the lexer), as dealing with this kind of encoding issue in generated code will be specific to the backend you're targeting.

Relevant background info from [Wikipedia](https://en.wikipedia.org/wiki/UTF-16):

> ### U+D800 to U+DFFF
> The Unicode standard permanently reserves these code point values for UTF-16 encoding of the high and low surrogates, and they will never be assigned a character, so there should be no reason to encode them. The official Unicode standard says that no UTF forms, including UTF-16, can encode these code points.
>
> However UCS-2, UTF-8, and UTF-32 can encode these code points in trivial and obvious ways, and large amounts of software does so even though the standard states that such arrangements should be treated as encoding errors. It is possible to unambiguously encode them in UTF-16 by using a code unit equal to the code point, as long as no sequence of two code units can be interpreted as a legal surrogate pair (that is, as long as a high surrogate is never followed by a low surrogate). The majority of UTF-16 encoder and decoder implementations translate between encodings as though this were the case[citation needed] and Windows allows such sequences in filenames.

/cc @kRITZCREEK @michaelficarra @andyarvanitis

### PR DESCRIPTION
**Pull request by michaelficarra**
Fixes #2434 and #2438.

### CODE REVIEW

**Comment by michaelficarra** [comment]
*Bonus:* I thought I would have to make some changes to `purescript-strings`, but it looks like the `Data.Char` functions [already wouldn't have worked](https://github.com/purescript/purescript-strings/blob/94d6526ca7c692cc6917225f68a7bcabeebf9555/src/Data/Char.js#L7-L9) for code points above `U+FFFF` and the `Data.String` functions were already treating strings as sequences of UTF-16 code units. 😎

**Comment by hdgarrood** [comment]
I think we might also want to test that we aren't falling victim to `text`'s replacement of invalid scalar values; I think adding the following examples/passing/StringEscapes.purs to ought to do that:

```purescript
replacement = '\0xFFFD'
notReplacing = replacement /= highSurrogate

main = do
  [...]
  assert notReplacing
```

Unless I'm missing something and this is already covered. See the "Acceptable data" paragraph in [the Data.Text documentation](https://hackage.haskell.org/package/text-1.2.2.1/docs/Data-Text.html) for what I mean by 'replacement of invalid scalar values'.

I realise the suggestion I'm about to make would make this change significantly bigger and more awkward, but have we considered introducing a separate type for PureScript strings (I think @kRITZCREEK suggested this to me initially)? Possibly a newtype over `[Int]` or maybe `Vector Int`, and maybe also with smart constructors to ensure that every element of the list is between 0 and 0xFFFF?

**Comment by hdgarrood** [comment]
It might additionally be nice to use [`assert'`](https://pursuit.purescript.org/packages/purescript-assert/2.0.0/docs/Test.Assert#v:assert%27) in the tests, i.e. the version that allows you to specify an error message, so that it's clearer which case has been broken if we later break one of these cases.

**Comment by michaelficarra** [comment]
CI is failing due to what appears to be an unrelated issue introduced by #2418. I'll look into it.

@hdgarrood I like your suggestions. I'll use `assert'` and add that test, but I'll wait to hear from others before switching internal string representation from `Data.Text` to `Vector Word16`.

**Comment by kRITZCREEK** [comment]
This is how far I got: 

https://github.com/kRITZCREEK/purescript/commit/b1ba4727f8b581239f4b4d3e7d6b481d8bb7305a

It's a bit of a messy change so I'd prefer if we could fix the regressions introduced by the `Text` PR with the current PR and then figure out a good `PSString` solution together. `Vector Word16` sounds about right but I think we want to give a "stringy" API on top and hide it behind smart constructors.

**Comment by paf31** [comment]
Any idea why `StringEscapes.purs` is failing here?

**Comment by hdgarrood** [comment]
Yeah, this the problem I anticipated earlier in the thread which led me to suggest adding that extra test. `Text` is not going to work for representing string literals in the compiler, because of `Data.Text.pack`'s replacement of invalid UTF-16 sequences. Since we're going to have to change the type for string literals to something else everywhere it's used anyway, I think we should go straight ahead with having a dedicated `PSString` type, like in @kRITZCREEK's gist. But may I suggest the following instead:

```haskell
module Data.PSString (PSString, fromString, unwrap) where

import Data.Vector.Unboxed as V

-- |
-- Strings in PureScript are sequences of UTF-16 code units, which do not
-- necessarily represent UTF-16 encoded text. For example, it is permissible
-- for a string to contain *lone surrogates,* i.e. characters in the range
-- 0xD800 - 0xDFFF which do not appear as a part of a surrogate pair.
newtype PSString = PSString (Vector Word16)
  deriving (Eq, Ord, Show)

fromString :: String -> PSString
fromString =
  foldMap (encodeSurrogates . fromEnum)
  >>> map (fromIntegral :: Int -> Word16)
  >>> V.fromList
  >>> PSString
  where
  encodeSurrogates ch
    | ch > 0xFFFF = [highSurrogate, lowSurrogate]
                    where highSurrogate = [...]
    | otherwise = [ch]

unwrap :: PSString -> [Word16] -- this is easier to deal with than Vector
unwrap (PSString str) = V.toList str
```

Then, the rest happens in the (backend-specific) code generator. For JS I think it would be:

```haskell
string :: PSString -> Text
string str = "\"" <> go str <> "\""
  where
  go = PSString.unwrap >>> foldMap encodeCodeUnit
```

and `encodeCodeUnit :: Word16 -> Text` is like the `encodeChar` in `Language.PureScript.Pretty.JS` except with the `fromEnum c > 0xFFFF` case removed.

**Comment by paf31** [comment]
What's the status of this now? Is it simple enough to fix that we could include it in 0.10.3?

**Comment by michaelficarra** [comment]
I am going to implement @hdgarrood's suggestion in the next few days, which should fix the remaining failing test case. It's pretty simple.

**Comment by michaelficarra** [comment]
@paf31 I've disabled the test that exercised `Text`'s replacement of lone surrogates with the Unicode replacement character. This PR should now pass CI and still be a strict improvement on what's currently in `master`. I'll follow up this PR with another which adds the `PSString` type, but for now this will allow you to go ahead and make a release.

**Comment by paf31** [comment]
Great, thanks!

**Comment by michaelficarra** [comment]
Alright, CI passed. :relieved:

**Comment by paf31** [comment]
Thanks! Could you please provide a summary for the release notes if you get a minute?

**Comment by michaelficarra** [comment]
@paf31 

* Fixed #2434: moved the expansion of astral code points to UTF-16 surrogate pairs from the JS code generator to the parser
* Fixed #2438: allow astral code points in record literal keys

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
