### PR TITLE
Handle TypeLevelString when checking orphans

### LINKED ISSUE #2378: Error "Invalid type in instance in checkOrphanInstance"
I get this error when instances include type-level strings.

### PR DESCRIPTION
**Pull request by joneshf**
Fixes #2378

### CODE REVIEW

**Comment by joneshf** [comment]
I'm not sure why those two builds failed on travis. I ran both `BUILD_TYPE=sdist COVERAGE=true stack test` and `BUILD_TYPE=sdist stack test`, and the tests pass in both cases. Is there some other state I'm missing here?

**Comment by paf31** [comment]
Hmm, odd. Thanks for the fix, it looks good.

CI says

```
1) Failing examples '2378.purs' should fail with 'OrphanInstance'
       Expected these errors: ["OrphanInstance"], but got these: ["UnknownName"]
```

but I'm not sure why.

**Comment by kRITZCREEK** [comment]
it's because `examples/failing/2378/Lib.purs` is not matched by the wildcards in `.cabal`

**Comment by joneshf** [comment]
Strange. Do you know why it worked for the other builds? In anycase, I'll add the glob and push up.

Would it make sense to have `examples/failing/**/*.purs` instead?

**Comment by garyb** [comment]
Annoyingly globs like that don't work for `extra-source-files` - it only allows filename wildcards.

**Comment by kRITZCREEK** [comment]
@joneshf the dist builds package the compiler like Cabal would before uploading it to hackage. This only grabs the files specified in the cabal file. We then unpack the distribution into a fresh directory and run the build in there. This then misses the files that were present before from cloning the repo and fails.

**Comment by joneshf** [comment]
Ah, makes sense!

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
