### PR TITLE
Allow operators shadowed by variables of the same name as the alias

### LINKED ISSUE #2803: Can't use an operator shadowed by a variable of the same name as the aliasee
```purescript
f :: Int -> Int -> Int
f = (+)

infixl 6 f as %

g :: Int -> Int -> Int
g a b = let f = (-) in a % b
```

Should be functionally equivalent to:

```purescript
f :: Int -> Int -> Int
f = (+)

infixl 6 f as %

g :: Int -> Int -> Int
g = f
```

Instead, I get the error:

<pre>  Value f is undefined.

while inferring the type of f
in value declaration g</pre>

### PR DESCRIPTION
**Pull request by LightAndLight**
Fixes #2803 
Fix transcript: https://gist.github.com/LightAndLight/67168114153cb3519c50185f3149b56c

The fix feels a bit heavy-handed, I didn't see any other way around it. I'll sleep on it.

Open to suggestions.

### CODE REVIEW

**Comment by paf31** [comment]
@garyb Do you think this is good to merge?

**Comment by garyb** [comment]
Intriguing bug! The fix seems pretty reasonable to me. Perhaps another alternative that would work is to use `Either Ident Ident` instead where one side is local defs and the other is top-level. That would remove some possibilities, since the only qualification we're interested in is that of the current module anyway?

**Comment by kRITZCREEK** [comment]
Could we circumvent this problem by resolving names before desugaring operators?

**Comment by kRITZCREEK** [comment]
Fixed in #3320

**Pull request closed without merging**
