### PR TITLE
Bump to 0.7.2

### PR DESCRIPTION
**Pull request by garyb**
Doing it this way as I'll draft some release notes here too for when we're ready to publish.

### CODE REVIEW

**Comment by garyb** [comment]
## Bug fixes

- Fixed haddock for the Language.PureScript.Bundle module #1262 (@wuzzeb)
- Some erroneous error positions were fixed for kind and missing instance errors #1086 (@garyb)
- The number of warnings printed for exhaustivity checks was limited to 5 #1281 (@nicodelpiano)
- Home directory is checked for `.psci` file _after_ the current working directory #883 (@mjgpy3)
- Line numbers now show for shadowed name warnings #1165 (@nicodelpiano)
- Cabal file was fixed for Nix packaging #1302 (@MasseGuillaume)
- Kind query for types defined in psci now works #1235 (@mjgpy3)
- Boolean operations are now being inlined again #1312 (@garyb)
- Int operations are now being inlined again #1330 (@garyb)
- "Writing..." and "Compiling..." messages are no-longer printed in `psci` #1276 (@paf31)

## Enhancements

- Exhaustivity checker was extended to report errors about redundant cases #1289 (@nicodelpiano)
- Improved triggering of suggestion for errors about using `(<<<)` instead of `(.)` #1284 (@mjgpy3)
- Only show the module name rather than the filename for pattern errors #1296 (@nicodelpiano)
- Error reporting in `psc-bundle` was improved #1307 (@hdgarrood) 
- `psc-publish` code is now part of the library module #1304 (@hdgarrood)
- `--version` and `--help` options were added to `psc-publish` #1300 (@garyb)
- `--dry-run` option was added to `psc-publish` #1308 (@hdgarood)
- `psc-publish` now requires a clean working tree #1306 (@hdgarood)
- `psc-publish` can now find `bower` on Windows machines #1317 (@hdgarood)
- `psc-publish` now uses OS-specific path delimiters to fix another bug on Windows #1326 (@hdgarood)
- Error list heading was made emacs-friendly #1327 (@epost)

**Comment by garyb** [comment]
That covers every PR we merged aside from the test-related ones as I figured that's externally invisible (thanks though @hdgarrood!)

**Comment by paf31** [comment]
Thanks for putting this together :)

**Comment by garyb** [comment]
No problem!

**Comment by hdgarrood** [comment]
:+1: I agree, I don't think the test stuff should go into the release notes either.

**Pull request merged**
