### PR TITLE
Update websocket host in psci interactive

### PR DESCRIPTION
**Pull request by seungha-kim**
host 0.0.0.0 do not work on Windows

Some discussion on this topic : https://github.com/middleman/middleman/issues/1011

### CODE REVIEW

**Comment by paf31** [comment]
> do not work on Windows

Do you mean in IE?

**Comment by seungha-kim** [comment]
Sorry to omit that! I tested on Chrome and Firefox.
image
image

**Comment by seungha-kim** [comment]
Actually I ran your recent purescript-graphics-viz example on my Windows and Mac machines, and it worked well on Mac.

Messages after this commit applied:

Chrome
image

Firefox
image

Edge
image

IE11 (Object doesn't support this action -> Web Audio API) 
image

Last time I ran the example it worked well on Chrome, but now it does not show anything...
Anyway websocket seems connected.

**Comment by paf31** [comment]
Sounds good, thanks. Could you please just fix `contributors.md`, and I'll merge this.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
