### PR TITLE
Fix #1479, encode .js files as UTF8.

### LINKED ISSUE #1479: Regression related to unicode identifiers
Compiler generates string literals with octal escapes when record labels contain international characters and at the same time are not valid javascript identifiers. In most parts the compiler uses hexadecimal escapes which do not cause runtime errors.

psc version 0.7.4.1

The following works:
```purescript
import Prelude
import Data.Generic
import Control.Monad.Eff.Console

newtype Asgård = Asgård { "asgård" :: String }

derive instance asgårdGeneric :: Generic Asgård

main = log $ gShow $ Asgård { "asgård": "asgård" }
```
related part from compiled typeclass js
```
return {
  asgård: asgård_1
};
```
This fails however:
```purescript
import Prelude
import Data.Generic
import Control.Monad.Eff.Console

newtype Asgård = Asgård { "asgård-a" :: String }

derive instance asgårdGeneric :: Generic Asgård

main = log $ gShow $ Asgård { "asgård-a": "asgård" }
```
related js
```
return {
  "asg\229rd-a": asgård$minusa_1
};
```
```
pulp run
```
using node 0.12 results in
```
SyntaxError: Octal literals are not allowed in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at [eval]:1:1
    at Object.exports.runInThisContext (vm.js:74:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
```

### PR DESCRIPTION
**Pull request by paf31**
@garyb Does this look ok?

### CODE REVIEW

**Comment by garyb** [comment]
Definitely! :+1::+1:

**Comment by paf31** [comment]
Obviously at some point, we'll want to move to `Text`, but this solves things for now.

**Comment by paf31** [comment]
@phadej Any thoughts on what's going wrong with 7.10.3 here?

**Comment by phadej** [comment]
@paf31 something wrong with dependencies. Unfortunately. I'd allow 7.10.3 fail for now

**Comment by phadej** [comment]
Found an issue, hpc-coveralls fails because of it's dependency introduced breaking change. Working on that.

**Comment by paf31** [comment]
Thanks @phadej

**Pull request merged**
