### PR TITLE
Fix #421, match type instance heads eagerly

### LINKED ISSUE #421: Superclass constraints are ignored in instances
``` haskell
-- With this class definition:

class (Monad m) <= MonadError e m where
  throwError :: forall a. e -> m a
  catchError :: forall a. m a -> (e -> m a) -> m a
  
-- This instance doesn't work:
  
instance monadErrorMaybeT :: (MonadError e m) => MonadError e (MaybeT m) where
  throwError e = lift (throwError e)
  catchError = liftCatchMaybe catchError
  
-- You have to add another `Monad m` constraint:

instance monadErrorMaybeT :: (Monad m, MonadError e m) => MonadError e (MaybeT m) where
  throwError e = lift (throwError e)
  catchError = liftCatchMaybe catchError
```

### PR DESCRIPTION
**Pull request by paf31**
/cc @garyb 

Still a WIP, but probably near enough to review.

### CODE REVIEW

**Comment by paf31** [comment]
Looks like `quickcheck` breaks due to a false positive in the overlapping instance check.

**Comment by garyb** [comment]
Ah, well, aside from it not fully working it looks really nice :wink:

**Comment by paf31** [comment]
It's much simpler now :smile:

**Comment by garyb** [comment]
How are the false positives arising?

**Comment by paf31** [comment]
Not sure yet, but I'll look into it.

**Comment by paf31** [comment]
Hah, it's failing because `monadStateStateT` and `monadStateStateT1` overlap now, i.e. because it should :smile:

**Comment by paf31** [comment]
It just means we need to patch `transformers` after this is released.

**Comment by garyb** [comment]
What on earth is that? :wink:

Apparently needed by `ParserT`, but I assume that will work after this too?

**Comment by paf31** [comment]
I haven't tested `parsers` yet, but I will do now.

**Comment by paf31** [comment]
`parsers` compiles fine with the patch on `transformers`.

**Comment by paf31** [comment]
- [ ] Merge and release https://github.com/purescript/purescript-transformers/pull/49, verify `core-tests`
- [ ] Pick simplest instance when superclasses are involved.

**Comment by garyb** [comment]
Looks great! +:100: :shipit:

**Comment by garyb** [comment]
Although, there are non-transformers test failures in there too, is that because the tests are wrong now?

**Comment by paf31** [comment]
Oops, you're right. Looks like it's matching the `suArray` instance too eagerly in `Superclasses2.purs`. I'll look into it.

**Comment by paf31** [comment]
Hmm, GHC gives

```
/tmp/1.hs:21:13:
    Could not deduce (a ~ [a])
    from the context (Cl a)
      bound by the type signature for test :: Cl a => a -> a
      at /tmp/1.hs:20:9-24
      ‘a’ is a rigid type variable bound by
          the type signature for test :: Cl a => a -> a at /tmp/1.hs:20:9
    Relevant bindings include
      x :: a (bound at /tmp/1.hs:21:6)
      test :: a -> a (bound at /tmp/1.hs:21:1)
    In the first argument of ‘su’, namely ‘[cl x x]’
    In the expression: su [cl x x]
    In an equation for ‘test’: test x = su [cl x x]
```

So maybe we should let that test fail now.

**Comment by garyb** [comment]
Should we turn that into a failing test then, or do you think it's something that could be addressed? I guess if the new behaviour agrees with GHC then perhaps it is right :wink:

**Comment by paf31** [comment]
I think it should probably be a failing test, yeah. I can't get to it today, but hopefully can make this mergeable tomorrow.

**Comment by garyb** [comment]
Oops, merging #1410 means this now conflicts.

**Comment by garyb** [comment]
I'm more than happy for this to go in whenever you're ready, by the way.

**Comment by paf31** [comment]
`core-tests` is breaking, but should work again once `transformers` is merged and released. I need to also release 0.7.4 to make that `transformers` release build, so I just need to coordinate a few things. If you think it's all good to go, I'll merge and release everything this afternoon.

Could you please run your tool and find reverse dependencies for `transformers`?

**Comment by garyb** [comment]
I'm currently working on a fix for #1244, I'd really like to get that in for 0.7.4, hopefully it shouldn't take too much longer.

I'll run off that list once I'm done :)

Also suffering from internet problems today so not actually present in IRC, posting this from my phone...

**Comment by paf31** [comment]
I can figure out the dependent modules, that's ok. I can make a `transformers` release now, but make it pre-release?

**Comment by paf31** [comment]
I get:

- [ ] `free`
- [ ] `parallel`
- [ ] `quickcheck`
- [ ] `parsing`

**Comment by garyb** [comment]
- [ ] purescript-quickcheck
- [ ] purescript-maps
- [ ] purescript-catenable-lists
- [ ] purescript-free
- [ ] purescript-strongcheck
- [ ] purescript-sets
- [ ] purescript-graphs

**Comment by paf31** [comment]
`maps`, really?

**Comment by paf31** [comment]
Oh `devDependencies` though.

**Comment by garyb** [comment]
Yeah, via `quickcheck` I assume

**Comment by paf31** [comment]
No need for a version bump on those then, but we can update the dependency version. It's not going to break any code to pull in `maps`, since `transformers` won't be pulled in too, right?

**Pull request merged**
