### PR TITLE
Use data ctor name parser for data ctors in imports/exports

### PR DESCRIPTION
**Pull request by LiamGoodacre**
For #2609

### CODE REVIEW

**Comment by hdgarrood** [comment]
Oh wait hold on, it seems a bit odd to me that  `properName` won't successfully parse things with primes, even though primes are allowed in proper names (aren't they)? Is `properName` used elsewhere?

**Comment by LiamGoodacre** [comment]
For declarations, `properName` appears to be used:
* in class names (declaration, import, export, constraints, instances)
* fixity declarations

**Comment by garyb** [comment]
It's also used for the parts of module names, class names, etc. But actually, `ModuleName` is probably the only one we want to exclude primes from, so we could just make that a special case instead.

**Comment by garyb** [comment]
Ah, or maybe not, if that ^ is all it's used for.

**Comment by LiamGoodacre** [comment]
The value fixity declarations are for data constructors, right?  So I should probably change that too.

**Comment by garyb** [comment]
Yep! 👍

**Comment by hdgarrood** [comment]
Why does it not make sense to allow primes in `properName` and then special-case for module names?

**Comment by garyb** [comment]
That's what I was suggesting above. :smile:

**Comment by hdgarrood** [comment]
Oh, right, cool. Your message following that one made me think you had realised there was a problem with that approach.

**Comment by garyb** [comment]
Ah, I was pointing to Liam's message that came in just a few seconds before; he didn't mention module names in the places it was used so I was saying that might invalidate my suggestion.

**Comment by paf31** [comment]
Is this good to merge then?

**Comment by hdgarrood** [comment]
I think this is okay as is but ideally I think we would do a bit more refactoring of some of the code in the lexer to better reflect that we're allowing primes in more places. For example I think the `validUName` function probably ought to change a bit.

**Comment by paf31** [comment]
Well feel free to merge when you think it's ready, obviously.

**Comment by hdgarrood** [comment]
@LiamGoodacre if it's not clear what I mean let's just go ahead and merge this, we can do the refactoring I'm imagining later.

**Comment by paf31** [comment]
Let's merge this and do the tidying you describe in a separate PR then. Thanks @LiamGoodacre!

**Pull request merged**
