### PR TITLE
Allow `import M (C)` for importing class C

### PR DESCRIPTION
**Pull request by garyb**
edit: I'll add a few tests before calling this done.

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
I think you'll also need to update `prettyPrintImport`: https://github.com/purescript/purescript/blob/f1128ecb6f01bb1809adc9787df2958d9fefc096/src/Language/PureScript/Errors.hs#L1225-L1226

**Comment by garyb** [comment]
Yeah, there are a couple of issues actually. You can't explicitly export without using the `class` syntax too, for example.

**Comment by paf31** [comment]
I have an idea for an alternative to constraint kinds that I'd like to discuss before merging this. I need to prototype it first, but it wouldn't necessitate joining the two namespaces.

**Comment by hdgarrood** [comment]
Aren't the namespaces joined already?

```purescript
module Main where
data C
class C
```
"Error: Declaration for type class C conflicts with an existing type of the same name."

**Comment by paf31** [comment]
Hmm. I guess that's because of the generated type synonym for the class, but they could reasonably be made separate if we wanted to.

**Comment by paf31** [comment]
I'm hoping I'll be able to clean up that type synonym hack at some point anyway.

**Comment by garyb** [comment]
They're inconsistently joined - they are supposed to be fully, but there are cases that are not caught.

The ref-using-`class` is just a thing used to syntax-direct the lookup, it's not really necessary if we make the behaviour actually consistent :wink:

**Comment by paf31** [comment]
So could we make them completely separate namespaces then?

**Comment by kRITZCREEK** [comment]
That's going to be bad for editors afaict. It's going to be tricky to tell classes from types for go-to-definition, show kind, etc. 

And I think beginners will have the same problem.

**Comment by paf31** [comment]
But classes don't appear in the same places as types, syntactically speaking.

**Comment by paf31** [comment]
So what's the plan here then? Are the two namespaces going to be made separate, or joined together?

Note that constraint kinds don't need to influence the answer, if we go with the constraint proxy approach.

**Comment by garyb** [comment]
I don't really have a preference as to whether they're joined or not. :)

There are some odd rules around namespace collisions already, as you can't name a data constructor and class the same thing within a module, since the generated code would overlap unless we auto-rename one or other of the definitions.

**Comment by paf31** [comment]
I've been thinking about this in the context of constraint kinds, and I think it might be nice to keep them separate, but fix up those weird corner cases where they overlap, if possible.

The reason is that I think the errors will be nicer if the namespaces are separate. And constraint kinds/proxies/whatever will be a relatively little-used feature anyway.

**Comment by kRITZCREEK** [comment]
I'm not saying it's ambiguous, I'm saying it's hard to tell apart.

```haskell
myFn
  ∷ ∀ f m
  . Functor f
  ⇒ Applicative f
  ⇒ Parralel f m
  → Monad m
  → Int

myFn
  ∷ ∀ f m
  . Functor f
  ⇒ Applicative f
  ⇒ Parralel f m
  ⇒ Monad m
  → Int
```

Also I think it should be a valid question to ask psci for the kind of `Monad` even though it's a class. That will lead to collisions if we separate the namespaces.

**Comment by garyb** [comment]
> I've been thinking about this in the context of constraint kinds, and I think it might be nice to keep them separate, but fix up those weird corner cases where they overlap, if possible.
> 
> The reason is that I think the errors will be nicer if the namespaces are separate. And constraint kinds/proxies/whatever will be a relatively little-used feature anyway.

Sounds good to me 👍 

I'll close this in that case?

**Comment by paf31** [comment]
> Also I think it should be a valid question to ask psci for the kind of Monad even though it's a class. 

Well, with the constraint proxies approach, you would be able to say `:kind class Monad`.

> I'll close this in that case?

Let's leave it for now, so other people can weigh in. I would like to wait until we have a prototype constraint proxies branch, so that we at least know that's an option.

**Comment by hdgarrood** [comment]
@kritzcreek bit tangential but regarding that example: this is why I prefer putting the arrows on the right:

```purescript
myFn :: forall m a.
  Functor m =>
  Applicative m =>
  Parallel m =>
  m a ->
  m a
```

I don't have any strong feelings re whether classes are in a separate namespace. If it would improve errors I'm inclined to say yes to separating them.

**Pull request closed without merging**
