### PR TITLE
Fix warnings and enable -Werror

### PR DESCRIPTION
**Pull request by erdeszt**
Related issue: https://github.com/purescript/purescript/issues/1385

I'm not sure if the last commit is necessary, but most of the places used the one pragma per line convention so I thought I unify it.

### CODE REVIEW

**Comment by paf31** [comment]
Looks good to me, thanks! @garyb Any comments before I merge?

**Comment by garyb** [comment]
Nope! Aside from being glad we'll never have to do this in PureScript :smile:

**Comment by hdgarrood** [comment]
I don't think specifying `-Werror` in the cabal file is a good idea, as if any warnings are produced when someone tries to `cabal install purescript`, it will fail. I think Hackage will reject packages with `-Werror` now, actually.

I think changing these back and putting `-Werror` into the Travis script would accomplish the same goal.

**Comment by paf31** [comment]
Ok sounds good.

**Pull request merged**
