### PR TITLE
Address travis timeout issues

### PR DESCRIPTION
**Pull request by hdgarrood**
These commits amend the CI scripts so that if a build does time out, the next one can continue where the previous left off. For more info see https://gist.github.com/hdgarrood/29fa8ebcd5b5acd679cf429fd0a93e3e

This enables us to enable OSX builds again (which I have done).

### CODE REVIEW

**Comment by hdgarrood** [comment]
Fixes #2635

**Comment by paf31** [comment]
👍 Looks great!

**Comment by hdgarrood** [comment]
Thanks! I think the best way forward now is for me to do the following:

* delete all the Travis caches,
* merge this and wait for CI to finish
* if it fails (which it probably will because there's no cache), push one more empty commit to master to get it to build again

Then, the caches should be set up, and also it should speed up future CI builds as there won't be as much useless data from older versions of the compiler in the caches which has to be downloaded and re-uploaded for every job. If that sounds good I'll go ahead and do that.

**Comment by paf31** [comment]
Sounds good

**Pull request merged**
