### PR TITLE
Use base-compat in tests

### PR DESCRIPTION
**Pull request by phadej**
First step for https://github.com/purescript/purescript/issues/1604

This touches only tests, to act as an example. I could convert the rest either in single big PR or few smaller.

### CODE REVIEW

**Comment by paf31** [comment]
Looks nice, thanks! Does `license-generator` change anything if the changes are only in executables? I think it should.

**Comment by phadej** [comment]
Let's see, `cabal-dependency-licenses` wants `cabal configure` :/ compiling dependencies atm.

**Comment by phadej** [comment]
ping @paf31

**Comment by paf31** [comment]
:+1: Looks fantastic, thanks. I'll merge later this evening.

**Pull request merged**
