### PR TITLE
Update to use language-javascript 0.6.x

### LINKED ISSUE #1966: support language-javascript-0.6
Related: https://github.com/fpco/stackage/issues/1292

From `language-javascript` readme:

>There are currently two versions:
>
>* 0.5 series : Is a continuation of the 0.5.X.Y series, from the [master]
>(https://github.com/erikd/language-javascript/tree/master) branch of this
>github repository.
>
>* 0.6 series : This has a vastly different and improved AST which makes if far
>more difficult to build an non-sensical Javascript AST. This code is in the
>[new-ast](https://github.com/erikd/language-javascript/tree/new-ast) branch of
>this github repository.

So the change isn't trivial, but probably still quite straightforward. I hope.

### PR DESCRIPTION
**Pull request by nwolverson**
Fix #1966.

Not sure what the release path is (plus obviously this isn't going to build with our stackage/cabal builds as it is just now).

Must say this was more painful than anticipated, particularly trying to give similar output, whitespace in particular. To be fair the new AST is nicer, at least with syb to hand.

### CODE REVIEW

**Comment by phadej** [comment]
`language-javascript`? :)

**Comment by nwolverson** [comment]
Durr

**Comment by hdgarrood** [comment]
We get around problems like this one (where we want different versions of packages to those that are in the snapshot) by filtering the `cabal.config`: https://github.com/purescript/purescript/blob/master/.travis.yml#L39

If you add `language-javascript` to that `grep -v` command, I think that should do it.

**Comment by hdgarrood** [comment]
Also if you are going to modify that line, maybe remove the comment on the preceding line. It definitely is necessary ;)

**Comment by nwolverson** [comment]
Yeah I did update that before. Also can now remove `sourcemap` as we're on later lts.

**Comment by paf31** [comment]
So this is good to merge, yes? Thanks @nwolverson !

**Comment by nwolverson** [comment]
Yes GTG. Definitely good to get a sanity check of the output, I've been comparing diffs for a couple of projects and should only differ in a little whitespace and couple of semicolons.

**Comment by aspidites** [comment]
@nwolverson thanks for this. Until it's merged, I went ahead and compiled purescript using this branch and things work as expected. (I was running into #1986).

**Comment by garyb** [comment]
Looks good to me, I'm not too concerned about imperfect formatting as what this is fixing is way more important!

@paf31 we should probably get a release out ASAP with this in, as the released `psc-bundle` 0.8.3 is basically unusable.

**Comment by paf31** [comment]
Thanks!

**Pull request merged**
