### PR TITLE
Fix #1185, fix #1369, add everythingWithScope traversal to correct some scoping issues.

### LINKED ISSUE #1185: Unexpected "may not be defined" Error
I wrote the following code:
```
module Main where

data Person = Person String Int

getName p = case p of
  (Person name 20) -> name
  _ -> "Unknown"

name = getName (Person "Jimmy" 20)
```
To my surprise, it failed with:
```
Compiling Main
Error found:
Error in module Main:
Error in binding group getName, name:
Error at /home/michael/dev/me/purescript/examples/passing/InternalBindingNameShouldExistAtTopLevel.purs line 9, column 8 - line 9, column 34:
  getName may not be defined in the current scope
See https://github.com/purescript/purescript/wiki/Error-Code-NameNotInScope for more information, or to contribute content related to this error.
```
If I change `name =` to something like `jimmyName =` everything works

Thoughts?

### LINKED ISSUE #1369: Shadowing warning doesn't apply to let bindings
This code does not throw "Duplicate value declaration" (or any other) error:
```purescript
foo :: forall e. Eff (console :: CONSOLE | e) Unit
foo = do
  a <- pure 5
  log $ "a is " ++ (show a)
  a <- pure 10
  log $ "a is " ++ (show a)
  let a = 5
  log $ "a is " ++ (show a)
  let a = 10
  log $ "a is " ++ (show a)
```
And if you run it you'll see:

    a is 5
    a is 10
    a is 5
    a is 10

### PR DESCRIPTION
**Pull request by paf31**
This isn't quite right, but it's pretty close.

### CODE REVIEW

**Comment by paf31** [comment]
Ok, this is good to go, I think.

**Comment by paf31** [comment]
Works with Halogen, and correctly identifies a few new shadowed names in `Data.Array` and `Control.Monad.Rec.Class`.

**Comment by garyb** [comment]
Looks good to me. Shame we needed a new traversal for it, but it makes sense :+1:

**Comment by paf31** [comment]
Yeah, it's a bit of unfortunate, but none of the existing traversals really did what I needed.

**Pull request merged**
