### PR TITLE
Remove old generics and generics-rep record support

### PR DESCRIPTION
**Pull request by paf31**
This removes

- the old `generic` deriving mechanism
- deriving for records in `generics-rep`

It needs some changes to `generics-rep`, and we'd probably want to deprecate `generics` too.

This is breaking, so it would go into 1.0 or 0.12.0.

Finally, this means we need to figure out how to derive `Eq`, `Show`, `Ord`, etc. for records using `RowToList`, which means moving some things around in the core libraries.

### CODE REVIEW

**Comment by hdgarrood** [comment]
I was expecting that we wouldn't derive `Eq`, `Show`, `Ord` etc, but rather just define them as normal instances; is that not the case? What are the unresolved questions around instances such as `Show (Record a)`?

**Comment by hdgarrood** [comment]
Also, this seems fairly significant, so I think it might be sensible to call the first release containing this v0.12.0, just in case we later notice some problem with it which we want to fix, but fixing it requires another breaking change.

**Comment by paf31** [comment]
Yes, sorry I meant we should write instances for those.

And yes, I think we do need a 0.12.0 release separate from 1.0.0 at this point.

**Comment by hdgarrood** [comment]
Is there anything stopping us from writing those instances now, and releasing updated core libraries with those instances, so that people can use them with the 0.11.x compiler?

**Comment by paf31** [comment]
Yes, we'd need to move `RowToList` somewhere where the new instances in `Prelude` could use it.

**Comment by paf31** [comment]
Fixes #2911.

**Comment by paf31** [comment]
@hdgarrood Done, thanks! I'll merge once CI passes.

**Comment by joneshf** [comment]
Would it be possible to add a `Fail` instance to generics/generics-rep describing this particular change and the resolution?

**Comment by paf31** [comment]
How would it work? The compiler won't derive instances for records any more, so the issue is not that we don't want an instance to exist, but that we want other instances to exist (e.g. `Show (Record r)`) now.

**Comment by joneshf** [comment]
I see. What sort of message do you get when you try to derive now?

**Comment by paf31** [comment]
> No instance for `YourClass { ... }`

**Comment by fsoikin** [comment]
What's the official way of migrating old `Data.Generic`-based code to `Data.Generic.Rep`? Is there, perhaps, a stopgap `instance New.Generic a r => Old.Generic a` implemented somewhere?

**Comment by paf31** [comment]
You could try using [this code](https://github.com/purescript/purescript-generics-rep/pull/7). If it doesn't get merged, I'll probably close the PR and make a `generics-compat` repo.

**Comment by fsoikin** [comment]
Got it, thanks @paf31.

One question, out of curiosity though: [a comment](https://github.com/purescript/purescript-generics-rep/pull/7/files#diff-60912c1fe64dd20d56036eab89061210R105) on that PR states that "_For standard data structures, you can simply write `derive instance deepFoo :: Deep Foo` in the module they are declared, and the instance methods will be filled in for you._" How does that work exactly? PureScript can't do `DeriveAnyClass`, can it?

**Comment by paf31** [comment]
I may have copied that incorrectly from the original docs 😄

**Comment by fsoikin** [comment]
Ok, got it.

**Pull request merged**
