### PR TITLE
Fix #1839, Renaming for nested constructor binders

### LINKED ISSUE #1839: Bug when a module has the same name as constructor
```
module Main where
import Prelude
import Control.Monad.Eff.Console
import Foo

data X = Foo Foo.Bar

eval (Foo (Foo.Bar x)) = x

main = print $ eval $ Foo None

module Foo where
data Bar = Bar Int | None

```

```
        if ($2 instanceof Foo.Bar) {
                             ^

TypeError: Expecting a function in instanceof check, but got undefined
```

### PR DESCRIPTION
**Pull request by sharkdp**
This fix applies the module collision renaming recursively to nested constructor binders.

### CODE REVIEW

**Comment by garyb** [comment]
Hmm, the traversal is already supposed to do this I think, so perhaps it's that that needs updating instead. Thoughts @paf31?

**Comment by paf31** [comment]
It definitely should work already. The traversal must be wrong.

**Comment by sharkdp** [comment]
Okay, I gave this another try. Let me know if I'm causing more trouble instead of help :smile:.

**Comment by garyb** [comment]
I can't believe that case has been missing for so long :scream:, I assume that change still fixes the related issue?

**Comment by sharkdp** [comment]
Yes, it still fixes the issue. Unfortunately, I didn't know how to add a test for potential runtime errors like this.

If my research is correct, this function (`CoreFn.Traversals.everywhereOnValues`) is only called from the module renaming function, which explains why it didn't pop up anywhere else(?).

**Comment by garyb** [comment]
If a test throws an exception it's considered to fail, so you could use the example from the original issue I think. I'm happy to merge this as-is though, unless you really want to add a test? :wink:

**Comment by sharkdp** [comment]
I could add a test if you want, but I'm also fine with you merging it directly, of course.

**Comment by garyb** [comment]
:+1:

**Comment by garyb** [comment]
And thanks!

**Pull request merged**
