### PR TITLE
Fixes running tests on Windows

### LINKED ISSUE #1401: Test suite failure on Windows
This is proving rather tricky. I added a fix so it would use `npm.cmd` as appropriate, but that cmd file relies on a magic variable called `%~dp0` which is supposed to be the directory that the current cmd file resides within, however when it's launched from Haskell, it's not - it's getting the support folder path instead.

That kinda sounds like a bug in `callProcess` to me, so I'm not sure where to go now...

### PR DESCRIPTION
**Pull request by garyb**
Fixes #1401... but maybe should wait for #1382 first?

### CODE REVIEW

**Comment by paf31** [comment]
:+1:

**Comment by phadej** [comment]
The `tests/support/setup-win.cmd` needs to be in `extra-source-files` (the travis build won't catch windows problems :( ).

**Comment by garyb** [comment]
Good call!

**Comment by paf31** [comment]
@garyb Do you want to merge this before 0.7.4?

**Comment by garyb** [comment]
I'll probably update this before my next PR so I can actually test it, so yeah I guess so!

**Comment by garyb** [comment]
This should be good now, I'll merge once travis completes.

**Comment by paf31** [comment]
:+1:

**Pull request merged**
