### PR TITLE
WIP: include types in CoreFn

### PR DESCRIPTION
**Pull request by coot**
Should we have a `--dump-types` switch as suggested by @metaleap in #3150.

### CODE REVIEW

**Comment by paf31** [comment]
My 2¢: we shouldn't include type information until we can check them, which I think means we need to elaborate to something like System F, and then include explicit quantifiers so that every type variable is scoped.

**Comment by metaleap** [comment]
> My 2¢: we shouldn't include type information until we can check them

To double-check my newb interpretation of the above: does this mean purs' type-checking happens *after* `--dump-corefn`?

**Comment by paf31** [comment]
No, I'm referring to something like GHC's core linting, which is a separate type _checking_ pass (note: checking only, not inference).

**Comment by metaleap** [comment]
> like GHC's core linting

Ah got it, I remember that one! Hmm, but why shouldn't we add the typed-core dumping now: once the linter happens later on, the results simply become "correct" automagically that much later on --- in other words, "something is more useful than nothing" for most-likely both @coot 's and my use-cases and whoever wants to experiment with "alt-transpilation" alongside ongoing developments. Seeing as the it's almost/mostly just the change from `_` to `toJSON t` in `ToJSON.hs`. Us few niche users of the `--dump` functionality can for now simply very reasonably be expected to assume all dumps invalid if their preceding `purs` run that dumped them errored out in the end.

(Just my 2c, but I don't feel too strongly about it, I'm equally fine with keeping this PR separately in my personal fork until then too --- my progress is very slow-going anyway currently)

**Comment by paf31** [comment]
> Hmm, but why shouldn't we add the typed-core dumping now: once the linter happens later on, the results simply become "correct" automagically that much later on

Because we don't know they're correct, we don't have a spec. Also it's more code that needs to be maintained and tested. It's easy to add it now, and much harder to maintain it later.

I suggest adding this in a compiler fork, and answering those questions there first.

**Comment by coot** [comment]
I agree, we need make corefn a typed checked language first.

**Pull request closed without merging**
