### PR TITLE
Update test suite to use real supporting libraries

### PR DESCRIPTION
**Pull request by hdgarrood**
* Use real versions of supporting libraries
* Use bower to make it easy to update supporting libraries

The reason I did this is that I noticed that some of the tests had started producing warnings, because of type classes with operator members, and I think this might have been interfering with their results. (Investigating now).

### CODE REVIEW

**Comment by hdgarrood** [comment]
The bower.json for the set of supporting libraries is currently pointing to a specific commit in my fork. Once https://github.com/purescript/purescript-assert/pull/1 is merged we can point at the normal version.

**Comment by hdgarrood** [comment]
The CI failure on the "fix psci tests" commit turns out to be a real bug, which was that type class members didn't get completed in psci. I've just fixed this.

**Comment by paf31** [comment]
Looks good but did you mean to check in the `flattened` directory?

**Comment by hdgarrood** [comment]
I did, I was thinking it would be nice to be able to run the tests without needing bower. I don't feel very strongly either way though. Would you rather the tests shelled out to bower at the beginning to get this code?

**Comment by paf31** [comment]
Hmm, I'm not sure. It'd be nice to be able to accept PRs from Haskellers who don't have Bower, I suppose. I'm not sure it's so much more convenient that it's worth all the duplication of code though TBH.

**Comment by hdgarrood** [comment]
I don't think PRs are a problem if we don't check it in - if the submitter hasn't set their environment up, it won't matter, because we'll hear from Travis soon after they create the PR. I'll change that, then.

**Comment by natefaubion** [comment]
Does it make sense to pull from master for these repos? I'm thinking if one makes a Prelude change, and it needs to be tested before a release.

**Comment by hdgarrood** [comment]
What sort of change are you thinking of? I think the test suites for individual libraries are better equipped to test changes in those libraries, and the tests here should really just be for the compiler.

**Comment by natefaubion** [comment]
I was thinking about the bug wrt to inlining boolean operators. Changes were made to the published Prelude that affected the compiler's optimizations. If we change something like that again, would we want to coordinate and do compiler/library releases at the same time?

**Comment by paf31** [comment]
:+1: Thanks very much!

**Comment by paf31** [comment]
Something isn't quite right with the tests now, but I'm not sure if it's related to this. Several tests break on my machine, but `cabal test` is reporting success.

**Comment by hdgarrood** [comment]
Perhaps because not all of the instances have been updated? The old Prelude was taken from before all of the operator members had been changed, so for example `Eq` had a member `(==)`. I was planning on fixing all these in #1323.

**Comment by paf31** [comment]
The code compiles fine with `psc` though.

**Comment by paf31** [comment]
Also, why would `cabal test` pass?

**Comment by paf31** [comment]
Ah, had to delete `.test_modules`. Sorry, never mind...

**Pull request merged**
