### PR TITLE
Issue #2453: dump output of psc tests to file

### PR DESCRIPTION
**Pull request by andyarvanitis**

### CODE REVIEW

**Comment by paf31** [comment]
👍 Looks good to me, thanks!

**Comment by paf31** [comment]
Fixes #2453

**Comment by andyarvanitis** [comment]
Looks like stack timed out on building lens on the last case. Is there a way to get the checks to build and run again without a new commit?

**Comment by paf31** [comment]
Yes, I've restarted the build.

**Comment by andyarvanitis** [comment]
Thanks!

**Pull request merged**
