### PR TITLE
Bump bounds

### PR DESCRIPTION
**Pull request by phadej**

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! I hope to release 0.8.1 soon.

**Comment by hdgarrood** [comment]
Perhaps we should add ghc 7.6.3 to tested-with in purescript.cabal too?

**Comment by hdgarrood** [comment]
Oh also, do we want to disallow aeson 0.10.x? I'll just check the release notes to see if it affects us.

**Comment by hdgarrood** [comment]
Actually I guess we don't need to do that as aeson-0.10 is deprecated on hackage anyway.

**Comment by phadej** [comment]
@paf31, what's still holding the next release / revision of purescript?

**Comment by AppShipIt** [comment]
@phadej I think the source map and psc-ide PRs which are wrapping up.

**Comment by paf31** [comment]
Right, I hope to get those merged soon and make a release.

**Pull request merged**
