### PR TITLE
pretty print proxy types when rendering docs

### LINKED ISSUE #3135: purs docs doesn't complete when using new proxy syntax
Using purs 0.11.6 [development build; commit: 71fc308a53bf89678c1e1d4a242cc01561d556d1] and trying to create the documentation (purs docs) when having the new proxy syntax doesn't seem to complete. Even though it uses up to 500% CPU.

Minimal Example:
````purescript
foo :: forall a. @a -> Int
foo _ = 42
````

Removing the proxy and it finishes just fine.

### PR DESCRIPTION
**Pull request by sloosch**
Fixes #3135 .

### CODE REVIEW

**Comment by LiamGoodacre** [comment]
@sloosch, could you please reopen this against the `0.12.0-dev` branch?

**Comment by LiamGoodacre** [comment]
Thanks.  Could you add a test?  You'll need to add a file to `examples/docs/src` and update `tests/TestDocs.hs` to reference it.

**Comment by sloosch** [comment]
Done!

**Comment by LiamGoodacre** [comment]
Oh I nearly forgot: could you add yourself to `CONTRIBUTORS.md`? Then I'll get this merged.
Thanks for working on this.

**Pull request merged**
