### PR TITLE
Better re-export handling

### LINKED ISSUE #291: Allow modules to re-export imported values
So, for example, `Control.Monad.Writer` can also export the functions from `Control.Monad.Writer.Class`.

``` haskell
module Control.Monad.Writer
  ( Writer()
  , runWriter
  , writer
  , listen
  , pass
  , tell
  , listens
  , censor
  ) where

import Prelude
import Control.Monad.Identity
import Control.Monad.Writer.Trans
import Control.Monad.Writer.Class
import Data.Monoid
import Data.Tuple

type Writer w a = WriterT w Identity a

runWriter :: forall w a. Writer w a -> Tuple a w
runWriter = runIdentity <<< runWriterT
```

### LINKED ISSUE #1244: Error when explicitly importing value re-exported from module
I wasn't sure if this was known already or not, but I think I ran into a bug:

```purescript
module Foo where

  foo :: Int
  foo = 3

module Bar (module Foo) where

  import Foo

module Baz where

  import Bar (foo) -- this is the problem

  baz :: Int
  baz = foo
```

```
➜  rexport  psc src/Foo.purs 
Error:
Error in module Baz:
Error at /home/joneshf/programming/purs/rexport/src/Foo.purs line 12, column 3 - line 14, column 3:
  Unknown value Bar.foo
See https://github.com/purescript/purescript/wiki/Error-Code-UnknownValue for more information, or to contribute content related to this error.
```

If the problem line is changed to `import Bar`, then things compile fine.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1244. Resolves #291 in a slightly different way too (if `A` explicitly imports values from `B` and then re-exports `B`, only the values it imported will be re-exported).

### CODE REVIEW

**Comment by garyb** [comment]
All green at last!

**Comment by paf31** [comment]
:+1: Thanks!

_Edit_: Actually, after I `cabal install`ed this, `transformers` test suite no longer builds - it complains about things not being in scope, but they should be because of module reexports. Not sure what's going on, but I think we should figure it out before releasing the compiler.

**Comment by garyb** [comment]
They run okay for me now, did you make those changes for v0.7.0-rc.2 after posting this?

The changes you made look right to me - you can't export a module anymore unless you import it, the reasoning for this being only the specific values imported into the current module are re-exported when you export a module.

**Comment by paf31** [comment]
The tests run ok? I get `Unknown value callCC` since `callCC` is imported via a module reexport in the tests. This is with what's on `master`.

**Comment by garyb** [comment]
Yep. Tried cleaning the output folder?

**Comment by garyb** [comment]
Yup, definitely works for me - I just installed the `master` version of `psc` on my Mac, and with a fresh checkout of `transformers` the tests run fine.

**Comment by paf31** [comment]
Yes, I just removed `output` and I get the same error. I'll reinstall `psc` to be sure.

**Comment by paf31** [comment]
Yes, I don't see module reexports in the externs files. Is that an issue?

**Comment by paf31** [comment]
Seems like it would be an issue if we want to support separate compilation without looking at original source files.

**Comment by garyb** [comment]
#1425 should sort that out.

**Pull request merged**
