### PR TITLE
0.9 Remove deprecated class import/export syntax

### PR DESCRIPTION
**Pull request by LiamGoodacre**
We should wait until the Prelude updates (#2069) are in so we don't temporarily break the publish tests.

### CODE REVIEW

**Comment by paf31** [comment]
What is the issue with the test suite?

**Comment by LiamGoodacre** [comment]
@paf31 The existing Prelude has exports using the deprecated syntax. `Semigroupoid` for example, giving the error `Cannot export unknown type Semigroupoid`.

**Comment by paf31** [comment]
If you merge in @garyb's latest changes, does that change anything?

**Comment by LiamGoodacre** [comment]
@paf31 Tests all pass locally now that I've rebased :]

**Comment by paf31** [comment]
Brilliant, thanks!

**Comment by garyb** [comment]
Thanks!

**Pull request merged**
