### PR TITLE
Remove duplicates from 'overlapping instances' error report

### PR DESCRIPTION
**Pull request by balajirrao**

### CODE REVIEW

**Comment by paf31** [comment]
Thanks! Do you have an example of where this change is required?

**Comment by balajirrao** [comment]
No, sorry I don't have an example. I hit this bug when I was trying to make psci give a type to (\x -> x ++ x). It partially succeeded but failed with an overlapping instances error (with duplicates).

**Comment by paf31** [comment]
:+1: Thanks!

**Comment by balajirrao** [comment]
Thanks for merging!

**Pull request merged**
