### PR TITLE
Disallow orphan instances

### LINKED ISSUE #1247: Disallow orphan instances
We keep talking about this but don't seem to have an issue for it. I'm quite an enthusiastic proponent of disallowing them and not providing an escape hatch either.

Worth discussing too perhaps, what counts as an orphan in the presence of multi-parameter typeclasses? I guess for an instance to not be an orphan it must satisfy either:

1. The instance is declared in the same module as its class.
2. At least one of the types appearing in the instance head is declared in the current module.

### PR DESCRIPTION
**Pull request by garyb**
Resolves #1247

### CODE REVIEW

**Comment by puffnfresh** [comment]
:fireworks:  :+1:

**Comment by tonymorris** [comment]
:+1:

Typo in comment: `OrhpanInstance`

**Comment by garyb** [comment]
I thought you'd like this :smile:

**Comment by garyb** [comment]
@tonymorris Ah thanks!

**Comment by paf31** [comment]
:100:

Hopefully we can use this restriction to speed up instance search a bit too.

**Comment by garyb** [comment]
Initial attempt at the error message page: https://github.com/purescript/purescript/wiki/Error-Code-OrphanInstance

It's hard to write about without being confusing!

**Pull request merged**
