### PR TITLE
Remove --require-path completely

### PR DESCRIPTION
**Pull request by paf31**
This is the first of several PRs to remove the stuff we deprecated in 0.8.*.

### CODE REVIEW

**Comment by paf31** [comment]
Rebased.

**Comment by garyb** [comment]
Shall we start merging these and call 0.8 done? Doesn't seem like there are any pressing issues that would necessitate a 0.8.6.

**Comment by garyb** [comment]
Oh, and :+1: :smile:

**Comment by paf31** [comment]
I'd like to close 0.8.*, yeah. Maybe we can continue in a branch if necessary, or work in a branch for 0.9.

**Comment by garyb** [comment]
Sounds good to me. :shipit:

**Comment by ethul** [comment]
Yes, noted. Thanks!

**Pull request closed without merging**
