### PR TITLE
Add --as-needed linker option to stop linking against unused shared objects

### PR DESCRIPTION
**Pull request by jplatte**
See #2026

### CODE REVIEW

**Comment by hdgarrood** [comment]
:+1: from me (assuming CI passes).

**Comment by paf31** [comment]
Thanks!

**Comment by nwolverson** [comment]
This doesn't build for me now 
```
Linking .stack-work/dist/x86_64-osx/Cabal-1.22.5.0/build/psc/psc ...
ld: unknown option: --as-needed
```

**Comment by paf31** [comment]
Ok, if we can't figure out why, I'll revert this.

**Comment by jplatte** [comment]
@nwolverson The important thing is which linker you are using. I assume your ld is not the GNU linker?

**Comment by hdgarrood** [comment]
Same here, OSX:

```
$ ld -v
@(#)PROGRAM:ld  PROJECT:ld64-264.3.101
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7k armv7m armv7em (tvOS)
LTO support using: LLVM version 7.3.0
```

**Comment by nwolverson** [comment]
```
@(#)PROGRAM:ld  PROJECT:ld64-241.8
configured to support archs: armv6 armv7 armv7s arm64 i386 x86_64 x86_64h armv6m armv7m armv7em
LTO support using: LLVM version 3.5svn
```

**Comment by hdgarrood** [comment]
Come to think of it, this seems to me like something that should be addressed in Cabal, really.

**Comment by jplatte** [comment]
Yeah, it's probably better to revert my commit for now.

Before we try to make this the default in cabal or anything like that though, we should try to find out why it's not the default in the GNU linker. Hopefully it's just some sort of backwards compatibility and not a thing where the linker produces broken executables.

**Pull request merged**
