### PR TITLE
Run bower thru node(js) executable

### PR DESCRIPTION
**Pull request by phadej**
Resolve https://github.com/purescript/purescript/issues/2183

I'll verify this on clean-ish ubuntu install soon.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Does Windows have `false`? Also, what do you think about matching on the result, and in the Nothing case, printing a more descriptive error before exiting nonzero?

**Comment by phadej** [comment]
@hdgarrood let's see what appveyor says.

**Comment by phadej** [comment]
@hdgarrood Added small `stderr` output and made it fail harder (not thru `false`). Let's see what CIs say

**Comment by hdgarrood** [comment]
:+1: lgtm (assuming CI passes).

**Comment by phadej** [comment]
and CI is green

**Comment by paf31** [comment]
Thanks again!

**Pull request merged**
