### PR TITLE
Fix #2772, match type level strings in docs renderer

### LINKED ISSUE #2772: purs docs --html gets stuck somewhere on QuickCheck
It seems like `purs docs` gets stuck when I run

```
purs docs --format html 'src/**/*.purs' 'bower_components/purescript-*/src/**/*.purs'
```

@hdgarrood Do you have any time to look at this?

### PR DESCRIPTION
**Pull request by hdgarrood**
This might be the same problem as in #2448 but I haven't been able to verify.

### CODE REVIEW

**Comment by paf31** [comment]
Good catch - these printer bugs are always a pain to identify. Thanks!

**Comment by hdgarrood** [comment]
Great. I think I'll just add a test and check whether it is really #2448 before merging.

**Comment by hdgarrood** [comment]
The instance that was causing this was `zipListIsNotBind`, which is a custom type error for attempts to use any `Bind ZipList` instance. Do you think we should remove any instance that mentions `Prim.Fail` in its constraints for the purposes of docs?

**Comment by paf31** [comment]
I don't think so, I think the few use cases will be few and far between.

**Comment by hdgarrood** [comment]
Ok then. Having that information in the docs will likely be useful anyway, come to think of it.

**Comment by hdgarrood** [comment]
Yes! This does fix #2448 as well.

**Comment by hdgarrood** [comment]
AppVeyor CI failure looks spurious so I think I'll ignore it, especially since the branch build succeeded.

**Pull request merged**
