### PR TITLE
etags format fix

### PR DESCRIPTION
**Pull request by user471**

### CODE REVIEW

**Comment by paf31** [comment]
Is there documentation for this format anywhere?

Also, could you please add yourself to `CONTRIBUTORS.md`? Thanks.

**Comment by user471** [comment]
https://en.wikipedia.org/wiki/Ctags#Etags_2

**Comment by paf31** [comment]
Could you give some details so I can understand?

**Comment by user471** [comment]
Before fix it was 
```"\x7f" ++ name ++ "\x01" ++ show line ++ ","```
but format is
```
{tag_definition_text}<\x7f>{tagname}<\x01>{line_number},{byte_offset}
```
or if ```{tag_definition_text} == {tagname}```
```
{tag_definition_text}<\x7f>{line_number},{byte_offset}
```
so correct code is
```
 name ++ "\x7f" ++ show line ++ ","
```

**Comment by AppShipIt** [comment]
@user471 Your anonymity is perplexing 😉

**Pull request closed without merging**
