### PR TITLE
Added pre-built installers to INSTALL.md

### PR DESCRIPTION
**Pull request by MiracleBlue**
Added 3 examples of installing the latest pre-built PureScript compiler binary, for Homebrew, NPM and PSVM.  Also added reference to FPChat Slack channel for getting help with PureScript.

### CODE REVIEW

**Comment by MiracleBlue** [comment]
Would you mind hitting the merge button for me?  Since I'm not a project collaborator, I can't do it :(

Thanks for the approval!

**Comment by hdgarrood** [comment]
I know, I just want to give other maintainers a chance to weigh in first.

**Comment by MiracleBlue** [comment]
Ah no worries, I'll leave it with y'all :) cheers!

**Comment by LiamGoodacre** [comment]
@MiracleBlue: Could you add yourself to the `CONTRIBUTORS.md` file please.

**Comment by MiracleBlue** [comment]
Done :)

**Comment by kRITZCREEK** [comment]
Thanks!

**Pull request merged**
