### PR TITLE
Add support for bundling function declarations

### PR DESCRIPTION
**Pull request by kl0tl**
**Description of the change**

`purs bundle` does not consider the dependencies of function declarations because the compiler always emit variable declarations. This has unfortunate consequences when optimizing foreign modules:

```js
"use strict";

var x = 0;

function foo() {
  return x;
}

exports.foo = foo;
```

If the dependency of `foo` on `x` isn’t discovered, `x` appears unused and is removed from the bundle!

Fix https://github.com/purescript/purescript/issues/4039, fix https://github.com/purescript/purescript/issues/3259 and fix https://github.com/purescript/purescript/issues/2290.

---

**Checklist:**

- [x] Added the change to the changelog's "Unreleased" section with a reference to this PR (e.g. "- Made a change (#0000)")
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by f-f — APPROVED** [review]

**Review by rhendric — APPROVED** [review]

**Comment by rhendric** [comment]
This PR spans releases, so it'll need a rebase and the changelog entry will need to be moved to the current Unreleased section.

**Comment by hdgarrood** [comment]
Is the changelog entry the only thing preventing merging here now?

**Comment by kl0tl** [comment]
No more!

**Review by hdgarrood — APPROVED** [review]

**Comment by JordanMartinez** [comment]
Just FYI. This seems to have introduced a regression. See purescript-contrib/purescript-arraybuffer/issues/34. Should I open a new issue? Or is there one already?

**Pull request merged**
