### PR TITLE
More object syntax

### PR DESCRIPTION
**Pull request by garyb**
Getters and updaters, as discussed in the other PR.

### CODE REVIEW

**Comment by garyb** [comment]
Checked with `test-everything` too - all seems good.

**Comment by jdegoes** [comment]
These changes will be nice -- help level the playing field wrt Haskell records, as well as provide "lightweight lenses" for disposable records that aren't used often enough to warrant real lenses.

**Comment by michaelficarra** [comment]
I would prefer sections. Then we could use `(.x)` syntax to mirror `(* 2)`.

**Comment by garyb** [comment]
@michaelficarra: That didn't even occur to me, but you're right, it makes much more sense. I'll give it a try.

**Comment by garyb** [comment]
Chained property access was actually a little tricky to parse before, so it only supported `_.x`, but section-style it's easy. The only reservation I have about that is it means the getters differ from the literal constructors and updaters, as you can't do `{ x: { y: _ } }` or `obj { x = { y = _ } }` - that seems like more of a job for proper lenses.

**Comment by michaelficarra** [comment]
You can't compose constructors the same way? Both `{ y: _ } >>> { x: _ }` and `{ x: { y: _ } }` seem fine to me.

**Comment by garyb** [comment]
Yep, that works too, this is all syntactic sugar for normal functions, so `(.x)` is desugared into `(\obj -> obj.x)`, `{ x: _ }` is `(\x -> { x: x })`, `obj { x = _ }` is `(\x -> obj { x = x })`. I just meant being able to compose reduces the pain of not being able to do `(.x.y)` or `{ y: _ } >>> { x: _ }`.

**Comment by paf31** [comment]
Nice :)

Could you please add a couple of cases to the pretty printer so that it doesn't spin if we hit these cases?

Also, I wonder if it would be useful to be able to section the record itself on update:

```purescript
updateFoo o = _ { foo = 1 } <$> o
```

But that could be something for later.

**Comment by garyb** [comment]
Yep no problem, those cases are in now. The other changes in there are just a few things hlint was complaining about.

**Comment by paf31** [comment]
:+1: Thanks very much!

This deserves a version bump - do you think it's good to release now, or did you want to make any other changes?

**Comment by garyb** [comment]
I was going to have a stab at operator sections, it seems like an opportune time as we've just added some section-like syntax. I know that's not actually on the list for 0.7, but hopefully will be relatively easy to do. If I don't get it sorted by tomorrow though, go for it.

**Comment by paf31** [comment]
Ok, no rush.

**Comment by garyb** [comment]
I need to make the change to use `Supply` for this too actually.

**Comment by paf31** [comment]
Good point. I'll wait for that, and then push a release. Thanks very much - 0.6.5 should be a really nice release.

**Comment by garyb** [comment]
No problem!

I'm working on the change now, shouldn't be long.

**Comment by jdegoes** [comment]
The problem with sections for getters is that they don't have a counterpart for setters.

```
(.foo)
???
```

Versus:

```
_.foo r
{ foo = _ }
```

Also via @paf31's suggestion:

```
_ { baz = 1 }
```

So I'd argue that `(.foo)` is a false consistency with operator sections because `.foo` is not really an operator; maybe it helps to think of it that way, maybe not. So for that reason, plus the reason of there being no "operator section" analogue for the other record operations, I think `_.foo` is probably better.

As a bonus, it will be immediately familiar to anyone whose worked with Scala before.

**Comment by garyb** [comment]
Hmm, maybe you're right.

The thing I liked about the sections is it's obvious that they behave in a similar way to standard operators - they're a representation of a partially applied thing, whereas `_.x` looks more like a normal accessor. I suppose `_` generally is taken to be a hole of some kind though, so maybe that's not entirely valid.

Also on your point, there's no section like `(obj.)` - although if we introduce first class labels that could become meaningful.

**Comment by paf31** [comment]
`(.foo)` isn't an operator, but it could become one if we add first class labels, using the optimizer to turn the saturated application `(.) obj "lbl"` into `obj["lbl"]`. Obviously there are some syntactic issues there, but it's a possibility.

I like the symmetry of using `_`. I'm not a fan of the Elm-style `.foo` without parens, due to syntactic ambiguity modulo whitespace, but since we parenthesize, I don't feel strongly either way.

**Comment by jdegoes** [comment]
A section like `(obj.)` would handle polymorphic labels and values, but there would still be no section-like notation for updating or setting. Since these would have to use `_`, it seems more consistent to just say that if you want "sections" for records of any kind, you use the underscore. 

Indeed, the reason Scala has this underscore notation is exactly for products (tuples in Scala's case, but records in Purescript's case), because curried functions don't really need them. It's where you have an n-product and want a function that will stick a value in one of those n slots.

But that said, I don't have a strong preference either way, I just think the analogy with operator sections is (currently) a false one and (a bit) inconsistent with the record update syntax.

**Comment by garyb** [comment]
Sold. :+1: 

Should I change this again now before too many people start making use of `(.prop)` syntax? I guess we'd want to make a new release too.

**Comment by paf31** [comment]
I guess that if we're committing to the changes, then we should do this sooner rather than later and rerelease.

**Comment by jdegoes** [comment]
Either way's fine by me (with the above caveats), I'm just so happy to have this stuff. Lots of code will become much more readable. Thanks @garyb!

**Comment by michaelficarra** [comment]
@paf31: what would the signature of `_ { foo = 1 }` be? `forall a. (| a) -> (foo :: Number | a)`?

**Comment by garyb** [comment]
I guess it would be inferred as 

``` purescript
forall a. { foo :: Number | a } -> { foo :: Number | a }
```

as it would desugar to:

``` purescript
\obj -> obj { foo = 1 }
```

**Comment by michaelficarra** [comment]
So it wouldn't be able to extend a record that doesn't have a `foo` field?

**Comment by garyb** [comment]
I think that's the type that "updater syntax" currently has. It would be nicer if it could extend the record, but I think we'd need some kind of record constraints to make that work, right @paf31?

**Comment by paf31** [comment]
Correct, it's just like regular object updates right now. There's no concept of extension because we don't have lacks-constraints.

**Pull request merged**
