### PR TITLE
Fix instance deriving regression

### LINKED ISSUE #4431: Functor deriving looking up wrong instances
Regression since 0.15.6: Changing tyvar names makes the new functor deriving fail, /cc @rhendric #4420. It appears that it is looking for constraints based on tyvars in the constructor declaration, not from the instance declaration.

@thomashoneyman reported on Discord an example that should derive but fails:
```purescript
module FunctorAlpha where

import Prelude

data TypedCache :: (Type -> Type) -> Type -> Type
data TypedCache key a = Get (key a)

derive instance (Functor k) => Functor (TypedCache k)
```

The error message:
```
[1/1 CannotDeriveInvalidConstructorArg] src/FunctorAlpha.purs:8:1

  8  derive instance (Functor k) => Functor (TypedCache k)
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  One or more type variables are in positions that prevent Functor from being derived.
  To derive this class, make sure that these variables are only used as the final arguments to type constructors, that their variance matches the variance of Functor, and that those type constructors themselves have instances of Data.Functor.Functor, Data.Bifunctor.Bifunctor, Data.Functor.Contravariant.Contravariant, or Data.Profunctor.Profunctor.
  
  src/FunctorAlpha.purs:
      5 data TypedCache :: (Type -> Type) -> Type -> Type
  
      6 data TypedCache key a = Get (key a)
                                         ^
      7
```

Renaming `k` to `key` make this example compile again. Indeed, you can instead add a redundant `Functor key` constraint in scope makes the derive declaration compile again, though it is not possible to use it since `key` is now ambiguous:
```purescript
-- Succeeds:
derive instance (Functor key, Functor k) => Functor (TypedCache k)

-- Fails:
ex :: forall f a. TypedCache f a -> TypedCache f a
ex = map identity
```

Another example that should work but doesn't without `Functor key` in scope:
```purescript
module FunctorAlpha where

import Prelude
import Data.Coyoneda

data TypedCache :: (Type -> Type) -> Type -> Type
data TypedCache key a = Get (key a)

-- Should work, but fails with same error:
derive instance Functor (TypedCache (Coyoneda k))
-- Actually derives, but fails on usage:
-- derive instance (Functor key) => Functor (TypedCache (Coyoneda k))
```

It seems like when we look up the dictionary in `hasInstance` we've ended up taking the name from the constructor declaration, not the instance head:
https://github.com/purescript/purescript/blob/df5fcff1c396d520e8543d5d85ce1455e56e2696/src/Language/PureScript/TypeChecker/Deriving.hs#L514-L524

I'll look into it a bit more as time allows but I'm not familiar with what the code is doing yet.

### PR DESCRIPTION
**Pull request by rhendric**
**Description of the change**

Fixes #4431.

---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [ ] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [ ] Updated or added relevant documentation
- [x] Added a test for the contribution (if applicable)

### CODE REVIEW

**Review by garyb — APPROVED** [review]

**Review by thomashoneyman — APPROVED** [review]

**Comment by MonoidMusician** [comment]
Thanks for the quick response!

Running `stack test` locally hangs when it gets to the compiler examples, and it looks like CI also stalled:
```
  Language.PureScript.Ide.Usage
    Finding Usages
      finds a simple usage [✔] (3ms)
      finds a simple recursive usage [✔] (2ms)
      ignores a locally shadowed recursive usage [✔] (2ms)
      finds a constructor usage [✔] (2ms)
      finds a constructor alias usage [✔] (3ms)
      finds a reexported usage [✔] (2ms)
compiler
  Passing examples
    '1110.purs' should compile and run without error [ ]
```

([1110.purs](https://github.com/purescript/purescript/blob/master/tests/purs/passing/1110.purs) doesn't have deriving, it's likely stuck on building the libraries …)

**Comment by rhendric** [comment]
Oh shoot. Everything worked until I started doing clean-up refactorings, and I'm pretty sure there's only one of those that could cause an infinite spin.

**Comment by MonoidMusician** [comment]
I was trying to only cancel one job to see what was happening, but it looks like I killed them all.

Another run locally got further but still appeared to stall, this time on a deriving example:
```
  Language.PureScript.Ide.Usage
    Finding Usages
      finds a simple usage [✔] (2ms)
      finds a simple recursive usage [✔] (2ms)
      ignores a locally shadowed recursive usage [✔] (3ms)
      finds a constructor usage [✔] (3ms)
      finds a constructor alias usage [✔] (2ms)
      finds a reexported usage [✔] (2ms)
compiler
  Passing examples
    '1110.purs' should compile and run without error [✔] (1262ms)
    .........
    .........
    'DeepCase.purs' should compile and run without error [✔] (184ms)
    'DeriveNewtype.purs' should compile and run without error [✔] (162ms)
    'DeriveWithNestedSynonyms.purs' should compile and run without error [✔] (204ms)
    'Deriving.purs' should compile and run without error [✔] (200ms)
    'DerivingBifunctor.purs' should compile and run without error [ ]^C⏎                                                                                     
```

Running another stack clean and test to verify, but sounds like you'll have it fixed by then 😉

**Comment by MonoidMusician** [comment]
Okay, that fixed the hanging. It appears that looking up type info for each deriving is not ideal though – `Ord1` doesn't need it and it makes `Data.Lazy` fail now:

```
Error found:
in module Data.Lazy
at tests/support/bower_components/purescript-lazy/src/Data/Lazy.purs:64:1 - 64:38 (line 64, column 1 - line 64, column 38)

  Cannot derive a type class instance, because the type declaration for Lazy could not be found.

in value declaration ord1Lazy

See https://github.com/purescript/documentation/blob/master/errors/CannotFindDerivingType.md for more information,
or to contribute content related to this error.
```

The line in question is:
```purescript
derive instance ord1Lazy :: Ord1 Lazy
```

**Comment by rhendric** [comment]
That *is* a twist. I see the problem; now I have to figure out whether I want to be more invasive or less. :thinking:

**Comment by rhendric** [comment]
Think I have it properly sorted now.

**Pull request merged**
