### PR TITLE
Simplify pretty printer for binders

### PR DESCRIPTION
**Pull request by paf31**
This should make the errors in #1218 a bit nicer.

@garyb @nicodelpiano Could you please review?

### CODE REVIEW

**Comment by garyb** [comment]
Looks good from trying to read the code, but I probably can't tell without seeing the differences in output :smile:

**Comment by paf31** [comment]
Sure:

```
> let f s = (prettyPrintBinder <$>) <$> runTokenParser "" parseBinder <$> P.lex "" s

> f "A b c"
Right (Right "A b c")

> f "A b (C d e)"
Right (Right "A b (C d e)")

> f "A (B c) (D e)"
Right (Right "A (B c) (D e)")

> f "A [ B c, D e ]"
Right (Right "A [ B c, D e ]")
```

There is probably a useful QuickCheck test here.

**Comment by paf31** [comment]
I'd actually be in favour of replacing more simple uses of `pattern-arrows` with simple functions like this. The one place where `pattern-arrows` is more useful IMO is when you have a dynamic set of precedence rules (e.g. if we pretty printed inline operators, which we don't). As it is, almost every one of our pretty printers could be simplified by not using it.

**Comment by nicodelpiano** [comment]
I tested it, and it looks good!

```
module Main where
data Tree a = Empty | Leaf a | Branch (Tree a) (Tree a)
f (Leaf 0) Empty = Empty
```

```haskell
Main.Empty
(Main.Leaf _)
(Main.Branch _ _) _
(Main.Leaf 0) (Main.Leaf _)
(Main.Leaf 0) (Main.Branch _ _)
```

That's what I expected to see. Now the general pretty print call should be `prettyPrintBinderAtom`, right? I suspect we should export it from the module.

**Comment by paf31** [comment]
Yes, you need `prettyPrintBinderAtom`. Maybe when you rebase you can export it?

**Pull request merged**
