### PR TITLE
Fix for Issue 3247: Handle exported modules when :browse comman…

### PR DESCRIPTION
**Pull request by omefire**
…d issued

### CODE REVIEW

**Comment by garyb** [comment]
@paf31 I'll get this in for the final release of 0.12 (or the next RC, if we need one).

**Comment by omefire** [comment]
@paf31 @garyb  I can include tests for this in a few days. Sorry, I didn't get notified about these comments.

**Comment by kRITZCREEK** [comment]
Something's not quite right here. I merged this with master and I get this output when browsing `Control.Monad`: https://gist.github.com/kRITZCREEK/bbfe6c935ef4d229788ebddae667218c

The export for `map` is repeated 8 times.

**Comment by hdgarrood** [comment]
I'm going to close this for now due to inactivity. Thanks for the PR nonetheless!

**Pull request closed without merging**
