### PR TITLE
Field puns, fix #921

### LINKED ISSUE #921: Object property punning
When creating or matching objects, I'd really love to be able to write `{ x }` as shorthand for `{ x: x }`:

```purescript
data Person = Person { name :: String, age :: Number }

instance showPerson :: Show Person where
  show (Person { name, age }) = name <> ", who is " <> show age <> " years old"

mkPerson name age = Person { name, age }
```

### PR DESCRIPTION
**Pull request by paf31**
This wasn't in 0.8 but was simple and seemed pretty useful.

### CODE REVIEW

**Comment by garyb** [comment]
Yeeuh! I'd been thinking about getting this in a lot lately too.

Does it/are we going to make it work for construction too? Like:

``` purescript
main = greet { greeting, name } 
  where
  greeting = "Hello"
  name = "World"
```

**Comment by paf31** [comment]
Yep, we can. I wanted to put this PR in to get some comments first.

Actually, I was a bit eager here and just realized that @balajirrao had expressed interest in working on this. Apologies for that, but we could split construction into a separate PR if you're still interested in working on this? No pressure obviously.

**Comment by balajirrao** [comment]
@paf31, yes, I want to work on this. It'll be a great way to start hacking purescript again. I'll send a PR very soon. Thanks!

**Comment by paf31** [comment]
@balajirrao Sounds great! I'll merge this into `master` then, and you can make your PR there.

**Pull request merged**
