### PR TITLE
Revert "Don't require that all types are exported"

### PR DESCRIPTION
**Pull request by garyb**
Reverts purescript/purescript#1525

### CODE REVIEW

**Comment by garyb** [comment]
I'll append the fix for nested synonyms to this branch before merging.

**Comment by paf31** [comment]
Looks good, thanks!

**Comment by garyb** [comment]
Ok I see where the problems come from with this now - we're only looking at the export list and not the actual declarations, hence not following nested synonyms - I'll see about fixing it tomorrow.

**Comment by paf31** [comment]
I think only considering the exports is probably the right thing to do, since the externs should represent the public API of the module (I know this is still up for debate to some extent). Let's discuss a bit more before committing to anything for 0.7.5?

**Comment by garyb** [comment]
Considering the exports _list_ isn't enough though, that's why cases like this:

``` purescript
module Test (X()) where

type X = Y
type Y = Int
```

are not picked up by the current warning.

**Comment by paf31** [comment]
But the purpose of the externs files should be to represent the public API that a module provides, and since `Y` is a part of that right now (I know it might not be in a later version, depending on what we decide about synonyms, but for now...) it should be in externs. So I think that either that exports list should give an error, or (better) automatically desugared in `Names` to include `Y`.

**Comment by garyb** [comment]
That's what I'm talking about - the current check is not good enough to throw the `TransitiveExportError` in the case I mentioned above. I'm not trying to change the behaviour to support a new use case here, this is fixing the existing check so that it actually works properly.

**Comment by paf31** [comment]
Ah I see. You're referring to the check in `Names` then?

I just want to make sure we're not planning on requiring any information not in externs, since obviously we can't rely on that being around in the separate compilation case any more.

**Comment by garyb** [comment]
Yep - I'm just saying that since we're keeping this check for now until we discuss abstraction with synonyms etc. it's probably a good time to fix the various problems with it :smile:

e.g. #1318 and #1179  (although these don't have the problem with invalid externs files now, but they still are wrong as the transitive export check should have rejected them in the first place) and #959

**Comment by paf31** [comment]
:+1: Sounds good to me.

**Comment by paf31** [comment]
@garyb What's the status of this? Are you still planning to update it before 0.7.5, or do you want to merge this now and push any fixes into a patch release?

**Comment by garyb** [comment]
Yep, I'd still like to get it fixed for 0.7.5. Will do so today hopefully.

**Comment by garyb** [comment]
I'm not too sure what to do about this now. The check works even less well than ever because of the change to desugaring:

``` purescript
module Fail1 (fail) where

type X = Int

fail :: X -> X
fail a = a

```
becomes:

``` purescript
module Fail1 (fail) where

type X = Int

fail :: Int -> Int
fail a = a
```

By the time we make this check, so it is no longer able to complain about `X` not being exported.

**Comment by paf31** [comment]
Where are you seeing that desugaring?

**Comment by garyb** [comment]
That's what I see when I trace `fail`'s type from `Environment` when compiling `Fail1`.

I've made improvements anyway - at least it propery requires nested synonyms to be exported and synonyms referenced by data constructors now. Both cases were previously were unchecked.

**Comment by garyb** [comment]
Also, here's the externs file for `Fail1`:

``` json
{
   "efExports":[
      {
         "ValueRef":{
            "Ident":"fail"
         }
      }
   ],
   "efImports":[
      {
         "eiImportedAs":null,
         "eiModule":[
            {
               "runProperName":"Prim"
            }
         ],
         "eiImportType":{
            "Implicit":[

            ]
         }
      }
   ],
   "efVersion":"0.7.4.1",
   "efDeclarations":[
      {
         "EDValue":{
            "edValueType":{
               "tag":"TypeApp",
               "contents":[
                  {
                     "tag":"TypeApp",
                     "contents":[
                        {
                           "tag":"TypeConstructor",
                           "contents":"Prim.Function"
                        },
                        {
                           "tag":"TypeConstructor",
                           "contents":"Prim.Int"
                        }
                     ]
                  },
                  {
                     "tag":"TypeConstructor",
                     "contents":"Prim.Int"
                  }
               ]
            },
            "edValueName":{
               "Ident":"fail"
            }
         }
      }
   ],
   "efFixities":[

   ],
   "efModuleName":[
      {
         "runProperName":"Fail1"
      }
   ]
}
```

**Comment by paf31** [comment]
Ah I always assumed this would happen in `Names`, hence pre-desugaring. Looks good though.

**Comment by garyb** [comment]
Oh right. Yeah, we can't do it there as it the check needs to look at members that have inferred types too. Good point though, maybe I should check twice?

**Comment by garyb** [comment]
Interesting that synonyms aren't desugared in the arguments of data constructors though - maybe they should be too?

**Comment by paf31** [comment]
I don't think we should consider this "desugaring", it's part of type elaboration which happens on types of terms, so it doesn't happen during kind checking, hence not on data constructors.

This is why I'm a little wary of using the `Environment` for things other than type checking.

**Comment by garyb** [comment]
Yeah, desugaring isn't really what I meant - I guess my question was more "if we have to do this for values to get synonym things to work out properly, why not constructors"?

**Comment by garyb** [comment]
I'll merge this once the tests are passed though, I'm happy with it for 0.7.5 as we're going to be looking at the rules for synonyms again anyway. Anything else we need for 0.7.5? I'm looking forward to it being out there :)

**Comment by paf31** [comment]
I don't think so, if you're happy with this, then I think let's release 0.7.5.

**Comment by garyb** [comment]
About time Travis!

:shipit: :ship: :shipit:

**Pull request merged**
