### PR TITLE
Update CONTRIBUTORS.md

### PR DESCRIPTION
**Pull request by robdaemon**
Adding licensing terms per request.

For the record, this was entirely unimposing and lightweight :)

### CODE REVIEW

**Comment by paf31** [comment]
Thanks so much! Could you just fill in the `\<your name\>` template please? :smile:

**Comment by paf31** [comment]
Oh dear, I didn't think an append-only file would be such a pain for merge commits. I'll figure these out :)

**Comment by robdaemon** [comment]
Oops, I missed that "your name" thing - fixed. If you want to change the mechanism here though, that's fine too. Maybe contributors emailing you their response and they can be applied without the merge commits?

**Comment by paf31** [comment]
Yes, I've changed the issue to ask people to just post the markdown in a comment, and I'll copy it manually. I'll copy yours over now.

Thanks!

**Pull request closed without merging**
