### PR TITLE
[psc-ide] adds a reset command

### PR DESCRIPTION
**Pull request by kRITZCREEK**
Let's see how this performs. It's actually so really strange...

### CODE REVIEW

**Comment by kRITZCREEK** [comment]
aaarghghhh

**Comment by kRITZCREEK** [comment]
Restarting CI

**Comment by kRITZCREEK** [comment]
I think this should fix the test failures we are seeing on travis. On top of that it makes the psc-ide tests faster and should prove useful to the editor plugins/pscid for a quick reset.

**Comment by hdgarrood** [comment]
👍 lgtm

**Comment by garyb** [comment]
Me too :+1:

**Pull request merged**
