### PR TITLE
Allow ide module rebuilds without touching fs output/cache-db continued

### PR DESCRIPTION
**Pull request by i-am-the-slime**
Takes over from #4362
Closes #4362
---

**Checklist:**

- [x] Added a file to CHANGELOG.d for this PR (see CHANGELOG.d/README.md)
- [x] Added myself to CONTRIBUTORS.md (if this is my first contribution)
- [x] Linked any existing issues or proposals that this pull request should close
- [x] Updated or added relevant documentation
- [ ] Added a test for the contribution (if applicable)

### CODE REVIEW

**Comment by i-am-the-slime** [comment]
@JordanMartinez I addressed the comments you had in #4362

**Review by JordanMartinez — APPROVED** [review]
Thanks

**Comment by purefunctor** [comment]
Mind adding a CHANGELOG.d entry to this as well?

**Comment by i-am-the-slime** [comment]
@purefunctor sure.
Not sure how to add @wclr to contributors (I have no licence info).

**Comment by JordanMartinez** [comment]
@wclr Since this PR builds on your work and you did not specify a license under which your contributions were made in your former PRs, could you clarify what license you would use?

**Comment by wclr** [comment]
> could you clarify what license you would use

Whatever is most common to use for this purpose, I hardly would like to be a legal person. -)

**Comment by purefunctor** [comment]
@wclr The majority of the `CONTRIBUTORS.md` entries use the MIT license, so we can go with that 😄

If you could add this @i-am-the-slime, I can merge this and close #4362. Thanks a lot again!

**Comment by JordanMartinez** [comment]
The license issue has been addressed. @purefunctor Mind approving this so we can merge?

**Review by purefunctor — APPROVED** [review]

**Pull request merged**
