### PR TITLE
Avoid 'WARNING - If this if/for/while really shouldn't have a body, use ...

### PR DESCRIPTION
**Pull request by jacereda**
...{}' when using the Closure Compiler.

### CODE REVIEW

**Comment by michaelficarra** [comment]
That is a dumb warning. Empty blocks are more empty than empty statements...

Do you have to use closure compiler?

**Comment by garyb** [comment]
> That is a dumb warning.
Haha!

I guess it's more of a lint thing really, strange that closure compiler warns on it.

**Comment by jacereda** [comment]
But it’s easy to forget the semicolon and have something like:

while (foo())
statementIntendedToBeOutOfTheLoop();

Adding an explicit {} is quite common in C land as well, lint tools warn about empty blocks without explicit braces.

I don’t have an immediate need for it, but it should be possible to use the closure compiler and, if possible, without warnings.

**Comment by garyb** [comment]
Oh sure, if this was code you were writing by hand I could understand why it's a warning. I just didn't think linting was closure's responsibility.

**Comment by jacereda** [comment]
It does indeed perform some linting:

https://github.com/google/closure-compiler/blob/8ce967b4c75a6d5f9eef8a9947c8c8b572e1719c/src/com/google/javascript/jscomp/CheckSuspiciousCode.java

https://github.com/google/closure-compiler/tree/8ce967b4c75a6d5f9eef8a9947c8c8b572e1719c/src/com/google/javascript/jscomp/lint

**Comment by paf31** [comment]
Shall I close this then?

**Comment by garyb** [comment]
I don't feel strongly about this either way.

**Pull request closed without merging**
