### PR TITLE
Update generic deriving for latest purescript-generics changes

### PR DESCRIPTION
**Pull request by paf31**
@garyb @gbaz Could you please review this?

- Update to support type constructors in signatures, per https://github.com/purescript/purescript-generics/issues/8
- Make products consistent with the instances in `Data.Generic` by providing fully-qualified data constructor names.

### CODE REVIEW

**Comment by garyb** [comment]
I think this one is more for @sclv than me...

**Comment by gbaz** [comment]
:+1:

**Comment by paf31** [comment]
I've tested this with `purescript-foreign-generics` and it works pretty nicely.

**Comment by paf31** [comment]
Thanks for the review.

**Pull request merged**
