### PR TITLE
Try Trusty dist for Travis

### PR DESCRIPTION
**Pull request by garyb**
Since this does great things for the build time of PS libraries, I wonder if it will help with the compiler build too.

### CODE REVIEW

**Comment by paf31** [comment]
:pray:

**Comment by paf31** [comment]
Maybe we should enable parallel builds?

**Comment by garyb** [comment]
Oh yeah, definitely worth trying that too. Do I just need to take the `sed` line out?

**Comment by garyb** [comment]
Nice, looks like it's a decent bit faster with sequential builds even (20ish mins vs 50ish).

**Comment by paf31** [comment]
Are you comparing even after Harry's change to remove old GHCJS versions?

**Comment by garyb** [comment]
I believe so, see the log here: https://travis-ci.org/purescript/purescript/builds

The build for the whitespace changes is what I was comparing it to.

**Comment by paf31** [comment]
Looks good, the individual builds are down to about 7 minutes :smile:

**Pull request merged**
