### PR TITLE
REPL fixes needed for Eff change

### LINKED ISSUE #3080: Switch from Eff to IO
Optimizer rules need to be updated as part of the switch to `IO` as the default effect monad.

### PR DESCRIPTION
**Pull request by paf31**
To accompany https://github.com/purescript/purescript-eff/pull/27

Closes #3080

Optimizer changes aren't needed if we don't change the module or type names, since the optimizer doesn't know about types anyway, only dictionary names, which won't change.

### CODE REVIEW

**Comment by paf31** [comment]
I have to remember to change the optimizer rules for `ST`, however.

**Comment by paf31** [comment]
I think I should close this and reopen against latest master since it's so out of date.

**Comment by paf31** [comment]
@hdgarrood Which type were you referring to?

**Comment by paf31** [comment]
You could try removing `typeDecl`. I'm not sure if it's needed for any values with polymorphic types, but I can't think of any examples right now.

**Comment by hdgarrood** [comment]
I was referring to the type in `typeDecl`

**Pull request closed without merging**
